### ISSUE TITLE
svg pie not rendered properly in v3.0.4 - 3.0.6

### ISSUE THREAD

**Issue by tjohannto** [canvg/canvg#1001]
I have an issue with a pie-svg which is not rendered properly after v3.0.2 

I have created an fiddle showing the error:

https://jsfiddle.net/gothmogg/hgkescuf/

![image](https://user-images.githubusercontent.com/45257386/77733868-dfcc1f80-7007-11ea-9bcc-c1c4c394d5c5.png)

This error appears on Firefox as well as on chrome on 3 different machines (but all Win 10 64bit).
v3.0.2 does work fine but all other later versions I have tested show this error.

Can you confirm or reproduce this error as it does not seem to exist on old Win7 machines?

**Comment by dangreen** [comment]
Fixed in [v3.0.7](https://github.com/canvg/canvg/releases/tag/v3.0.7)
