### ISSUE TITLE
this.DOMParser is not a constructor

### ISSUE THREAD

**Issue by wangyanqi-hunch** [canvg/canvg#1034]
worker 
offscreen

**Comment by dangreen** [comment]
@wangyanqi-hunch Hi. Please provide code example.

**Comment by wangyanqi-hunch** [comment]
index.js:

  var worker = new Worker();
      const canvas = this.$refs.canvas;
      const offscreen = this.$refs.canvas.transferControlToOffscreen();
      worker.postMessage(
        {
          svg: svgDom,
          canvas: offscreen
        },
        [offscreen]
      );
      worker.onmessage = function(event) {
        console.log("111", event);
        worker.terminate();
      };
    },


worker:

import Canvg, {
  presets
} from 'canvg';


let x = 20;
let speed = 5;
let textNnm = 0;

onmessage = function (evt) {
  const {
    svg,
    canvas
  } = evt.data;
  const context = canvas.getContext("2d");
  let v = null;
  v = Canvg.fromString(
    context,
    svg,
    presets.offscreen()
  );

};
