### ISSUE TITLE
TextPath is not yet implemented 

### ISSUE THREAD

**Issue by gabelerner** [canvg/canvg#111]
_From [mustafee...@confiz.com](https://code.google.com/u/116048375095009012107/) on October 06, 2011 00:58:35_

What steps will reproduce the problem? 1. Pasted the below SVG into the test page

<svg width="12cm" height="3.6cm" viewBox="0 0 1000 300" version="1.1"
     xmlns=" http://www.w3.org/2000/svg "
xmlns:xlink=" http://www.w3.org/1999/xlink ">
  <defs>
    <path id="MyPath"
          d="M 100 200 
             C 200 100 300   0 400 100
             C 500 200 600 300 700 200
             C 800 100 900 100 900 100" />
  </defs>
  <desc>Example toap01 - simple text on a path</desc>
  <use xlink:href="#MyPath" fill="none" stroke="red"  />
  <text font-family="Verdana" font-size="42.5" fill="blue" >
    <textPath xlink:href="#MyPath">
      We go up, then we go down, then up again
    </textPath>
  </text>
  
  <rect x="1" y="1" width="998" height="298"
        fill="none" stroke="blue" stroke-width="2" />
</svg> What is the expected output? What do you see instead? expected output would be to render text path and load it into canvas but instead of loading into canvas it gave me an error which is : 

ERROR: Element 'textPath' not yet implemented.
ERROR: Element 'textPath' not yet implemented.
child.measureText is not a function
[Break On This Error] x = child.x + child.measureText(ctx); What version of the product are you using? On what operating system? i am using your online library. Please provide any additional information below. Please solve this issue as soon as possible because I'm fully dependent on this library.

_Original issue: http://code.google.com/p/canvg/issues/detail?id=111_

**Comment by Gregoor** [comment]
hey, thanks for open sourcing this!
I guess this is closed as in "not going to happen"?

**Comment by gabelerner** [comment]
closed by https://github.com/canvg/canvg/pull/687
