### ISSUE TITLE
Add warning to OffscreenCanvas example

### ISSUE THREAD

**Issue by Viliasas** [canvg/canvg#1133]
Hello,

I've been using OffscreenCanvas with canvg while developing on Chrome and didn't consider that it could be not fully supported by all major browsers... It would be good to add a warning to OffscreenCanvas example that it's not supported on Safari and Firefox (https://developer.mozilla.org/en-US/docs/Web/API/OffscreenCanvas#Browser_compatibility).

**Comment by gabelerner** [comment]
i do not believe it's on us to add a warning for several reasons:
- there's no clarity as to when we remove the warning (what does "major" mean?) and how we would keep it in sync with browser development.
- as a developer you have choice of canvas or offscreen and should make the appropriate tradeoffs yourself based on who your users will be and what you are targeting.
- as far as i remember, we don't default to offscreen - if we did then a warning might be appropriate

**Comment by dangreen** [comment]
Released in [v3.0.7](https://github.com/canvg/canvg/releases/tag/v3.0.7)
