### ISSUE TITLE
Remove polyfills?

### ISSUE THREAD

**Issue by tiberiumihai** [canvg/canvg#1253]
Hello,

I'm using lib with angular and angular-cli >=v8.0.0 auto-handles the core-js polyfills imports.

Is there any canvg bundle without them?

My angular app bundle size was grown by >164 KB because of this issue.
![image](https://user-images.githubusercontent.com/12754525/97047238-51aa1e80-1581-11eb-9790-48c2a81d9f07.png)

There are also warnings thrown by the angular cli:
```
WARNING in /web/node_modules/canvg/lib/index.es.js depends on '@babel/runtime-corejs3/core-js-stable/object/define-property'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies
```

Thanks!

**Comment by dangreen** [comment]
@tiberiumihai Hi.

You can modify your webpack config to handle [index.babel.js](https://unpkg.com/browse/canvg@3.0.7/lib/index.babel.js) bundle following some steps from [this](https://github.com/TrigenSoftware/bdsl-webpack-plugin/tree/master/examples/transpile-dependencies) instruction.

**Comment by tiberiumihai** [comment]
I think I'll pass. I don't want to extract ng webpack config. It would make ng upgrades complicated later on.
The project uses jspdf which have an optionalDependency of canvg and gets installed automatically.
I'll close this one and open an issue there.
Thanks!
