### ISSUE TITLE
Import canvg fail

### ISSUE THREAD

**Issue by Undo101** [canvg/canvg#1302]
After I installed and import Canvg into my program, I got an ESLint-related error on the console. It looks like the dependencies in the plugin haven't been installed caused. How can I fix this, thank you
![image](https://user-images.githubusercontent.com/26062774/104428321-4cc49c00-55bf-11eb-96be-d73daea9d523.png)

**Comment by dangreen** [comment]
@Undo101 Hi. Your eslint config should ignore `node_modules/**/*`.

**Comment by Undo101** [comment]
I did it, but it didn't work. And my packaging tool is rollup.js.

**Comment by Undo101** [comment]
> @Undo101 Hi. Your eslint config should ignore `node_modules/**/*`.

I did it, but it didn't work. And my packaging tool is rollup.js.

**Comment by Undo101** [comment]
I suspect that Canvg uses its own ESLint rules, which have nothing to do with my project rules. Why doesn't Canvg add these dependencies internally？

**Comment by dangreen** [comment]
@Undo101 

1) this config is located in stackblur-canvas package, not in canvg
2) you should configure your tools to ignore configs from node_modules
3) “ add these dependencies internally”, they are already internally (node_modules)

**Comment by Undo101** [comment]
@dangreen 
Thank you for your prompt reply, it should be caused by the wrong packing method, let me take a look。
