### ISSUE TITLE
foreignObject is not displaying

### ISSUE THREAD

**Issue by Battledash-2** [canvg/canvg#1383]
# While trying to use the foreignObject nothing inside of the tag is displayed.

## Expected result:
![expected](https://user-images.githubusercontent.com/69129349/112395109-30865f00-8cd4-11eb-8928-49790d9e7699.PNG)

## Actual Result:
![result](https://user-images.githubusercontent.com/69129349/112395168-4562f280-8cd4-11eb-87fb-24c9c6446e5d.PNG)

### Here's the code I'm using:
```svg
<svg xmlns="https://www.w3.org/2000/svg">
    <foreignObject x="50" y="50">
        <body x="50" y="50" xmlns="https://www.w3.org/1999/xhtml">
            <p>Hello!</p>
        </body>
    </foreignObject>
</svg>
```

# I'm not looking for a 'will never support this' answer btw :/

**Comment by gabelerner** [comment]
will never support this per https://github.com/canvg/canvg/issues/671 because we're in the business of rendering SVG, not HTML on a canvas.

you can use https://html2canvas.hertzen.com/ if you want to render html on a canvas in combination with canvg.

**Comment by Battledash-2** [comment]
How would HTML2CANVAS work in NodeJS?

**Comment by gabelerner** [comment]
i think you'd have to petition that repo to make the same abstractions we did where it works in both browser and node!

alternatively, if you're already on a server you can use a lot of tools to render html to an image, then drop the image into the svg.
