### ISSUE TITLE
Unable to convert the SVG image into canvas - canvg v3.0.7

### ISSUE THREAD

**Issue by akashishu777** [canvg/canvg#1391]
In canvg v2.0.0 I am able to convert the SVG image into canvas but unable to do the same in v3.0.7 

```
import * as canvg from 'canvg';
                        
// Converting the SVG image into canvas.
const canvas = document.createElement("canvas");
canvas.setAttribute('id', 'canvas-test');
const svg = plotlyParts.querySelectorAll(".main-svg");
const innerSvg = '' + (new XMLSerializer()).serializeToString(svg[0]);

canvg(canvas, innerSvg); // <------- Producing Error
```

"canvg": "^3.0.7" Error: // Value of type 'type of Canvg' is not callable. Did you mean to include 'new'?ts(2348)

**Comment by gabelerner** [comment]
The interface changed between major version 2 and 3. Please see the readme on how to use canvg v3.
