### ISSUE TITLE
Progress Reporting

### ISSUE THREAD

**Issue by gabelerner** [canvg/canvg#14]
_From [codedr...@gmail.com](https://code.google.com/u/108240851375674070640/) on March 31, 2010 07:47:52_

It would be great to figure out a way to report progress of parsing of SVG
into canvas, particularly with large SVG files for which canvg can take
some perceptible time.

One idea:
- have a 'setProgressFunction(func)' function that allows the user to send
  a callback function that canvg remembers
- Upon parsing hte XML, get a tally of all elements in the document:
  var total = document
  document.documentElement.getElementsByClassName('*').length
- every time we enter RenderedElementBase() we count up a count variable
  and if we go up a percentage point then send a notification with the
  progress to the progress function

_Original issue: http://code.google.com/p/canvg/issues/detail?id=14_

**Comment by agnivade** [comment]
Hi, I have an svg element which seems to take noticeable amount to render. The svg is loaded as a string. The problem due to this is I am trying to import the resulting output as a texture in a threejs scene, and all I am getting is a black output.
