### ISSUE TITLE
Support CSS

### ISSUE THREAD

**Issue by gabelerner** [canvg/canvg#143]
_From [tomithy....@gmail.com](https://code.google.com/u/110488834238757311725/) on May 17, 2012 11:54:00_

What steps will reproduce the problem? 1. Current Canvg does not support the inclusion of css What is the expected output? What do you see instead? Takes in a CSS text and a svg DOM to create a rendered image with the style defined inside the CSS file.

_Original issue: http://code.google.com/p/canvg/issues/detail?id=143_

**Comment by thelordgabo** [comment]
I continue having the problem :

<svg width="800" height="567" style="overflow: hidden;" class="c3" ...

the  class "c3" is not applied.
