### ISSUE TITLE
canvg does not convert my svg files

### ISSUE THREAD

**Issue by gabelerner** [canvg/canvg#144]
_From [diego.ce...@gmail.com](https://code.google.com/u/100232016821022884478/) on May 26, 2012 16:31:33_

What steps will reproduce the problem? 1.try to convert the attached file using canvg What is the expected output? What do you see instead? Using other library ( http://xmlgraphics.apache.org/batik/ ) i got the attached png file. When i use canvg my canvas still blank. What version of the product are you using? On what operating system? - canvg 1.1
- I'm using Firefox 12 on Mac OsX Lion Please provide any additional information below. I think the problem is in viewBox attribute of svg tag. When i tryed to convert using other files (without viewBox attribute) canvg works like expected.

**Attachment:** [draft4.svg draft4.png](http://code.google.com/p/canvg/issues/detail?id=144)

_Original issue: http://code.google.com/p/canvg/issues/detail?id=144_

**Comment by sudeep350** [comment]
Hi, 
I am facing formatting issue while converting SVG to canvas.  i have attached two SVG below. 
[svg.zip](https://github.com/gabelerner/canvg/files/377600/svg.zip)

so when I convert these svg into canvas , we are not getting desired output.  Please see canvas output file
[CanvasOuput.pdf](https://github.com/gabelerner/canvg/files/377612/CanvasOuput.pdf)

Here one SVG got reversed and other one got rotated.  Can you please take a look and let me the know the issue.
