### ISSUE TITLE
3.0.8 breaks require("canvg")

### ISSUE THREAD

**Issue by shanebdavis** [canvg/canvg#1484]
3.0.7 works with require("canvg")

> (NodeJS v14.17.0; NPM v7.6.0)

I understand there is a desire to move towards ES modules, but 3.0.8 was a patch update; it shouldn't cause breaking changes. If such a breaking change is needed to further ES-module support, that should be a major version change e.g. 4.0.0.

I'd like to request a 3.0.9 release that restores CommonJS compatibility and a 4.0.0 release with the new ES-module changes.

**Comment by dangreen** [comment]
@shanebdavis can you try canvg@3.0.9 ?

**Comment by Jason-Morcos** [comment]
3.0.9 still appears broken to me. 3.0.7 works perfectly (I use canvg as part of a process to download an SVG as an image) but 3.0.8 and 3.0.9 both only produce a blank white image. Honestly I'm not sure what issues it's related to and am happy to open a new issue certainly, but it appears to me likely related to 3.0.8 generally being a patch-release-regression and I'm not sure what, if anything, makes my setup unique. I use Canvg in the `import Canvg from 'canvg';` style, but I use it in a web application so it makes me think that perhaps this is related to changing the type of the package as 3.0.8 did. I have no errors in my console nor when webpacking, it just downloads a blank image.

**Comment by dangreen** [comment]
Closed due to inactivity.
