### ISSUE TITLE
Can't resolve 'process/browser'

### ISSUE THREAD

**Issue by RibikiH** [canvg/canvg#1519]
Hi

Firstly, Thank for your work.

I use webpack 5.1 and canvg 3.0.9
Today when complie I get this error log
```
ERROR in ./node_modules/canvg/lib/index.es.js 1933:16-23
Module not found: Error: Can't resolve 'process/browser' in '*****\node_modules\canvg\lib'       
Did you mean 'browser.js'?
BREAKING CHANGE: The request 'process/browser' failed to resolve only because it was resolved as fully specified 
(probably because the origin is a '*.mjs' file or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.
```

Have any idea thank!

**Comment by dangreen** [comment]
@RibikiH Hi. Can you provide repo with minimal code to reproduce this issue?

**Comment by smujaddid** [comment]
> Sorry, this my fault. Thank you for your interest.

Hi! How did you resolve this issue? Can you share it here?

**Comment by RibikiH** [comment]
> Hi! How did you resolve this issue? Can you share it here?
You can read issue:
https://github.com/microsoft/PowerBI-visuals-tools/issues/365

**Comment by robsilva** [comment]
Has anyone been able to solve this?

**Comment by robsilva** [comment]
For those in the same boat, I was able to solved it by adding a new rule to webpack (version 5):
```
modules: {
  rules: [
    {
        test: /\.m?js$/,
        resolve: {
          fullySpecified: false,
        },
      },
      ...
  ]
}
```

**Comment by sjonchhe** [comment]
has anybody solved it using craco?

**Comment by Rennix09** [comment]
> For those in the same boat, I was able to solved it by adding a new rule to webpack (version 5):
> 
> ```
> modules: {
>   rules: [
>     {
>         test: /\.m?js$/,
>         resolve: {
>           fullySpecified: false,
>         },
>       },
>       ...
>   ]
> }
> ```

save my day, thanks very much!
