### ISSUE TITLE
ie fails to display the actual font size.

### ISSUE THREAD

**Issue by gabelerner** [canvg/canvg#152]
_From [PabL...@gmail.com](https://code.google.com/u/115628364813892989508/) on July 03, 2012 12:24:18_

What steps will reproduce the problem? 1. I have a svg generated with protovis. the font size is seems to be fine on the svg. What is the expected output? What do you see instead? expected: a canvas with the current font size.

actual: on Internet explorer the font size changes. I have no problems with others browsers. What version of the product are you using? On what operating system? v 1.1 ,microsoft windows 7. Please provide any additional information below. this only happens with internet explorer.

_Original issue: http://code.google.com/p/canvg/issues/detail?id=152_

**Comment by codeSasquatch** [comment]
my fix for IE was to add the style of the Body into my svg element directly before doing any transforms with scaling etc.

<svg text-anchor="middle" font-size="14px" font-weight="normal" style="line-height:1.4285" font-family="Arial"> 

bootstrap and change the font to what I wanted to be printed, before I could apply transforms with scaling and other classes to override the styles.

my .css file body
body {
  font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
  font-size: 14px;
  line-height: 1.42857143;
  color: #333;
  background-color: #fff;
}
