### ISSUE TITLE
CSS Custom Properties not supported

### ISSUE THREAD

**Issue by jkjustjoshing** [canvg/canvg#1568]
[CSS Custom Properties](https://developer.mozilla.org/en-US/docs/Web/CSS/--*) (also known as "CSS Variables") are supported in all browsers. The below should cause all `<rect>`s to fill with red, but canvg does not honor this.

```
rect {
  --fill: red;
  fill: var(--fill, green); /* if --fill is not set, fall back to green */
}
```

![image](https://user-images.githubusercontent.com/813192/147298062-8a75ef37-6424-46d3-b055-9779001b9996.png)

**Comment by gabelerner** [comment]
This probably will go into the WONTFIX thread https://github.com/canvg/canvg/issues/671.  Just like foreign object support, the goal of `canvg` is to come close to the svg spec, not the html/css spec.  It's unlikely that we would ever support all of css in this library and today it's just simple classes, tags, and fonts.  We don't support many other selectors, pseudo-anything, at-rules, etc.  That said, if you find this feature is important for your particular project, we're open to PRs.  The file to change would be here: https://github.com/canvg/canvg/blob/master/src/Document/StyleElement.ts

**Comment by jkjustjoshing** [comment]
I was able to do a workaround by doing a find+replace of all CSS Variables with their values before passing to canvg. Thanks!
