### ISSUE TITLE
Access parsed data?

### ISSUE THREAD

**Issue by Nineswiss** [canvg/canvg#1574]
This might be a silly question but is there any way to get the actual parsed svg data (x,y, width, fill, paths etc)? They idea being that I can store the parsed data and manipulate or save (as json) the image.

**Comment by gabelerner** [comment]
Not a silly question.

When you do
`c = Canvg.fromString(ctx, '<svg><text x="50" y="50">Hello World!</text></svg>')`, you can access `c.documentElement` which is a subclass of https://github.com/canvg/canvg/blob/master/src/Document/Element.ts.  That means it has a `children` property and you can dive into it and get the child elements which are also subclasses of `Element`.  You can look at the `type` property or use `instanceof` to see which exact element it is from the list here: https://github.com/canvg/canvg/tree/master/src/Document.  Then you can access other properties on it (i.e. a https://github.com/canvg/canvg/blob/master/src/Document/PathElement.ts has a `pathParser` to help you).
