### ISSUE TITLE
2.0.0 drawSvg not maintaining aspect ratio width/height specified in svg

### ISSUE THREAD

**Issue by almercier** [canvg/canvg#1576]
I'm trying to upgrade to 2.0.0 from an unknown very old version of canvg, and I'm seeing breaking behavior when using drawSvg.

Here's a fiddle showing the behavior. Previously the aspect ratio of the width/height inside the SVG would have been maintained but now the width/height appears to be completely disregarded and instead stretched to fit the entire area given.
http://jsfiddle.net/Mercieral/g0eraLy2/12/
```javascript
var my_canvas = document.getElementById('canvas'),
    context = my_canvas.getContext("2d");

context.fillStyle = "orange";
context.fillRect(75,50,50,100);

const arrowSVG = 
`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 98.148499 64.038498" y="0" x="0" height="64.038498" width="98.148499">
	<path d="m 0.5865,16.402 47.072,47.074 c 0.75,0.75 2.078,0.75 2.828,0 l 47.076,-47.075 c 0.375,-0.375 0.586,-0.884 0.586,-1.414 0,-0.53 -0.211,-1.039 -0.586,-1.414 L 84.5755,0.586 C 84.1845,0.195 83.6735,0 83.1615,0 c -0.512,0 -1.023,0.195 -1.414,0.586 L 49.0735,33.26 16.3985,0.587 c -0.75,-0.751 -2.078,-0.75 -2.828,0 L 0.5865,13.574 c -0.782,0.781 -0.782,2.047 0,2.828 z"/>
</svg>
`;

context.fillStyle = "black";
context.translate(75, 50);
context.drawSvg(arrowSVG, 0, 0, 50, 100);
```
![image](https://user-images.githubusercontent.com/30079507/149238360-215e7801-2699-45b6-a2b4-6bf307f1db7d.png)

Actual SVG
![image](https://user-images.githubusercontent.com/30079507/149260310-9defca13-407d-4e98-bf6d-d609aa0996d8.png)

Is this expected? From my understanding of the spec, `preserveAspectRatio="xMidYMid meet"` should be the default handling of svgs in spaces where the aspect ratio is different. 

How can I make sure the aspect ratio is preserved instead of stretching the svg on 2.0.0 without having to manually figure out the width/height to pass into drawSvg?

Not sure if it helps, but on the old implementation we were doing this. I removed the contextRender function call as that does not seem to be needed anymore in 2.0.0, but I'm wondering if that has something to do with my issue...?
```javascript
let svgRender = context.drawSvg(svgText, x, y, w, h);
svgRender.contextRender(context, x, y, w, h);
```

**Comment by gabelerner** [comment]
I think the functionality has been replaced with:
![image](https://user-images.githubusercontent.com/241819/149383519-4492a903-19db-4d10-a52c-002419c80d92.png)

that's what we use on the example page: http://canvg.github.io/canvg/demo/index.html
try pasting your svg and filling in the width height and clicking render w/ and w/o the resize checked

**Comment by almercier** [comment]
That does fix it.

That leads me to my other question regarding default behavior then. Mozilla's documention [here](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/preserveAspectRatio#svg) indicates that "xMidYMid meet" should be default behavior for SVGs, and since I'm not overriding preserveAspectRatio in the SVG text I would have assumed I wouldn't have to resize using that algorithm. What's the intention for requiring the user to manually call resize?

**Comment by almercier** [comment]
I also was trying to use 2.0.0's drawSvg instead of Canvg.from w/ render in v3, because I explicitly do not want to have the running interval loop which appears to be running using the code below

```javascript
if (t.svgRender == null) {
    t.svgRender = Canvg.fromString(g, arrowSvgText, {
        ignoreMouse: true,
        ignoreAnimation: true,
        ignoreDimensions: true,
        ignoreClear: true,
        offsetX: x,
        offsetY: y,
        scaleWidth: w,
        scaleHeight: h,
    });
    t.svgRender.resize(w, h, 'xMidYMid meet');
}
t.svgRender.render();
```

**Comment by gabelerner** [comment]
@dangreen do you have insight into why this new API was chosen?

**Comment by dangreen** [comment]
@almercier

> Mozilla's documention here indicates that "xMidYMid meet" should be default behavior for SVGs

It will work if you remove `width` and `height` from your SVG. This behavior is valid as for browser and as for canvg.

with size:

<img width="1365" alt="Снимок экрана 2022-01-15 в 13 55 48" src="https://user-images.githubusercontent.com/986756/149612655-5bd47976-ca66-436c-b06f-52e19510ffee.png">

without:

<img width="1365" alt="Снимок экрана 2022-01-15 в 13 54 17" src="https://user-images.githubusercontent.com/986756/149612659-c3003395-901f-4b53-a0c5-1d4d5cf9fc6f.png">
