### ISSUE TITLE
Release notes for 3.0.10

### ISSUE THREAD

**Issue by almercier** [canvg/canvg#1592]
Got the notice of an update yesterday, but do not see any release notes available for this version.

**Comment by serenecloud** [comment]
Same here today, so I did some digging and the changes I can see are:

1. Updated versions of dependencies with renovate bot
2. Fixed "TypeError: node.getAttribute is not a function" when SVG contains FeColorMatrixElement nodes #1516 
3. Fixed positioning of nested tspans #1563

**Comment by almercier** [comment]
Thanks @serenecloud !
