### ISSUE TITLE
Canvg 3.0.10 isn't compatible with Typescript 4.4+

### ISSUE THREAD

**Issue by serenecloud** [canvg/canvg#1623]
Hi,

We're in the process of upgrading our libraries (also using renovate) and our CI pipeline fails when trying to upgrade from Typescript 4.2.x to 4.5.x because of the removal of `OffscreenCanvas` and `OffscreenCanvasRenderingContext2D` in Typescript 4.4: https://github.com/microsoft/TypeScript-DOM-lib-generator/issues/1029#issuecomment-869224737

```
tsc --noEmit
node_modules/canvg/lib/Document/Document.d.ts(12,91): error TS2304: Cannot find name 'OffscreenCanvas'.
node_modules/canvg/lib/presets/offscreen.d.ts(19,50): error TS2304: Cannot find name 'OffscreenCanvas'.
node_modules/canvg/lib/types.d.ts(1,69): error TS2304: Cannot find name 'OffscreenCanvasRenderingContext2D'.
```

I'm not sure how easy a fix for this will be, but I hope this issue can help others seeing similar logs in after upgrading.

**Comment by dangreen** [comment]
@serenecloud Hi. Please try [canvg@v4](https://www.npmjs.com/package/canvg/v/4.0.0).

**Comment by serenecloud** [comment]
Hi @dangreen - thanks so much for the quick reply and the new version! We've upgraded to v4 and everything looks great!
