### ISSUE TITLE
Scaling Highcharts via cang results in scaled but cropped image

### ISSUE THREAD

**Issue by gabelerner** [canvg/canvg#165]
_From [jamie.po...@gigaom.com](https://code.google.com/u/109448359172267269184/) on August 27, 2012 19:22:01_

What steps will reproduce the problem? 1. Create graph in Highcharts.
2. Convert graph to canvas with scale attributes
3. Observe that graph is scaled but bounds of SVG have not grown to match.

Example here: http://jsfiddle.net/UVNvh/3/ What is the expected output? What do you see instead? Expect to see the scaled graph with the new dimensions. What version of the product are you using? On what operating system? Hightcharts is at 2.3.0 and using 1.2 of canvg. Please provide any additional information below.

_Original issue: http://code.google.com/p/canvg/issues/detail?id=165_

**Comment by morganzysman** [comment]
I have a similar issue, my PNG are only half way generated on IE. 
Any ideas?

<img width="584" alt="screen shot 2017-11-10 at 09 25 01" src="https://user-images.githubusercontent.com/5576762/32659546-ff151434-c5fd-11e7-8890-743b813f66a9.png">

**Comment by gabelerner** [comment]
if this is still an issue, please provide example svgs or jsfiddles with the newest releases
