### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by oguzhanet** [canvg/canvg#1650]
### Would you like to work on a fix?

- [ ] Check this if you would like to implement a PR, we are more than happy to help you go through the process.

### Current and expected behavior

After updating our site to Angular 10 -> 11, we are noticing lots of third party warnings in the build as shown below. It would be nice if the warnings was handled in canvg.

Warning: C:\Project\VPDP\vpdpwebapp\vpdp\node_modules\canvg\lib\index.es.js depends on 'core-js/modules/es.regexp.to-string.js'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

Warning: C:\Project\VPDP\vpdpwebapp\vpdp\node_modules\canvg\lib\index.es.js depends on 'core-js/modules/es.promise.js'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

Warning: C:\Project\VPDP\vpdpwebapp\vpdp\node_modules\canvg\lib\index.es.js depends on 'core-js/modules/es.string.trim.js'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

Warning: C:\Project\VPDP\vpdpwebapp\vpdp\node_modules\canvg\lib\index.es.js depends on 'core-js/modules/es.array.reverse.js'. CommonJS or AMD 
dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

Warning: C:\Project\VPDP\vpdpwebapp\vpdp\node_modules\canvg\lib\index.es.js depends on 'core-js/modules/es.string.includes.js'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

Warning: C:\Project\VPDP\vpdpwebapp\vpdp\node_modules\canvg\lib\index.es.js depends on 'core-js/modules/es.array.reduce.js'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

Warning: C:\Project\VPDP\vpdpwebapp\vpdp\node_modules\canvg\lib\index.es.js depends on 'core-js/modules/es.string.split.js'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

Warning: C:\Project\VPDP\vpdpwebapp\vpdp\node_modules\canvg\lib\index.es.js depends on 'core-js/modules/es.array.index-of.js'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

Warning: C:\Project\VPDP\vpdpwebapp\vpdp\node_modules\canvg\lib\index.es.js depends on 'core-js/modules/es.string.ends-with.js'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

Warning: C:\Project\VPDP\vpdpwebapp\vpdp\node_modules\canvg\lib\index.es.js depends on 'core-js/modules/es.string.starts-with.js'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

Warning: C:\Project\VPDP\vpdpwebapp\vpdp\node_modules\canvg\lib\index.es.js depends on 'core-js/modules/es.string.match.js'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

Warning: C:\Project\VPDP\vpdpwebapp\vpdp\node_modules\canvg\lib\index.es.js depends on 'core-js/modules/web.dom-collections.iterator.js'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

Warning: C:\Project\VPDP\vpdpwebapp\vpdp\node_modules\canvg\lib\index.es.js depends on 'core-js/modules/es.string.replace.js'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

Warning: C:\Project\VPDP\vpdpwebapp\vpdp\node_modules\canvg\lib\index.es.js depends on 'core-js/modules/es.array.iterator.js'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

### Reproduction

1

### Canvg version

v3.0.10

**Comment by dangreen** [comment]
@oguzhanet Hi. Did you try canvg@v4 ?

**Comment by oguzhanet** [comment]
@dangreen Yes, I tried. Same way.

**Comment by dangreen** [comment]
@oguzhanet are you sure? V4 doesn't depends on core-js

**Comment by oguzhanet** [comment]
![Capture](https://user-images.githubusercontent.com/77545698/162144408-526302a5-16ce-4d42-bb99-f18aa4f34c24.PNG)

Same

**Comment by dangreen** [comment]
@oguzhanet  it's canvg of jspdf.

Just configure your builder as described in link from logs (https://angular.io/guide/build#configuring-commonjs-dependencies).
