### ISSUE TITLE
how to introduce with html page using script tag directly?

### ISSUE THREAD

**Issue by honghh2018** [canvg/canvg#1693]
### Would you like to work on this feature?

- [X] Check this if you would like to implement a PR, we are more than happy to help you go through the process.

### What problem are you trying to solve?

Hi developer, thanks to develop this great tools.
   I had a question about how to introduce the canvg using <script src="./canvg.js"></script> directly without the npm build?
 
when introduce it by script tag , how can i using the below code:

    window.onload = async () => {
        const canvas = document.querySelector('canvas');
        const ctx = canvas.getContext('2d');
        ctx.fillRect(50,50,30,40)

        v = await Canvg.from(ctx, './svgs/1.svg');

thanks
Best
hanhuihong

### Describe the solution you'd like

 introduce the canvg using html script tag

**Comment by gabelerner** [comment]
https://codesandbox.io/s/github/canvg/canvg/tree/master/sandboxes/browser?from-embed
