### ISSUE TITLE
Incorrect stroke and radial gradient

### ISSUE THREAD

**Issue by gabelerner** [canvg/canvg#172]
_From [jndi...@gmail.com](https://code.google.com/u/110245169003707871602/) on September 14, 2012 08:00:56_

What steps will reproduce the problem? 1. Look at the attached svg in a browser, and in canvg. What is the expected output? What do you see instead? No black stroke should appear and the radial gradient at the ends should match the linear in the middle. What version of the product are you using? On what operating system? canvg r144 , Chrome and other browsers. Please provide any additional information below.

**Attachment:** [cylinder.svg](http://code.google.com/p/canvg/issues/detail?id=172)

_Original issue: http://code.google.com/p/canvg/issues/detail?id=172_

**Comment by chpio** [comment]
it seems to default to `stroke="black"` but the [default](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/stroke) is `stroke="none"`

**Comment by gabelerner** [comment]
i have it set to fully transparent initially https://github.com/canvg/canvg/blob/master/src/canvg.js#L1185 ... @chpio can you provide an explicit example where it's rendering as black but shouldn't?

**Comment by gabelerner** [comment]
provide example if still relevant issue
