### ISSUE TITLE
IE (10 ?) syntax errors when using <svg xmlns="http://www.w3.org/2000/svg"></svg> declarations

### ISSUE THREAD

**Issue by gabelerner** [canvg/canvg#189]
_From [baptiste...@gomoob.com](https://code.google.com/u/101092238986569751670/) on December 04, 2012 14:41:57_

Hi, I'm trying to output a RaphaelJS SVG element to a base64 image but i've encountered a problem while executing my code under IE (I'm using IE10 but I've tested this in IE9 and IE8 compatibility modes). 

I think my problem comes from the line '137' in 'canvg.js', that's to say on the 'parser.parseFromString(xml, 'text/xml')' instruction. 

My SVG code is the following : 

<svg xmlns=" http://www.w3.org/2000/svg " style="overflow: hidden; position: relative;" width="320" height="240" xmlns=" http://www.w3.org/2000/svg " version="1.1"><desc>Created with RaphaÃ«l 2.1.0</desc><defs /><image preserveAspectRatio="none meet" x="0" y="0" width="320" height="240" xmlns:xlink=" http://www.w3.org/1999/xlink " xlink:href="bd.jpg" /><image preserveAspectRatio="none meet" x="0" y="0" width="45" height="45" xmlns:xlink=" http://www.w3.org/1999/xlink " xlink:href="ico-archi1.png" /></svg>

You can replace the images by whatever you want. 

When I execute canvg on this string IE outputs the following errors : 

SCRIPT5022: SyntaxError 
canvg.js, Ligne 131 Caractère 5
XML5634: Un attribut avec le même nom existe déjà sur cet élément. 
, Ligne 1 Caractère 161

This seems to be a parsing error, if I add the following lines at the beginning of the 'svg.parseXml' function my code now works. 

// -- Internet Explorer trick, otherwise an error is generated in the 'parseFromString' function when 
// -- You use <svg xmlns=" http://www.w3.org/2000/svg"></svg> declarations, this is the case for Raphael
xml = xml.replace(/xmlns=\"http:\/\/www.w3.org\/2000\/svg\"/, '');

Hope this can help... 

Baptiste

_Original issue: http://code.google.com/p/canvg/issues/detail?id=189_

**Comment by jiorgiodavis** [comment]
try this guys, its a mixture of codes i got here. and i modified it. it works for me.
var start = xml.indexOf("<svg");
			var end = xml.lastIndexOf("/svg>");
			xml = xml.substring(start,end+5);
			xml = xml.replace(/xmlns=\"http:\/\/www\.w3\.org\/2000\/svg\"/g, '');
			xml = xml.replace(/xmlns:NS1=\"\"/g, '');
			xml = xml.replace(/NS1:xmlns:xlink=\"http:\/\/www.w3.org\/1999\/xlink\"/g, 'xmlns:xlink=\"http:\/\/www.w3.org\/1999\/xlink\"');
			xml= xml.replace(/xmlns:xlink=\"http:\/\/www.w3.org\/1999\/xlink\" xlink:href/g, 'xlink:href');
			xml = xml.replace(/\/\//g, '' );
			xml = xml.replace(/<desc>Created with Raphaël 2.1.2<\/desc>/g,"");
			/* FOR UNEXPECTED SPANS */
			xml = xml.replace(/<span> undefined<\/span>/g,"");
			xml = xml.replace(/<span>undefined<\/span>/g,"");
