### ISSUE TITLE
Canvg does not support comma separated transform values.

### ISSUE THREAD

**Issue by gabelerner** [canvg/canvg#191]
_From [kris.rog...@gmail.com](https://code.google.com/u/113673856662327757093/) on December 10, 2012 21:31:23_

The problem can be reproduced by defining the transform attribute on an element using comma delimiting.

For example, the first svg definition below produces the expected transformation via canvg, whilst the second doesn't.

Space separated:

<svg><text x="50" y="50" transform="rotate(15) translate(500, 20)">Hello World!</text></svg>

Comma separated:

<svg><text x="50" y="50" transform="rotate(15),translate(500, 20)">Hello World!</text></svg>

According to http://www.w3.org/TR/SVG/coords.html#TransformAttribute "The individual transform definitions are separated by whitespace and/or a comma."

In the svg.Transform class, the regex for parsing transform attributes has no reference to commas:

var data = svg.trim(svg.compressSpaces(v)).split(/\s(?=[a-z])/);

Changing it to the following seems to work in all valid cases, although not thoroughly tested:

var data = svg.trim(svg.compressSpaces(v)).split(/[\s|\s?,\s?](?=[a-z])/);

_Original issue: http://code.google.com/p/canvg/issues/detail?id=191_

**Comment by jlahare** [comment]
is this fix available with "canvg-client" (used with npm)?

**Comment by gabelerner** [comment]
I don't know what `canvg-client` is ... You should be using `canvg`. That one matches this repo and hasn't had trouble parsing transforms for a while.
