### ISSUE TITLE
Trouble scaling redrawn image

### ISSUE THREAD

**Issue by gabelerner** [canvg/canvg#207]
_From [jackmfau...@gmail.com](https://code.google.com/u/102052409741581566026/) on February 17, 2013 11:26:55_

What steps will reproduce the problem? 1. Run canvg with custom scaling and a redraw on window.resize
2. Resize browser window
3. Observe canvg What is the expected output? What do you see instead? canvg should redraw the canvas at the updated dimensions after the window is resized. Instead, canvg scales the svg correctly the first time (onload) but onresize it's sized to the original dimensions of the svg when it's redrawn. What version of the product are you using? On what operating system? canvg 1.2, Google Chrome 24.0.1312.57 on Mac OS X 10.7 (Lion) Please provide any additional information below. Attached my code. Not a Javascript pro so hopefully this isn't a syntax error I overlooked...

**Attachment:** [header.js](http://code.google.com/p/canvg/issues/detail?id=207)

_Original issue: http://code.google.com/p/canvg/issues/detail?id=207_

**Comment by liz282907** [comment]
not working...
