### ISSUE TITLE
IE9 empty/duplicate attributes, multiple colons SYNTAX_ERR (12)

### ISSUE THREAD

**Issue by gabelerner** [canvg/canvg#216]
_From [hello.ti...@gmail.com](https://code.google.com/u/100525594363986493402/) on March 21, 2013 11:21:42_

What steps will reproduce the problem? 1. Try to parse a SVG with one or more of the following in IE9:
---- empty custom namespace attributes (e.g. xmlns:NS1="")
---- duplicate attributes
---- custom namespace attributes with multiple colons (e.g. NS1:xmlns:xlink) What is the expected output? What do you see instead? I see errors. SYNTAX_ERR (12), to be specific. What version of the product are you using? On what operating system? canvg 1.2, IE9 on Win7

I fixed this issue by replacing the whole <svg>-starting-tag with a valid one that will pass the IE9 parseFromString().

This regexp will does the trick for me, just put it right before your canvg call. 
svg = svg.replace( /^(<svg\s[a-zA-Z0-9.=\/:";\s]+>)/, '<svg  xmlns=" http://www.w3.org/2000/svg " version="1.1" xmlns:xlink=" http://www.w3.org/1999/xlink">'); canvg(canvas, svg);

Maybe it helps someone.

"Why you use invalid SVG XML anyway?", one might ask. I don't have a chance, that's what I get from Raphael.

_Original issue: http://code.google.com/p/canvg/issues/detail?id=216_

**Comment by vaishu26** [comment]
Still I have an issue in IE11 browser.

**Comment by vaishu26** [comment]
Can anyone help me please ?
