### ISSUE TITLE
preserveAspectRatio is not supported

### ISSUE THREAD

**Issue by gabelerner** [canvg/canvg#22]
_From [codedr...@gmail.com](https://code.google.com/u/108240851375674070640/) on April 04, 2010 18:16:09_

<svg xmlns=" http://www.w3.org/2000/svg " viewBox="0 0 200 200">
<circle fill="blue" cx="100" cy="100" r="40" />
</svg>

should render a blue circle.  canvg renders a blue ellipse.

_Original issue: http://code.google.com/p/canvg/issues/detail?id=22_

**Comment by pasestars** [comment]
I render a circle image using pattern, but it render not right.
`<svg width="500" height="500" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
 <defs>
  <pattern viewBox="0 0 1 1" patternContentUnits="objectBoundingBox" width="100%" height="100%" id="pattern">
   <image id="svg_4" xlink:href="https://i.ibb.co/31PYDX5/maou.jpg" preserveAspectRatio="xMidYMid slice" width="1" height="1"/>
  </pattern>
 </defs>
  <circle id="sd" r="100" cy="100" cx="100" fill="url(#pattern)" />
</svg>`
![example](https://user-images.githubusercontent.com/53326132/114966722-5e0e9480-9e9d-11eb-9051-72fbf77b1aa9.png)
