### ISSUE TITLE
writing-mode doesn't work.

### ISSUE THREAD

**Issue by gabelerner** [canvg/canvg#223]
_From [drma...@gmail.com](https://code.google.com/u/113696909369165807160/) on April 15, 2013 20:42:51_

Please check the following before submitting the issue: [X] When I drag the svg to my browser, it renders without errors
[X] My <svg> tag has: xmlns=" http://www.w3.org/2000/svg "
[ ] If I'm using Raphael/links/images, my <svg> tag has:
xmlns:xlink=" http://www.w3.org/1999/xlink " If any of these are false, then your svg xml is incorrect and needs to be fixed before sending it in canvg. -- What steps will reproduce the problem? 1. specify the writing-mode='tb' or 'tb-rl' to text element. What is the expected output? What do you see instead? I expect that the text is written vertically.
but text is in horizontal. What version of the product are you using? On what operating system? Please provide any additional information below.

_Original issue: http://code.google.com/p/canvg/issues/detail?id=223_

**Comment by grebbandev** [comment]
Ever found a solution to this?

**Comment by gabelerner** [comment]
moving to https://github.com/canvg/canvg/issues/668
