### ISSUE TITLE
Use of external resources in SVG image tag taints canvas 

### ISSUE THREAD

**Issue by gabelerner** [canvg/canvg#239]
_From [stanle...@gmail.com](https://code.google.com/u/103765249112972952959/) on July 17, 2013 12:01:42_

Please check the following before submitting the issue: [x] When I drag the svg to my browser, it renders without errors
[x] My <svg> tag has: xmlns=" http://www.w3.org/2000/svg "
[x] If I'm using Raphael/links/images, my <svg> tag has:
xmlns:xlink=" http://www.w3.org/1999/xlink " If any of these are false, then your svg xml is incorrect and needs to be fixed before sending it in canvg. -- What steps will reproduce the problem? 1. Run canvg on inline SVG element containing image tag linking to external image (example here: http://jsfiddle.net/Q2QEr/1/ ).
2. Attempt to call canvas.toDataURL() What is the expected output? What do you see instead? A data uri containing the canvas ideally should be generated. Instead, a DOM exception should is generated. What version of the product are you using? On what operating system? r182 using firefox and chrome Please provide any additional information below. I think this may be fixed by using CORS-enabled images during the drawing of images on to the canvas ( https://developer.mozilla.org/en-US/docs/HTML/CORS_Enabled_Image ).

I think this can be addressed by adding 
    this.img.crossOrigin = 'Anonymous';
after line 2219 ( https://code.google.com/p/canvg/source/browse/trunk/canvg.js?spec=svn182&r=182#2219 )
and 
    this.img.crossOrigin = 'Anonymous';
    this.img.onload = function() { self.loaded = true; }
    this.img.src = this.img.src;
in place of line 2227 ( https://code.google.com/p/canvg/source/browse/trunk/canvg.js?spec=svn182&r=182#2227 )

_Original issue: http://code.google.com/p/canvg/issues/detail?id=239_

**Comment by abishekrsrikaanth** [comment]
How do I use this with the `drawSVG` function?

**Comment by abishekrsrikaanth** [comment]
@gabelerner ^

**Comment by danilovaz** [comment]
I solve this with: canvg(canvas, svg, { useCORS: false })

**Comment by DharanBro** [comment]
@gabelerner  
canvg falis if image tag has some URL(random image got from internet). Have a look at this fiddle.
https://jsfiddle.net/dharanbro/vyxes9km/2/
