### ISSUE TITLE
Canvg rendering black rectangle instead of graph

### ISSUE THREAD

**Issue by gabelerner** [canvg/canvg#242]
_From [karl.m.p...@gmail.com](https://code.google.com/u/118120135107722332290/) on August 23, 2013 09:19:45_

Please check the following before submitting the issue: [X] When I drag the svg to my browser, it renders without errors
[X] My <svg> tag has: xmlns=" http://www.w3.org/2000/svg "
[X] If I'm using Raphael/links/images, my <svg> tag has:
xmlns:xlink=" http://www.w3.org/1999/xlink " If any of these are false, then your svg xml is incorrect and needs to be fixed before sending it in canvg. -- What steps will reproduce the problem? 1. paste my svg code in http://canvg.googlecode.com/svn/trunk/examples/index.htm 2. click render What is the expected output? What do you see instead? Expect to see the image to the right(svg output) as canvg output, i.e. a line path with x and y-axises. Instead, i get a black rectangle with only the axises rendering correctly. What version of the product are you using? On what operating system? I'm using the one from http://canvg.googlecode.com/svn/trunk/canvg.js .
My operating system is Windows 7 64-bit. Please provide any additional information below. Here's the code im using:

<svg width="880" height="400" title="test2" version="1.1" xmlns=" http://www.w3.org/2000/svg"><g transform="translate(50,20)"><path d="M0,0C5.079746051409108,9.406937132239086,90.00000000000003,250,135.00000000000003,250S225.00000000000006,250,270.00000000000006,250S360,250,405,250S495.0000000000001,250,540.0000000000001,250S630,250,675,250S787.5,250,810,250L810,250C787.5,250,720,250,675,250S585.0000000000001,250,540.0000000000001,250S450,250,405,250S315.00000000000006,250,270.00000000000006,250S180.00000000000003,250,135.00000000000003,250S5.079746051409108,9.406937132239086,0,0Z" class="line" style="stroke: #333333;"></path><g class="x brush" style="pointer-events: all;"><rect class="background" x="0" width="810" height="250" style="visibility: hidden; cursor: crosshair;"></rect><rect class="extent" x="226.5" width="0" height="250" style="cursor: move;"></rect><g class="resize e" transform="translate(226.5,0)" style="cursor: ew-resize; display: none;"><rect x="-3" width="6" height="250" style="visibility: hidden;"></rect></g><g class="resize w" transform="translate(226.5,0)" style="cursor: ew-resize; display: none;"><rect x="-3" width="6" height="250" style="visibility: hidden;"></rect></g></g><rect class="axisRect" x="-50" y="0" width="50" height="251" style="fill: #ffffff;"></rect><rect class="endRect" x="810" y="0" width="50" height="251" style="fill: #ffffff;"></rect><g class="x axis" transform="translate(0,250)"><g class="tick major" transform="translate(33.75000000000001,0)" style="opacity: 1;"><line y2="6" x2="0"></line><text y="9" x="0" dy=".71em" style="text-anchor: middle;">10:4:10</text></g><g class="tick major" transform="translate(146.25,0)" style="opacity: 1;"><line y2="6" x2="0"></line><text y="9" x="0" dy=".71em" style="text-anchor: middle;">10:5:0</text></g><g class="tick major" transform="translate(258.75,0)" style="opacity: 1;"><line y2="6" x2="0"></line><text y="9" x="0" dy=".71em" style="text-anchor: middle;">10:5:50</text></g><g class="tick major" transform="translate(371.25000000000006,0)" style="opacity: 1;"><line y2="6" x2="0"></line><text y="9" x="0" dy=".71em" style="text-anchor: middle;">10:6:40</text></g><g class="tick major" transform="translate(483.75,0)" style="opacity: 1;"><line y2="6" x2="0"></line><text y="9" x="0" dy=".71em" style="text-anchor: middle;">10:7:30</text></g><g class="tick major" transform="translate(596.25,0)" style="opacity: 1;"><line y2="6" x2="0"></line><text y="9" x="0" dy=".71em" style="text-anchor: middle;">10:8:20</text></g><g class="tick major" transform="translate(708.75,0)" style="opacity: 1;"><line y2="6" x2="0"></line><text y="9" x="0" dy=".71em" style="text-anchor: middle;">10:9:10</text></g><path class="domain" d="M0,6V0H810V6"></path></g><g class="y axis"><g class="tick major" transform="translate(0,250)" style="opacity: 1;"><line x2="-6" y2="0"></line><text x="-9" y="0" dy=".32em" style="text-anchor: end;">0</text></g><g class="tick major" transform="translate(0,227.97356828193833)" style="opacity: 1;"><line x2="-6" y2="0"></line><text x="-9" y="0" dy=".32em" style="text-anchor: end;">20</text></g><g class="tick major" transform="translate(0,205.94713656387665)" style="opacity: 1;"><line x2="-6" y2="0"></line><text x="-9" y="0" dy=".32em" style="text-anchor: end;">40</text></g><g class="tick major" transform="translate(0,183.92070484581498)" style="opacity: 1;"><line x2="-6" y2="0"></line><text x="-9" y="0" dy=".32em" style="text-anchor: end;">60</text></g><g class="tick major" transform="translate(0,161.8942731277533)" style="opacity: 1;"><line x2="-6" y2="0"></line><text x="-9" y="0" dy=".32em" style="text-anchor: end;">80</text></g><g class="tick major" transform="translate(0,139.8678414096916)" style="opacity: 1;"><line x2="-6" y2="0"></line><text x="-9" y="0" dy=".32em" style="text-anchor: end;">100</text></g><g class="tick major" transform="translate(0,117.84140969162996)" style="opacity: 1;"><line x2="-6" y2="0"></line><text x="-9" y="0" dy=".32em" style="text-anchor: end;">120</text></g><g class="tick major" transform="translate(0,95.81497797356829)" style="opacity: 1;"><line x2="-6" y2="0"></line><text x="-9" y="0" dy=".32em" style="text-anchor: end;">140</text></g><g class="tick major" transform="translate(0,73.78854625550659)" style="opacity: 1;"><line x2="-6" y2="0"></line><text x="-9" y="0" dy=".32em" style="text-anchor: end;">160</text></g><g class="tick major" transform="translate(0,51.762114537444916)" style="opacity: 1;"><line x2="-6" y2="0"></line><text x="-9" y="0" dy=".32em" style="text-anchor: end;">180</text></g><g class="tick major" transform="translate(0,29.735682819383243)" style="opacity: 1;"><line x2="-6" y2="0"></line><text x="-9" y="0" dy=".32em" style="text-anchor: end;">200</text></g><g class="tick major" transform="translate(0,7.70925110132157)" style="opacity: 1;"><line x2="-6" y2="0"></line><text x="-9" y="0" dy=".32em" style="text-anchor: end;">220</text></g><path class="domain" d="M-6,0H0V250H-6"></path></g></g><g transform="translate(50,320)"><path d="M0,0L135.00000000000003,60L270.00000000000006,60L405,60L540.0000000000001,60L675,60L810,60L810,60L675,60L540.0000000000001,60L405,60L270.00000000000006,60L135.00000000000003,60L0,0Z" class="line" style="stroke: #333333;"></path><g class="x axis" transform="translate(0,60)"><g class="tick major" transform="translate(33.75000000000001,0)" style="opacity: 1;"><line y2="6" x2="0"></line><text y="9" x="0" dy=".71em" style="text-anchor: middle;">10:4:10</text></g><g class="tick major" transform="translate(146.25,0)" style="opacity: 1;"><line y2="6" x2="0"></line><text y="9" x="0" dy=".71em" style="text-anchor: middle;">10:5:0</text></g><g class="tick major" transform="translate(258.75,0)" style="opacity: 1;"><line y2="6" x2="0"></line><text y="9" x="0" dy=".71em" style="text-anchor: middle;">10:5:50</text></g><g class="tick major" transform="translate(371.25000000000006,0)" style="opacity: 1;"><line y2="6" x2="0"></li...

_Original issue: http://code.google.com/p/canvg/issues/detail?id=242_

**Comment by mato75** [comment]
I still have this issue, I do not know what is the reason for it.
