### ISSUE TITLE
problem when converting svg with direction''RTL'' to canvas using canvg

### ISSUE THREAD

**Issue by gabelerner** [canvg/canvg#270]
_From [YuvalSom...@gmail.com](https://code.google.com/u/101680217637758619659/) on March 17, 2014 19:02:39_

i'm trying to convert hebrew/english text from svg to canvas unsing canvg
here is an example code that i tested and is showing the problem

<svg xmlns=" http://www.w3.org/2000/svg " width="640" height="480">
  <text xml:space="preserve" xmlns:xml=" http://www.w3.org/XML/1998/namespace "  direction="rtl" font-family="arial" font-size="24" id="svg_1" y="39" x="204" stroke-width="0" stroke="#000000" fill="#000000">מהנדס QA </text>
</svg>

_Original issue: http://code.google.com/p/canvg/issues/detail?id=270_

**Comment by gabelerner** [comment]
rtl supported now

**Comment by d4rksky** [comment]
hi , how can I use rtl mode with canvg ??
I tried test it in canvg examples but the result not supported rtl
this is my svg
```
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="400" height="400" direction="rtl" viewBox="0 0 360 360">
        <text style="font-size:12px" x="200" y="10">hello</text>
	<text style="font-size:12px" x="200" y="25">Whats up ? it is going well?</text>   
</svg>
``` 
result:
![image](https://user-images.githubusercontent.com/28533048/106377588-4ef66b00-63b3-11eb-971a-a50fe392181c.png)
how can I fixed it?
