### ISSUE TITLE
Letter-spacing not rendering correctly

### ISSUE THREAD

**Issue by gabelerner** [canvg/canvg#280]
_From [hypothet...@gmail.com](https://code.google.com/u/114110038850906562903/) on April 29, 2014 14:14:42_

What steps will reproduce the problem? 1. Create a text element with a letter-spacing attribute
2. Rasterize the canvas using Canvg What is the expected output? What do you see instead? Expected: Letters will reflect their spacing like the SVG
Result: Letter spacing remains at default What version of the product are you using? On what operating system? Latest (1.3?) Please provide any additional information below. Here is a JSBin demonstrating the issue. http://jsbin.com/fujev/2

_Original issue: http://code.google.com/p/canvg/issues/detail?id=280_

**Comment by dsbudiac** [comment]
FWIW, html2canvas handles this issue w/ a "letterRendering" option to render each character separately: http://html2canvas.hertzen.com/documentation.html

**Comment by gabelerner** [comment]
moving to https://github.com/canvg/canvg/issues/668

**Comment by mattnicholson** [comment]
Late to the party here, but my workaround was to use the built-in 'dx' property of a text span and apply letter spacing that way — and canvg honored it in the rendering — the `dx` property sets a value relative to the previous element, and can be negative too, to bring letters closer together:
```
<text x="0" y="0">
            <tspan  dx="80">S</tspan>
            <tspan  dx="80">p </tspan>
            <tspan  dx="80">a</tspan>
            <tspan  dx="80">c</tspan>
            <tspan  dx="80">e</tspan>
            <tspan  dx="80">d</tspan>
</text>
```
