### ISSUE TITLE
SVG to image conversion fails for large (2MB) svg (both Chrome and Firefox)

### ISSUE THREAD

**Issue by gabelerner** [canvg/canvg#285]
_From [chenopodiumcapitatum1](https://code.google.com/u/chenopodiumcapitatum1/) on May 22, 2014 08:19:18_

What steps will reproduce the problem? 1. Go to: http://canvg.googlecode.com/svn/trunk/examples/index.htm 2. Paste content of attached .svg file
3. SVG looks fine, but no image is generated
(see attached screen shot) What is the expected output? What do you see instead? - the canvas image :-). I see just the SVG image on the right side
- on Chrome, I see nothing in the console.
- on Firefox, I see this error: 
  [15:13:05.387] NS_ERROR_FAILURE: Failure @ http://canvg.googlecode.com/svn/trunk/canvg.js:971 - when doing it in my own code, chrome sometimes hangs What version of the product are you using? On what operating system? - Windows 7 (64 bit), both on Chrome and Firefox
- latest canvg (from test page above) Please provide any additional information below. - The svg size is 2'130'333 bytes. Is there a limit in Chrome/Firefox? Is there a client side workaround for such large svgs? 
  (besides splitting it up or sending it to a server or making them smaller :-)

Thanks,
Chantal

**Attachment:** [largesvg.png svg_toolarge.svg](http://code.google.com/p/canvg/issues/detail?id=285)

_Original issue: http://code.google.com/p/canvg/issues/detail?id=285_

**Comment by curiousityUnlimited** [comment]
I am encountering the same issue. In my case i am trying to get a printer friendly version of a D3 bar graph by converting SVG to canvas using this excellent plugin. It works great when there are 1000 bars in the graph .. but for huge data for around 10000 bars i.e 1000 SVG elements conversion is failing with NS_ERROR_FAILURE: at the same line as pointed above. 
![d3bargraph](https://cloud.githubusercontent.com/assets/14826585/10085760/ec1203fe-62d8-11e5-8bcd-8fe97814d108.png)

**Comment by gabelerner** [comment]
moved to https://github.com/canvg/canvg/issues/669
