### ISSUE TITLE
Bunch of problems brought about from resizing

### ISSUE THREAD

**Issue by gabelerner** [canvg/canvg#293]
_From [sammygil...@gmail.com](https://code.google.com/u/104898559003161520075/) on June 25, 2014 20:50:51_

Here's what I do:

First I run this line:

```
canvg('canvas', 'image.svg');
```

This creates a 278x322 image.

I then run this line:

```
canvg('canvas', 'image.svg', {scaleHeight:322, ignoreDimensions:true, ignoreMouse: true, ignoreClear: true});
```

So firstly, this creates an image that I expect to be the same size as the original, but it ends up being a different size (smaller). But it gets stranger!

If I have "ignoreMouse: false", the first time I mouse over the canvas it will redraw (and clear if ignoreClear:false) at approximately whatever random size scaleHeight:322 is (i.e. not the full canvas). So if I actually scaled to 100, then on mouseover the image redraws as scaleHeight:322 (not actually 322). Then on further mouseovers I can only assume it's redrawn every time, because the canvas just extends in size (the direction depends on if I scaled width or height).

Then if I have ignoreDimensions:false I then get redraws clearing the canvas. Not sure why, given that it then doesn't seem to actually change the canvas size.

So I'm just highly confused... if nothing made sense I can make a video showing the problem.

I'm using the CDN version atm (on that note, you should throw the version number in the source code itself)

Sammy

_Original issue: http://code.google.com/p/canvg/issues/detail?id=293_

**Comment by chemitaxis** [comment]
I have this issue too, any ideas how to fix it? Thanks.
