### ISSUE TITLE
All SVG elements not rendered

### ISSUE THREAD

**Issue by gabelerner** [canvg/canvg#298]
_From [nite...@gmail.com](https://code.google.com/u/104274638029616534864/) on August 12, 2014 04:43:23_

What steps will reproduce the problem? 1. Use a DOM containing svg element, multiple times 

<svg xmlns=" http://www.w3.org/2000/svg " version="1.1" width="217.00000000000003" height="49" id="ext-gen13319" style="width: 217.00000000000003px; height: 49px;"><defs></defs><rect width="100&#37;" height="100&#37;" fill="#000" stroke="none" opacity="0" id="ext-gen13320"></rect><rect id="ext-sprite-13325" zIndex="0" fill="rgba(255, 255, 255,0)" height="49" width="218" x="0" y="0" stroke-width="0" hidden="false" ry="0" rx="0" transform="matrix(1,0,0,1,0,0)" style="-webkit-tap-highlight-color: rgba(0, 0, 0, 0);"></rect></svg> 2. 3. What is the expected output? What do you see instead? Expected output: All the SVG elements are rendered
Actual output: All SVG elements are not getting rendered, some svg elements are not getting rendered, they are rendered getting subsequently 3rd or 4th time. What version of the product are you using? On what operating system? canvg v1.3, OS = Windows Please provide any additional information below. Attached the file to indicate the problem of missing svg.

**Attachment:** [missing svg.jpg](http://code.google.com/p/canvg/issues/detail?id=298)

_Original issue: http://code.google.com/p/canvg/issues/detail?id=298_

**Comment by abishekrsrikaanth** [comment]
I have the same issue as well. Take a look at this http://jsfiddle.net/technicaliti/L3hondLn/43/

**Comment by AalHappy** [comment]
Hi,Even I am facing the same issue..the code is like below:
<div id="canvasprint">
<svg>Hello</svg>
<svg>hello1</svg>
</div>
Does any one know how I can parse multiple svg using canvg..I can only parse single inline svg tag at one time..

**Comment by SDhalor** [comment]
same issue
