### ISSUE TITLE
Canvg 'parsererror' element on Firefox

### ISSUE THREAD

**Issue by gabelerner** [canvg/canvg#313]
_From [rafaelalbani@gmail.com](https://code.google.com/u/rafaelalbani@gmail.com/) on November 20, 2014 12:52:59_

Please check the following before submitting the issue: [ ] When I drag the svg to my browser, it renders without errors [ ] My <svg> tag has: xmlns=" http://www.w3.org/2000/svg "
[ ] If I'm using Raphael/links/images, my <svg> tag has:
xmlns:xlink=" http://www.w3.org/1999/xlink " If any of these are false, then your svg xml is incorrect and needs to be fixed before sending it in canvg. -- What steps will reproduce the problem? 1. Using SVG (GWT Google Chart) in canvg function.
2. Get the canvas element and use: canvas.toDataURL("image/jpeg") to get the image.  
3. The image will be broken What is the expected output? What do you see instead? expected output: A base64 image/jpeg.
output: A base64 image/jpeg broken. What version of the product are you using? On what operating system? Canvg 1.3 - Linux Ubuntu 13.10 - Firefox 30.0 Please provide any additional information below. The following exception is thrown on the console of the browser:
"ERROR: Element 'parsererror' not yet implemented."

I suspect that the svg is good, since the same code works in Chrome

_Original issue: http://code.google.com/p/canvg/issues/detail?id=313_

**Comment by cnd5041** [comment]
Sorry, I am having some trouble understanding the post, but am getting the same error in Firefox 35.0 (and the code works in chrome). Is there a fix for this?

I am trying to print an Esri ArcGIS map with layers on it. The map prints fine, but the printout is throwing the error when it gets to a certain graphic layer. Any help is appreciated. 

Here is the SVG string that I am passing in:
<svg id="map_gc" style="overflow: visible; position: absolute;" height="610" width="1920" overflow="hidden"><g style="display: block;" transform="matrix(1.00000000,0.00000000,0.00000000,1.00000000,6.00000000,4.00000000)" id="clusters_layer"><path fill-rule="evenodd" dojoGfxStrokeStyle="solid" stroke-dasharray="none" d="M 954 236 960 236 966 237 971 239 977 242 982 245 986 249 990 253 994 258 997 263 999 268 1000 274 1001 280 1001 286 1000 292 999 298 997 303 994 308 990 313 986 317 982 321 977 324 971 327 966 329 960 330 954 330 948 330 942 329 937 327 931 324 926 321 922 317 918 313 914 308 911 303 909 298 908 292 907 286 907 280 908 274 909 268 911 263 914 258 918 253 922 249 926 245 931 242 937 239 942 237 948 236 954 236" path="M 954,236 960,236 966,237 971,239 977,242 982,245 986,249 990,253 994,258 997,263 999,268 1000,274 1001,280 1001,286 1000,292 999,298 997,303 994,308 990,313 986,317 982,321 977,324 971,327 966,329 960,330 954,330 948,330 942,329 937,327 931,324 926,321 922,317 918,313 914,308 911,303 909,298 908,292 907,286 907,280 908,274 909,268 911,263 914,258 918,253 922,249 926,245 931,242 937,239 942,237 948,236 954,236" stroke-miterlimit="4" stroke-linejoin="miter" stroke-linecap="butt" stroke-width="2" stroke-opacity="1" stroke="rgb(255, 0, 0)" fill-opacity="0.25" fill="rgb(255, 0, 0)"></path><image transform="matrix(1.00000000,0.00000000,0.00000000,1.00000000,0.00000000,-15.00000000)" xlink:href="../dist/cars/images/BluePin.png" preserveAspectRatio="none" height="48" width="48" y="262" x="930" stroke-miterlimit="4" stroke-linejoin="miter" stroke-linecap="butt" stroke-width="1" stroke-opacity="0" stroke="none" fill-opacity="0"></image><text fill-rule="evenodd" font-family="serif" font-size="13.333333333333332" font-weight="normal" font-variant="normal" font-style="normal" transform="matrix(1.00000000,0.00000000,0.00000000,1.00000000,0.00000000,-10.00000000)" dominant-baseline="alphabetic" text-rendering="optimizeLegibility" kerning="auto" rotate="0" text-decoration="undefined" text-anchor="middle" y="286" x="954" stroke-miterlimit="4" stroke-linejoin="miter" stroke-linecap="butt" stroke-width="1" stroke-opacity="0" stroke="none" fill-opacity="1" fill="rgb(255, 255, 255)">32</text></g></svg>

**Comment by khuram832** [comment]
i am putting svg here ...  canvg parser is working fine on all browser but why not on firefox browser??? plz if you have any solution let me guide ???
"<svg version=\"1.1\" style=\"position: absolute; width: 883px; height: 450px; top: 0px; left: 0px;\"><desc>JavaScript chart by amCharts 3.21.12</desc><g><path cs=\"100,100\" d=\"M0.5,0.5 L882.5,0.5 L882.5,449.5 L0.5,449.5 Z\" fill=\"#FFFFFF\" stroke=\"#000000\" fill-opacity=\"0\" stroke-width=\"1\" stroke-opacity=\"0\" class=\"amcharts-bg\"></path><path cs=\"100,100\" d=\"M0.5,0.5 L753.5,0.5 L753.5,336.5 L0.5,336.5 L0.5,0.5 Z\" fill=\"#FFFFFF\" stroke=\"#000000\" fill-opacity=\"0\" stroke-width=\"1\" stroke-opacity=\"0\" class=\"amcharts-plot-area\" transform=\"translate(49,77)\"></path></g><g><g class=\"amcharts-value-axis value-axis-valueAxisAuto0_1522475756624\" transform=\"translate(49,0)\" visibility=\"hidden\"></g><g class=\"amcharts-category-axis\" transform=\"translate(49,77)\"><g><path cs=\"100,100\" d=\"M63.5,0.5 L63.5,5.5\" fill=\"none\" stroke-width=\"1\" stroke-opacity=\"1\" stroke=\"#000000\" transform=\"translate(0,336)\" class=\"amcharts-axis-tick\"></path><path cs=\"100,100\" d=\"M32.5,336.5 L32.5,336.5 L32.5,0.5\" fill=\"none\" stroke-w…"
