### ISSUE TITLE
Image fill pattern not rendered in canvg

### ISSUE THREAD

**Issue by gabelerner** [canvg/canvg#314]
_From [jpmorin...@gmail.com](https://code.google.com/u/108194127070474429684/) on November 22, 2014 14:55:47_

Please check the following before submitting the issue: [ ] When I drag the svg to my browser, it renders without errors [ ] My <svg> tag has: xmlns=" http://www.w3.org/2000/svg "
[x] If I'm using Raphael/links/images, my <svg> tag has:
xmlns:xlink=" http://www.w3.org/1999/xlink " If any of these are false, then your svg xml is incorrect and needs to be fixed before sending it in canvg. -- What steps will reproduce the problem? 1. Using RaphaelJS, set the attribute 'fill' of a shape with an image url [fill: url(/img/path.png)]
2. Apply the RaphaelJS fix to the 'svg' so it works with canvg
3. Rendering with canvg creates the shape with empty fill What is the expected output? What do you see instead? Blank background on the shape. What version of the product are you using? On what operating system? canvg-1.3 on Ubuntu (Linux) Please provide any additional information below. (This is the SVG before applying the RaphaelJS xmlns fix for canvg)

<svg height="600" version="1.1" width="800" xmlns=" http://www.w3.org/2000/svg " style="overflow: hidden; position: relative; background-color: rgb(255, 255, 255);" viewBox="0 0 800 600" preserveAspectRatio="xMidYMin meet">
  <desc style="-webkit-tap-highlight-color: rgba(0, 0, 0, 0);">
    Created with Raphaël 2.1.2
  </desc>
  <defs style="-webkit-tap-highlight-color: rgba(0, 0, 0, 0);">
    <pattern id="A5902D33-0DD4-48AC-9E28-DAC0B51A87D0" x="0" y="0" patternUnits="userSpaceOnUse" height="20" width="20" patternTransform="matrix(1,0,0,1,0,0) translate(225.5,56)" style="-webkit-tap-highlight-color: rgba(0, 0, 0, 0);">
      <image x="0" y="0" xmlns:xlink=" http://www.w3.org/1999/xlink " xlink:href="/img/patterns/pattern-diagonal.png" width="20" height="20" style="-webkit-tap-highlight-color: rgba(0, 0, 0, 0);">
      </image>
    </pattern>
  </defs>
  <rect x="225.5" y="56" width="195" height="141" r="0" rx="0" ry="0" fill="url(#A5902D33-0DD4-48AC-9E28-DAC0B51A87D0)" stroke="#000000" stroke-width="3" stroke-opacity="1" fill-opacity="0.75" font-size="72px" transform="matrix(1,0,0,1,0,0)" style="-webkit-tap-highlight-color: rgba(0, 0, 0, 0); stroke-opacity: 1; fill-opacity: 0.75; font-size: 72px; cursor: pointer;">
    <title style="-webkit-tap-highlight-color: rgba(0, 0, 0, 0);">
    </title>
  </rect>
</svg>

**Attachment:** [svg-canvas-pattern.png](http://code.google.com/p/canvg/issues/detail?id=314)

_Original issue: http://code.google.com/p/canvg/issues/detail?id=314_

**Comment by mitar** [comment]
I think I have a similar problem. The following SVG is not rendered with background:

```svg
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<svg xmlns="http://www.w3.org/2000/svg" pointer-events="none" width="50" height="50" style="width: 50px; height: 50px; background-color: #8BC34A;">
  <text text-anchor="middle" y="50%" x="50%" dy="0.36em" pointer-events="auto" fill="#ffffff" font-family="Helvetica, Arial, Lucida Grande, sans-serif" style="font-weight: 400; font-size: 28px;">
    US
  </text>
</svg>
```

**Comment by xinhaiz** [comment]
This bug has been fixed? I have a similar problem.

**Comment by gabelerner** [comment]
`background-color` is not a valid svg property. it's an `html` one. if you want a similar effect, you can paint the canvas your desired color then tell canvg to not clear it
