### ISSUE TITLE
Black color fill in

### ISSUE THREAD

**Issue by gabelerner** [canvg/canvg#315]
_From [PhamNhat...@gmail.com](https://code.google.com/u/100964806536682960215/) on December 05, 2014 15:27:40_

My code below. 

<svg xmlns=" http://www.w3.org/2000/svg " xlink=" http://www.w3.org/1999/xlink " version="1.1" id="v_5" width="800" height="600"><defs id="v_7"></defs><g id="v_6" class="viewport"><g id="j_1" model-id="190928d6-e7e7-41ef-9a2b-a08ae224d6c5" class="link"><path class="connection" stroke="white" id="v_12" stroke-width="2" stroke-dasharray="5 4" d="M 140 20 C 114.9765981783141 37.590288169498066 89.95319635662821 55.18057633899613 102 73 C 114.04680364337179 90.81942366100387 163.16381275180123 108.86798281351358 228 132 C 292.83618724819877 155.13201718648642 373.391552636167 183.34749240694953 343 202 C 312.608447363833 220.65250759305047 171.2699767035309 229.74204755868826 29.931506043228765 238.83158752432604"></path><path class="marker-source" fill="black" stroke="black" id="v_13" transform="translate(140,20) scale(1,1) rotate(-234.36018371582028)"></path><path class="marker-target" fill="black" stroke="white" id="v_14" d="M 10 0 L 0 5 L 10 10 z" transform="translate(19.41579428421641,235.0342399741181) scale(1,1) rotate(-6.709836959838867)"></path><path class="connection-wrap" id="v_15" d="M 140 20 C 114.9765981783141 37.590288169498066 89.95319635662821 55.18057633899613 102 73 C 114.04680364337179 90.81942366100387 163.16381275180123 108.86798281351358 228 132 C 292.83618724819877 155.13201718648642 373.391552636167 183.34749240694953 343 202 C 312.608447363833 220.65250759305047 171.2699767035309 229.74204755868826 29.931506043228765 238.83158752432604"></path><g class="labels" id="v_16"></g><g class="marker-vertices" id="v_17"><g class="marker-vertex-group" transform="translate(102, 73)" id="v_44"><circle class="marker-vertex" idx="0" r="10"></circle><path class="marker-vertex-remove-area" idx="0" d="M16,5.333c-7.732,0-14,4.701-14,10.5c0,1.982,0.741,3.833,2.016,5.414L2,25.667l5.613-1.441c2.339,1.317,5.237,2.107,8.387,2.107c7.732,0,14-4.701,14-10.5C30,10.034,23.732,5.333,16,5.333z" transform="translate(5, -33)"></path><path class="marker-vertex-remove" idx="0" transform="scale(.8) translate(9.5, -37)" d="M24.778,21.419 19.276,15.917 24.777,10.415 21.949,7.585 16.447,13.087 10.945,7.585 8.117,10.415 13.618,15.917 8.116,21.419 10.946,24.248 16.447,18.746 21.948,24.248z"><title>Remove vertex.</title></path></g><g class="marker-vertex-group" transform="translate(228, 132)" id="v_45"><circle class="marker-vertex" idx="1" r="10"></circle><path class="marker-vertex-remove-area" idx="1" d="M16,5.333c-7.732,0-14,4.701-14,10.5c0,1.982,0.741,3.833,2.016,5.414L2,25.667l5.613-1.441c2.339,1.317,5.237,2.107,8.387,2.107c7.732,0,14-4.701,14-10.5C30,10.034,23.732,5.333,16,5.333z" transform="translate(5, -33)"></path><path class="marker-vertex-remove" idx="1" transform="scale(.8) translate(9.5, -37)" d="M24.778,21.419 19.276,15.917 24.777,10.415 21.949,7.585 16.447,13.087 10.945,7.585 8.117,10.415 13.618,15.917 8.116,21.419 10.946,24.248 16.447,18.746 21.948,24.248z"><title>Remove vertex.</title></path></g><g class="marker-vertex-group" transform="translate(343, 202)" id="v_46"><circle class="marker-vertex" idx="2" r="10"></circle><path class="marker-vertex-remove-area" idx="2" d="M16,5.333c-7.732,0-14,4.701-14,10.5c0,1.982,0.741,3.833,2.016,5.414L2,25.667l5.613-1.441c2.339,1.317,5.237,2.107,8.387,2.107c7.732,0,14-4.701,14-10.5C30,10.034,23.732,5.333,16,5.333z" transform="translate(5, -33)"></path><path class="marker-vertex-remove" idx="2" transform="scale(.8) translate(9.5, -37)" d="M24.778,21.419 19.276,15.917 24.777,10.415 21.949,7.585 16.447,13.087 10.945,7.585 8.117,10.415 13.618,15.917 8.116,21.419 10.946,24.248 16.447,18.746 21.948,24.248z"><title>Remove vertex.</title></path></g></g><g class="marker-arrowheads" id="v_18"><g class="marker-arrowhead-group marker-arrowhead-group-source" id="v_21" transform="translate(150.56505487271554,27.574944058267945) scale(1,1) rotate(-234.36018371582028)"><path class="marker-arrowhead" end="source" d="M 26 0 L 0 13 L 26 26 z"></path></g><g class="marker-arrowhead-group marker-arrowhead-group-target" id="v_22" transform="translate(18.481063231614037,227.0890422432539) scale(1,1) rotate(-6.709836959838867)"><path class="marker-arrowhead" end="target" d="M 26 0 L 0 13 L 26 26 z"></path></g></g><g class="link-tools" id="v_19"><g class="link-tool" id="v_20" transform="translate(108.6460952758789, 44.742088317871094) "><g class="tool-remove" event="remove"><circle r="11"></circle><path transform="scale(.8) translate(-16, -16)" d="M24.778,21.419 19.276,15.917 24.777,10.415 21.949,7.585 16.447,13.087 10.945,7.585 8.117,10.415 13.618,15.917 8.116,21.419 10.946,24.248 16.447,18.746 21.948,24.248z"></path><title>Remove link.</title></g><g class="tool-options" event="link:options"><circle r="11" transform="translate(25)"></circle><path fill="white" transform="scale(.55) translate(29, -16)" d="M31.229,17.736c0.064-0.571,0.104-1.148,0.104-1.736s-0.04-1.166-0.104-1.737l-4.377-1.557c-0.218-0.716-0.504-1.401-0.851-2.05l1.993-4.192c-0.725-0.91-1.549-1.734-2.458-2.459l-4.193,1.994c-0.647-0.347-1.334-0.632-2.049-0.849l-1.558-4.378C17.165,0.708,16.588,0.667,16,0.667s-1.166,0.041-1.737,0.105L12.707,5.15c-0.716,0.217-1.401,0.502-2.05,0.849L6.464,4.005C5.554,4.73,4.73,5.554,4.005,6.464l1.994,4.192c-0.347,0.648-0.632,1.334-0.849,2.05l-4.378,1.557C0.708,14.834,0.667,15.412,0.667,16s0.041,1.165,0.105,1.736l4.378,1.558c0.217,0.715,0.502,1.401,0.849,2.049l-1.994,4.193c0.725,0.909,1.549,1.733,2.459,2.458l4.192-1.993c0.648,0.347,1.334,0.633,2.05,0.851l1.557,4.377c0.571,0.064,1.148,0.104,1.737,0.104c0.588,0,1.165-0.04,1.736-0.104l1.558-4.377c0.715-0.218,1.399-0.504,2.049-0.851l4.193,1.993c0.909-0.725,1.733-1.549,2.458-2.458l-1.993-4.193c0.347-0.647,0.633-1.334,0.851-2.049L31.229,17.736zM16,20.871c-2.69,0-4.872-2.182-4.872-4.871c0-2.69,2.182-4.872,4.872-4.872c2.689,0,4.871,2.182,4.871,4.872C20.871,18.689,18.689,20.871,16,20.871z"></path><title>Link options.</title></g></g></g></g></g></svg>

_Original issue: http://code.google.com/p/canvg/issues/detail?id=315_

**Comment by thelordgabo** [comment]
I also have the same problem, image attached. 
![wrong-image](https://cloud.githubusercontent.com/assets/3825673/12098963/d580320a-b2fb-11e5-96eb-8551b93b14de.PNG)

**Comment by mlh758** [comment]
I'm having this problem as well. I think it might be related to using opacity.

**Comment by rafaelmagalhaes** [comment]
has any one found a fix for this im having the same issue

**Comment by proshuai** [comment]
@mlh758 do you have resolve the question? how to do?

**Comment by proshuai** [comment]
@thelordgabo how to resolve it?

**Comment by mlh758** [comment]
@proshuai I stopped using opacity, I set an explicit background when it started and put it back to whatever I had before when it was done.

**Comment by gabelerner** [comment]
can someone resubmit an svg if this is still relevant?

**Comment by Seankps** [comment]
I found the cause to be <font> tags in my svg. By adding styles to those tags (background-color: transparent; fill: none;) I was able to fix my black background without making the text invisible
