### ISSUE TITLE
Mutation observers for dynamic inline SVG manipulation

### ISSUE THREAD

**Issue by pcwalton** [canvg/canvg#319]
Hi,

I was wondering whether you'd be interested in using mutation observers to enable dynamic inline SVG manipulation.

This seemed to me at a quick glance to be the main feature needed to use canvg as our SVG implementation in Servo (http://github.com/servo/servo). I'm the main layout developer on that project and was interested in experimenting with using canvg to get SVG support without having to implement it natively. To do that we'll need to not only run canvg to convert `<svg>` elements on a page as it loads but also to keep it updated.

What do you think?

**Comment by gabelerner** [comment]
is this still something you require? i'm going through all the issues and can take another look. if so, please reopen.
