### ISSUE TITLE
External Css not parsed

### ISSUE THREAD

**Issue by kpatel1989** [canvg/canvg#323]
I am trying to add external css to my svg but its not being parsed and rendered on the canvas.

my svg file : 
<?xml-stylesheet type="text/css" href="style.css" ?>
<svg xmlns="http://www.w3.org/2000/svg"
    xmlns:xlink="http://www.w3.org/1999/xlink">
    <defs>
        <style>
            @font-face {
                font-family: versa;
                src: url("VeraSeBd.ttf") format("svg"); 
            }

```
    </style>
</defs>

<circle cx="40" cy="40" r="24"/>
<text x="20" y="140" font-family="versa" font-size ="20">Example SVG text 1</text>
```

</svg>

and Css file

circle {
     stroke: #006600;
     fill  : #00cc00;
  }

text {
    stroke : #00cc00;
}

**Comment by jpatel3** [comment]
I don't think it will consider that css, you will need to inline all your style before you render.

**Comment by thelordgabo** [comment]
I have the same problem but with a class:

<svg width="800" height="567" style="overflow: hidden;" class="c3" ...

The css rule "c3" is not applied.

**Comment by gabelerner** [comment]
it handles inline css that's part of the svg itself but doesn't care about the rest of the dom or any other external stylesheets.  unfortunately, that's on you to bring into the svg like jpatel3 said. moving to https://github.com/canvg/canvg/issues/671
