### ISSUE TITLE
Support rendering with WebGL

### ISSUE THREAD

**Issue by AshleyScirra** [canvg/canvg#325]
Modern HTML5 game engines use WebGL over canvas2d since it is considerably faster (even just for 2D) and supports shaders for visual effects. It's also great if games can use SVG graphics. However rendering via canvas2d is more complicated and slower than having direct WebGL rendering. This feature would fill a very useful hole for web gaming.

**Comment by gabelerner** [comment]
moving to https://github.com/canvg/canvg/issues/671
