### ISSUE TITLE
text element not render in my project

### ISSUE THREAD

**Issue by beyondalbert** [canvg/canvg#332]
Hi, it's weird that canvg can not render text element in my project. 
I test the demo in README in jsfiddle, it can render ok. 
Event I put the same svg string in my project and jsfiddle, in jsfiddle the text can be rednered, but not in my project. 
I also compared canvg lib in my project and demo jsfidle, their identical files!

what's going on with my project? This problem confused me too many days.
I use rails to development a website, here is the js and css lib I used:
1. jquery 
2. jquery UI
3. bootstrap

**Comment by gabelerner** [comment]
please upload a zip if it's not working and make sure you follow the README/jsfiddle.
