### ISSUE TITLE
issue94.svg rendering solution

### ISSUE THREAD

**Issue by jajce** [canvg/canvg#333]
After some research I figured out that
<path d="A 0 0 * * * x y"> is the same as
<path d="L x y">

So adding this lines to Arc handling case will solve the issue.

``` javascript
if (rx == 0 && ry == 0) {
  ctx.lineTo(cp.x, cp.y);
  continue;
}
```

So now issue94.svg is not an issue anymore :)

**Comment by gabelerner** [comment]
issue94 seems like it's working in master
