### ISSUE TITLE
text with gradiant does not render

### ISSUE THREAD

**Issue by Toushin** [canvg/canvg#342]
Hello,
I was trying to render an SVG text element with a linearGradiant.

I expected to see my text rendered, but instead got this error:
TypeError: element.getBoundingBox is not a function      canvg.js (Zeile 1716, Spalte 57)
The rendering then stopped completely.

I'm using the latest version of canvg at the time of writing this post and running windows 7.

It seems the combination of text and a gradiant does not work, despite plain text with a color or a rect with a gradiant working without issue.

**Comment by Toushin** [comment]
I made a fiddle to show this issue: https://jsfiddle.net/1c5x0n0v/23/

**Comment by NateAGeek** [comment]
Still having this issue, I know this is from 2015.

The error appears to be happening on a tspan, getBoundingBox, is not available in the svg.Element.tspan.
