### ISSUE TITLE
baseline-shift attribute not working

### ISSUE THREAD

**Issue by rfinquiron** [canvg/canvg#343]
This is my svg

```
<svg>
    <g >
        <g >
            <circle cx="22" cy="22" r="8" fill="#cc0000" fill-opacity="0.8" stroke="none" />
        </g>
        <g>
            <text x="22" y="22" fill="#f3f3f3" font-size="11px" text-anchor="middle">
                <tspan baseline-shift="-35%" x="22" dy="0em">1</tspan>
            </text>
        </g>
    </g>
</svg>
```

If you have a look at the output, the text is shifted up on canvg output while its good on svgoutput.
Any help would be appreciated.

![image](https://cloud.githubusercontent.com/assets/4939880/6429682/ecbd5bb6-bffc-11e4-9d21-6ddc47f2ba09.png)

Thanks

**Comment by gabelerner** [comment]
moving to https://github.com/canvg/canvg/issues/668
