### ISSUE TITLE
SyntaxError in IE11 with SVG from RaphaelJS

### ISSUE THREAD

**Issue by maciejjankowski** [canvg/canvg#346]
In IE 11 I get the following:

```
SCRIPT5022: SyntaxError
File: canvg.bundle.js, Line: 1035, Column: 5
->    return parser.parseFromString(xml, 'text/xml');
Non-default namespace declarations must not have an empty URI. Line: 1, Column 187
```

I am using RaphaelJS which generates the following SVG:

```
<svg style="overflow: hidden; position: relative;" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns="http://www.w3.org/2000/svg" width="770" version="1.1" height="553"><desc>Created with Raphaël 2.1.2</desc><defs></defs><image xlink:href="ron2.jpg" preserveAspectRatio="none" height="553" width="770" y="0" x="0"></image><text stroke-width="2" fill="#000000" stroke="#ffffff" font-size="105px" font-family="Impact" text-anchor="left" y="109" x="431" style="text-anchor: middle; font-family: Impact; font-size: 105px;"><tspan dy="41.5">SO is awesome!!</tspan></text><text stroke-width="2" fill="#000000" stroke="#ffffff" font-size="105px" font-family="Impact" text-anchor="left" y="108" x="427" style="text-anchor: middle; font-family: Impact; font-size: 105px;"><tspan dy="41.5">SO is awesome!!</tspan></text></svg>
```

and I am calling canvg like this:

```
 canvg('canvas', $('#container').html());
```

which works fine in latest Chrome and FF

**Comment by maciejjankowski** [comment]
it appears that there is a problem with SVG tag - this part exactly:
````
<svg xmlns="http://www.w3.org/2000/svg" style="top: -0.45px; overflow: hidden; position: relative;" width="770" height="553" version="1.1" 
xmlns="http://www.w3.org/2000/svg" 
xmlns:NS1="" NS1:xmlns:xlink="http://www.w3.org/1999/xlink">
<image preserveAspectRatio="none meet" x="0" y="0" width="770" height="553" 
xmlns:NS2="http://www.w3.org/1999/xlink" 
NS2:href="ron2.jpg" />
````
those namespaces look somewhat weird - I have no idea why `NS1=""` and then the weird `NS1:xmlns:xlink` follows - looks unnatural, but I have no idea what it means and what to do about it.

the SVG comes from this: `new XMLSerializer().serializeToString( document.querySelector( "svg" ) )`

**Comment by beyondalbert** [comment]
hi，I came up with the same problem, any idea how to fix this problem?
I generate my svg with Snap.svg library.

**Comment by Gnafu** [comment]
This is a DOMParser related issue.
canvg.js [line 204](https://github.com/gabelerner/canvg/blob/master/canvg.js#L204) does a check for InternetExplorer using window.DOMParser, if window.DOMParser does not exists the parsing is done with ActiveXObject.
The problem is that IE11 defines window.DOMParser and such parser will fail.

My solution was to try {} catch{} the DOMParser block and to retry with ActiveXObject if an exception is thrown.

```
			else if (window.DOMParser)
			{
                try {
                    var parser = new DOMParser();
                    return parser.parseFromString(xml, 'text/xml');
                } catch (e) {
                    xml = xml.replace(/<!DOCTYPE svg[^>]*>/, '');
                    var xmlDoc = new ActiveXObject('Microsoft.XMLDOM');
                    xmlDoc.async = 'false';
                    xmlDoc.loadXML(xml);
                    return xmlDoc;
                }
			}
			else
			{
				xml = xml.replace(/<!DOCTYPE svg[^>]*>/, '');
				var xmlDoc = new ActiveXObject('Microsoft.XMLDOM');
				xmlDoc.async = 'false';
				xmlDoc.loadXML(xml);
				return xmlDoc;
			}
```
This is an UGLY hack, and react to real syntax exceptions by retrying with the ActiveX, so you must be 100% sure the SVG is valid.

**Comment by akoskm** [comment]
@Gnafu I ran into the same problem. Why the `DOMParser` fails in IE11, is this a bug with their implementation or our XMLs are really invalid?

**Comment by akoskm** [comment]
In my case `DOMParser` was somewhat right. It tries to parse a SVG similar to this:

```
<svg
  xmlns:xlink="http://www.w3.org/1999/xlink"
  height="10000"
  version="1.1"
  width="10000"
  xmlns="http://www.w3.org/2000/svg"
  style="overflow: hidden; position: absolute; left: -0.203125px; background-image: url(&quot;data:image/gif;base64,R0lGODlhDwAPAPAAAP////Hx8SH5BAEAAAAALAAAAAAPAA8AAAKpYRiGYRiGYRiGYRiGIAiCIAiCIAiCIBiCIAiCIAiCIAiCYAiCIAiCIAiCIAiCIQiCIAiCIAiCIAiGIAiCIAiCIAiCIBiCIAiCIAiCIAiCYAiCIAiCIAiCIAiCIQiCIAiCIAiCIAiGIAiCIAiCIAiCIBiCIAiCIAiCIAiCYAiCIAiCIAiCIAiCIQiCIAiCIAiCIAiGIAiCIAiCIAiCIBiCIAiCIAiCIAiCIAA7&quot;);">
  ...
</svg>
```
And it reports that an attribute with the same name already exists on this element (`xmlns`). I used the following RegExp to remove every attribute contained in the `svg` tag:

```
(?![<svg])[^>]*
```

Finally my parseXML method looks like:

```
svg.parseXml = function(xml) {
    if (window.DOMParser)
    {
        xml = xml.replace(/(?![<svg])[^>]*/, '');
        var parser = new DOMParser();
        return parser.parseFromString(xml, 'text/xml');
    }
    else
    {
        xml = xml.replace(/<!DOCTYPE svg[^>]*>/, '');
        var xmlDoc = new ActiveXObject('Microsoft.XMLDOM');
        xmlDoc.async = 'false';
        xmlDoc.loadXML(xml);
        return xmlDoc;
    }
}
```

Tested on Firefox 44.0, Chromium 48.0.2564.82 and IE 11.0.9600.18163

**Comment by ddausch** [comment]
Akoskum, i am seeing something similar with IE 11. Stepping thru canvg I did notice the parseXml throwing an exception. I see above that you wrote your own version. How did u integrate that with canvg?

**Comment by akoskm** [comment]
@ddausch this is not my own version, I've just added this line:

```
xml = xml.replace(/(?![<svg])[^>]*/, '');
```

in the version that I'm currently using.

**Comment by ddausch** [comment]
@akoskm - Thanks, I get what you mean. I ended up replacing the following text: xmlns=\"http://www.w3.org/2000/svg\"  with a space. 
I went to this url: https://validator.w3.org/check and the new version of my content passed their test. I am still getting a DOM syntax error. Any other suggestions here? Not sure what to do next.

**Comment by akoskm** [comment]
I would suggest placing a `console.log(xml)` before the actual parsing happens:
```
    var parser = new DOMParser();
    console.log(xml);
    return parser.parseFromString(xml, 'text/xml');
```
and validate the XML that is printed to the console. There must be a syntax error somewhere. During my experiments I realized the Firefox and Chromium implementations are perfectly fine with parsing invalid XMLs and the syntax error you're getting in IE11 happens for a reason.

**Comment by MarkMaldaba** [comment]
FYI - I've been ecountering similar issues.  The <svg> element that exists in the DOM is not really designed for generating a valid SVG document, but rather a standardised SVG rendering within the browser.  It will therefore not necessarily validate as SVG 1.1 when rendered as a string (depending on what element types and properties you are using) and if the XML is not valid then the DOMParser object will throw syntax errors in IE.

The solution I found was to use the [Raphael.Export plugin](https://github.com/AliasIO/Raphael.Export), which provides a `toSVG()` function on the Raphael object.  This generates SVG markup that should parse and render correctly outside of the browser context, including when rendering other formats via CanVG.

As well as fixing the DOMParser issue, it resolved a bunch of other rendering issues I was experiencing with gradient fills, so is well worth a look.

**Comment by jl2922** [comment]
```
  svgString = svgString.replace('xmlns:NS1="" ', '');
  svgString = svgString.replace('NS1:xmlns', 'xmlns');
```

no time to dig through why there is an NS1 in IE but it works for me after removing it.

**Comment by gabelerner** [comment]
if this is still an issue, please provide a new example for me to look at. thanks!
