### ISSUE TITLE
canvg throws the "An invalid or illegal string was specified" error during svg chart convertion to canvas

### ISSUE THREAD

**Issue by podlesky** [canvg/canvg#356]
I have a task to convert to svg charts to images. One chart is converted successfully, but during second one convertion to canvas, canvg throws the following exception:

[Exception... "An invalid or illegal string was specified" code: "12" nsresult: "0x8053000c (NS_ERROR_DOM_SYNTAX_ERR)"
location: "http://localhost/shared/js/highcharts/exporting/canvg.js Line: 1574"]

User-Agent:
Mozilla/5.0 (Windows NT 6.1; WOW64; rv:2.0.1) Gecko/ /2.0.1Mozilla/5.0 (Windows NT 6.1; WOW64; rv:2.0.1) Gecko/
/2.0.1

My code is:

```
    var chart_svg = chartData.chart.getSVG();
    //also tried to set width and height and use DOM canvas but without success
    var chart_canvas = document.createElement('canvas');

    canvg(chart_canvas, chart_svg, {
        renderCallback: function () {
            $(chartData.container).empty();
            var imgData = chart_canvas.toDataURL('image/png');
            var img = new Image();
            $(img).load(function () {
                $(img).appendTo(chartData.container);
            });
            img.src = imgData;
        }
    });
```

I surround lines 1574-1580 with try and empty catch and seems that it works fine:
        try {
        ctx.translate(centp.x, centp.y);
        ctx.rotate(xAxisRotation);
        ctx.scale(sx, sy);
        ctx.arc(0, 0, r, a1, a1 + ad, 1 - sweepFlag);
        ctx.scale(1 / sx, 1 / sy);
        ctx.rotate(-xAxisRotation);
        ctx.translate(-centp.x, -centp.y);
        }
        catch (e) {  }

However is there any other pretty fix for this error?

Thanks.

**Comment by gabelerner** [comment]
i need the svg string in `chart_svg` to fully debug this
