### ISSUE TITLE
Support marker elements

### ISSUE THREAD

**Issue by gabelerner** [canvg/canvg#36]
_From [adeve...@gmail.com](https://code.google.com/u/110004786915373318047/) on April 14, 2010 14:04:08_

http://dev.w3.org/SVG/profiles/1.1F2/publish/painting.html#Markers Test file:

<svg width="300" height="300" xmlns=" http://www.w3.org/2000/svg ">
 <defs>
  <marker viewBox="0 0 10 10" id="se_arrow_fw" refY="5" 
markerUnits="strokeWidth" markerWidth="5" markerHeight="5" orient="auto" 
refX="8">
   <path d="m0,0l10,5l-10,5l5,-5l-5,-5z" fill="#000000"/>
  </marker>
 </defs>
  <line fill="none" stroke="#000000" stroke-width="9" x1="44" y1="131" 
x2="258.99999" y2="133" id="svg_3" marker-end="url(#se_arrow_fw)"/>
</svg>

_Original issue: http://code.google.com/p/canvg/issues/detail?id=36_

**Comment by rakeshgithubaccount** [comment]
I am using canvg javasript library to convert svg to canvas but its giving an error while converting "Cannot read property 'x' of undefined at t.Element.marker.render" what can i do for this ? From the above conversation i came to know that while converting marker gives the problem and i have marker element in my svg.

Is it like you have fixed this problem in specific version of yours ?
