### ISSUE TITLE
Misalignment of text within <tspan> element

### ISSUE THREAD

**Issue by maxharlow** [canvg/canvg#362]
I have the following SVG:

``` html
<svg>
<text dy="1em"><tspan>One</tspan><tspan x="0" dy="1.1em">Two</tspan><tspan x="0" dy="1.1em">Three</tspan></text>
</svg>
```

In SVG this renders each word on a separate line, in CanVG there is a lot of extra space between each element:

![screen shot 2015-05-16 at 17 05 36](https://cloud.githubusercontent.com/assets/896707/7666882/e087e474-fbed-11e4-8c2d-0c19166ea95a.png)

**Comment by gabelerner** [comment]
latest version this works!
