### ISSUE TITLE
canvg ignores text-decoration attribute

### ISSUE THREAD

**Issue by Toushin** [canvg/canvg#365]
see this fiddle: https://jsfiddle.net/1c5x0n0v/27/

It seems that the text-decoration attribute is ignored by canvg, so underlined <tspan>-elements are not rendered correctly.

**Comment by gabelerner** [comment]
not natively supported by canvas's text function, have to do it myself at some point ... related to https://github.com/gabelerner/canvg/issues/276

**Comment by gabelerner** [comment]
moving to https://github.com/canvg/canvg/issues/668
