### ISSUE TITLE
svg path tag is not reflecting on the canvas but is reflecting as svg

### ISSUE THREAD

**Issue by basnetujwal** [canvg/canvg#368]
Hi team,

I was using canvg from the very beginning from its release there was no issue before, converting svg to canvas but now there is problem converting this svg section:

![svgerrorelement](https://cloud.githubusercontent.com/assets/5961912/8123575/ed3cd9be-10eb-11e5-8b54-ff839c305dde.PNG)

I look forward to get solution from you guys.

Cheers,
Ujwal Basnet

**Comment by gabelerner** [comment]
can you please include that as text as opposed to an image so i can debug easier?
