### ISSUE TITLE
"rgb-color" dependency needed?

### ISSUE THREAD

**Issue by rbatllet** [canvg/canvg#380]
The "rbg-color" dependency is added but a file named "rgbcolor.js" is present in the project.

is it a deprecated dependency and can be excluded avoiding rgbcolor.js to be overwritten?

{
  "name": "canvg",
  "version": "1.0.0",
  "main": "canvg.js",
  "keywords": ["javascript", "client", "browser", "svg", "canvas"],
  "ignore" : ["examples", "svgs"],
  "dependencies": {
    "rgb-color": "ariutta/rgb-color"
  }
}

**Comment by gabelerner** [comment]
i only have rgbcolor.js in the repo for people that don't want to use bower. i guess it would make sense to rename it to rgb-color.js to match ariutta's repo, right?

**Comment by gabelerner** [comment]
we've updated build to be cleaner
