### ISSUE TITLE
It doesn't work in safari.

### ISSUE THREAD

**Issue by puppeteer701** [canvg/canvg#383]

**Comment by eXponenta** [comment]
It's can't draw SVG in Safari. I need it.

**Comment by gabelerner** [comment]
works in my safari, please provide more details and reopen

<img width="1132" alt="screen shot 2018-08-31 at 11 08 45 pm" src="https://user-images.githubusercontent.com/241819/44941786-dec30580-ad72-11e8-8d69-e3e696e11416.png">
