### ISSUE TITLE
Consider removing examples/svgs from release, or restructuring to make them easy to exclude.

### ISSUE THREAD

**Issue by MarkMaldaba** [canvg/canvg#395]
Old releases of canvg didn't include the 'examples' and 'svgs' folders - just the three .js files in the root directory, and the license.

Neither of these folders is required on a production server and take up about 5.5 MB (which is massive, when compared to the actual .js payload of ~128k).

It would be much easier for consumers of canvg - particularly for those like myself who manage third-party libraries via the version-controlled 'vendor drop' process - if these folders (and, less importantly, the .json build files) were omitted from the releases, or at the very least that the directory structure was modified so that the payload is in a separate sub-directory (e.g. a 'canvg' folder containing just the .js files and license).

It looks like the build files are set up this way already, so perhaps it is just a matter of creating the releases using the build files, rather than just zipping up the whole tag?

**Comment by gabelerner** [comment]
:+1: will tackle at some point

**Comment by gabelerner** [comment]
everything is distributed properly now for browser/node.
