### ISSUE TITLE
canvg not working on Firefox

### ISSUE THREAD

**Issue by huynhtrong** [canvg/canvg#400]
// Canvg requires trimmed content
 var content = $('#market-chart').html().trim(),
canvas = document.getElementById('market-trend-canvas');

// Draw svg on canvas
  canvg(canvas, content);

this code not working on Firefox

**Comment by dgambin** [comment]
I am also having the same issue. Any hint?

**Comment by jpatel3** [comment]
What error are you getting? It works fine for me.

**Comment by daneshka** [comment]
I had the same issue.
The workaround for me was clean-up the SVG file before calling canvg.
In my case it was removing all of attributes with custom namespaces and also removing height="Infinity" from the svg element.

**Comment by priyaD15** [comment]
How to clean the svg, can you please elaborate

**Comment by daneshka** [comment]
@priyaD15 
Here is my code:
        //Canvg doesn't support these stuff
        clonedSvg.find("text").each(function (index, item) {
            item.removeAttribute("oryx:fontSize");
        });
        clonedSvg.find("circle").each(function (index, item) {
            if (!item.hasAttribute("stroke-width")) {
                item.setAttribute("stroke-width", 2);
            }
        });
        clonedSvg.removeAttr("style");
        //to make items in groups visible - canvg doesn't fully support url
        clonedSvg.find("[fill*=url]").each(function (index, item) {
            var fill = jQuery(item).attr("fill");
            var startIndex = fill.indexOf("url(");
            var endIndex = fill.indexOf(")");
            var url = fill.substring(startIndex, endIndex + 1);
            fill = fill.replace(url, "");
            //canvg doesn't like space
            jQuery(item).attr("fill", fill.trim());
        });
        var svgStr = jQuery("<div>").append(clonedSvg.clone()).html();
        var canvas = jQuery("<canvas width='" + $svg.attr("width") + "' height='" + $svg.attr("height") + "'/>");
        jQuery(this.html).find("body").append(canvas);

        //Canvg doesn't support these stuff
        svgStr = svgStr.replace(/&nbsp;/g, ' ').split("stroke-dasharray=\"0\"").join("");
        svgStr = svgStr.replace(/xmlns=\"http:\/\/www.w3.org\/2000\/svg\"/, '');
        svgStr = svgStr.replace(/xmlns:NS1=\"\"/, '');
        svgStr = svgStr.replace(/NS1:xmlns:xlink=\"http:\/\/www.w3.org\/1999\/xlink\"/, '');
        svgStr = svgStr.replace(/xmlns:NS2=\"\"/, '');
        svgStr = svgStr.replace(/NS2:xmlns:svg=\"http:\/\/www.w3.org\/2000\/svg\"/, '');
        svgStr = svgStr.split("oryx:").join("");
        svgStr = svgStr.replace("height=\"Infinity\"", "");

        canvas = canvas.get(0);
        var ctx = canvas.getContext('2d');
        ctx.clearRect(0, 0, canvas.width, canvas.height);
        window.canvg(canvas, svgStr);

**Comment by priyaD15** [comment]
@daneshka  thank you so much for this help.
I will check out how it will be useful in my case, thanks again

**Comment by gabelerner** [comment]
can you all revisit this and let me know which functions don't work at this point in time?

**Comment by may16197** [comment]
I get this error on FF:

Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help http://xhr.spec.whatwg.org/ ---canvg.js:216:6
GET 
XHR 
https://localhost/data/d3/[object%20SVGSVGElement] [HTTP/1.1 404 Not Found 10ms

**Comment by ed1987** [comment]
@daneshka that worked, thank you!

**Comment by khuram832** [comment]
Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help http://xhr.spec.whatwg.org/ ---canvg.js:216:6
GET
XHR
https://localhost/data/d3/[object%20SVGSVGElement] [HTTP/1.1 404 Not Found 
please guide me if you have solution of this , why this happened on firefox only ?

**Comment by Redboat** [comment]
Hi,
I'm getting the same error in Chrome. I'm using the spinning football SVG (1.svg) example file, so there shouldn't be any issues with the file.

```
[Deprecation] Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.
svg.ajax @ canvg.js:277
svg.load @ canvg.js:2963
canvg @ canvg.js:117
(anonymous) @ canvg-test:26

Uncaught DOMException: Failed to execute 'send' on 'XMLHttpRequest': Failed to load '.../1.svg'.
    at Object.svg.ajax (https://.../js/canvg.js:278:12)
    at Object.svg.load (https://.../js/canvg.js:2963:25)
    at canvg (https://.../js/canvg.js:117:8)
    at https://.../canvg-test:26:9
svg.ajax @ canvg.js:278
svg.load @ canvg.js:2963
canvg @ canvg.js:117
(anonymous) @ canvg-test:26
```

In firefox is also tells me:

`Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://.../1.svg. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).
`
Anyone know how to get this working?
Thanks.

**Comment by gabelerner** [comment]
i'll actively try to merge https://github.com/canvg/canvg/pull/504 which will fix this
