### ISSUE TITLE
Styling of SVG tag 

### ISSUE THREAD

**Issue by kairusann** [canvg/canvg#417]
_border_, _padding_ and _margin_ are not working as tested on [example page](http://gabelerner.github.io/canvg/examples/index.htm) using the following code:

```
<svg style="border:2px solid #ddd; margin-left: 20px; padding-top:55px;font-family:cursive;"><text x="50" y="50">Hello World!</text></svg>
```

It is very easy to reproduce this issue so no screenshot is provided.

**Comment by gabelerner** [comment]
we will not be supporting html styles here. you can implement this within the svg. moving to https://github.com/canvg/canvg/issues/671
