### ISSUE TITLE
Convert NVD3 chart to Image

### ISSUE THREAD

**Issue by Amarnath510** [canvg/canvg#419]
Hi,

I have requirement where we need to convert the nvd3 graph to image. But when I googled the results are always about svg to image or canvas to image. As nvd3 is dependent on d3 which in turn uses svg but I am not able to figure out how to convert nvd3 to image. I have attacked small piece of code and also   created 
[nvdtochart.txt](https://github.com/gabelerner/canvg/files/64016/nvdtochart.txt)

plunker also for the same http://plnkr.co/edit/YgkXQ1jCQiyKPr1qAJhV?p=info

**Comment by amenadiel** [comment]
canvg doesn't interact with whatever library you used to render the SVG, just with the result of it.

Anyway, the following should work:

```js
var container = jQuery('#canvas'),
   thesvg = container.find('svg'),
   svgData = new XMLSerializer().serializeToString(thesvg[0]),
   targetCanvas = document.createElement('canvas'),
   targetImg = new Image();

targetCanvas.setAttribute('id','targetCanvas');

container[0].appendChild(targetCanvas);
container[0].appendChild(targetImg);

canvg('targetCanvas',svgData,{
    ignoreMouse: true,
   ignoreAnimation: true
});

targetImg.src = targetCanvas.toDataURL();
```

**Comment by Amarnath510** [comment]
Thanks for the quick response. 
After including the above code I am seeing an image but it is not rendered properly.

So when I dig down into each line above I am seeing some strange values.
Value of `targetImg.src` after `targetImg.src = targetCanvas.toDataURL();` is `data:,`
When I inspected the image link in the browser, it is 

`
<canvas id="targetCanvas" width="0" height="500" style="width: 0px; height: 500px;"></canvas>
<img src="data:,">`

So I aasume the image did not rendered properly or there is an issue in the code.
Please refer [plunker](http://plnkr.co/edit/YgkXQ1jCQiyKPr1qAJhV?p=preview) to view the issue.

**Comment by amenadiel** [comment]
This means that, for some reason, canvg can't fill the canvas with meaningful data from the svgData you're feeding it. I can't see nothing wrong with the svg itself, but perhaps it's an issue of `g` elements being nested inside  `g` elements at various depths.

**Comment by Amarnath510** [comment]
So is there any other way to render the char to image? 
Or should change my approach like instad of using nvd3 chart use some other chart API?
I really need this task to be done.

**Comment by gabelerner** [comment]
can you attach the svg string to this issue so i can debug? thanks!

**Comment by Amarnath510** [comment]
@gabelerner I am using nvd3 for which the code is at http://plnkr.co/edit/YgkXQ1jCQiyKPr1qAJhV?p=info 
The solution stated above by @amenadiel  is using svg but in my case it is nvd3. I am not sure whether nvd3 is internally using svg or not.
Can you help merender the graph into image using nvd3 instead of svg?

**Comment by gabelerner** [comment]
it seems to work with that example http://jsfiddle.net/L3hondLn/408/

**Comment by ace-of-fox** [comment]
I'm having a similar issue.  My pie charts work fine, but when I draw the bar charts, it appears the ticks are missing.  I believe the lines are getting drawn but it might be missing the style? so you can't see them.  I've been searching on this issue, but haven't found anything close to it except for this thread.   http://plnkr.co/edit/pnBbNXkjw8CQwszOhGRc?p=preview

**Comment by Oshinodono** [comment]
Hi, personally I catch the svg chart with javascript getElementById() and send it to a python function through an Ajax request to convert the nvd3 chart in png with ImageMagick. It works well for pie charts, but line charts are render almost entirely black, here an overview:

svg data : http://pastebin.com/Rpjum2HT
original svg image: https://drive.google.com/open?id=0B6WmPFbvhbGoZkZoR2pTSjJIVE0
result after converting to png with ImageMagick: https://drive.google.com/open?id=0B6WmPFbvhbGoTXI5UnNyaUtraGc

**Comment by christian-s1** [comment]
Did any of you find a solution for this. I personally use c3.js, but i got the same problem as you did with nvd3. My canvas just stays empty when I feed the svg element to canvg.

**Comment by Oshinodono** [comment]
Hi finally I've converted chart client side with this javascript solution (https://github.com/exupero/saveSvgAsPng) and only after send them server side, not very nice but it works.

**Comment by amenadiel** [comment]
If anyone is still interested in this issue, I created a new Plunkr showing how capture the nvd3 graph
http://plnkr.co/edit/BeadSfS13MBzY1c60tmt?p=preview



I updated the links and upgraded jquery to v3.x but it's basically the same. However, instead of creating an image, I just create and append the canvas element. 

```js
$scope.generate = function() {
  var container = jQuery('#canvas'),
      thesvg = container.find('svg');
  thesvg.find('text').css('font','400 11px Arial');
 
  var content = container.html().trim(),
  canvas = document.createElement("canvas");
  container[0].appendChild(canvas);
  canvg(canvas, content);

  thesvg.find('text').css('font','');
};
```

Once you have that canvas, you can use `canvas.toDataURL()` to get what you want.

See, if the SVG is valid, you don't really need to use `XMLSerializer`. Just get the SVG contents using `jQuery('#canvas').html().trim()`.

Please note I'm altering the font size of the `text` elements prior to the canvas generation and resetting said property after generation. Otherwise, you'd get a canvas with larger texts.
