### ISSUE TITLE
overflow="hidden" ignored when loading from xml

### ISSUE THREAD

**Issue by remig** [canvg/canvg#426]
When SVG is loaded from a URL, and that SVG includes an 'overflow="hidden"' attribute, canvg does the right thing and clips the overall SVG element.  But if that same SVG is loaded from an XML string, 'overflow="hidden"' is ignored.

It looks like svg.loadXmlDoc() is explicitly ignoring overflow via 'e.root'.  I'm not sure what the purpose of that is, but it seems unnecessary.  e.root is only ever used to check if 'overflow' should be applied, but shouldn't overflow be applied regardless of how the SVG was loaded?

Attached is a trivial repro.
[overflow_hidded_ignored.html.txt](https://github.com/gabelerner/canvg/files/101162/overflow_hidded_ignored.html.txt)

**Comment by gabelerner** [comment]
```xml
<svg id="svg" width="300" height="300" overflow="hidden">
	<rect x="0" y="0" width="300" height="300" fill="none" stroke="black" stroke-width="1"></rect>
	<rect x="-100" y="-100" width="300" height="300" fill="grey" stroke="black" stroke-width="5"></rect>
</svg>
```
seems to be working on http://canvg.github.io/canvg/examples/index.htm, please reopen if i'm mistaken
