### ISSUE TITLE
xml:space="preserve" is not honored

### ISSUE THREAD

**Issue by xr250** [canvg/canvg#439]
This attribute indicates that multiple contiguous space characters are preserverd.
See "10.15 White space handling" in the SVG spec. https://www.w3.org/TR/SVG/text.html#SpacingProperties
canvg does not appear to implement this attribute. See http://jsfiddle.net/htshp8j0/3/

**Comment by gabelerner** [comment]
moving to https://github.com/canvg/canvg/issues/668
