### ISSUE TITLE
Cannot read property 'width' of undefined with 100% width SVG element

### ISSUE THREAD

**Issue by xmakina** [canvg/canvg#443]
Element: `<svg width="100%" height="24px"><g><path class="line" d="M0,19.621505047735003L11.076923076923077,17.75003046411946L22.153846153846153,17.646184088193557L33.23076923076923,18.45441338897004L44.30769230769231,24L55.38461538461539,3.071155916932292L66.46153846153847,7.317499492122048L77.53846153846153,5.541097261316634L88.61538461538461,7.81419240933304L99.6923076923077,13.024563319698544L110.76923076923077,5.331545041905942L121.84615384615384,0L132.92307692307693,3.1390952287648117"></path></g></svg>`

Error: TypeError: Cannot read property 'width' of undefined
Error line: this.width=function(){return this.Current().width}

Let me know if you need anything else.

**Comment by xmakina** [comment]
No error is thrown, but the system breaks if you alter this fiddle (http://jsfiddle.net/bv16o50f/1/) to use 100% rather than 900 as the width.

**Comment by gabelerner** [comment]
seems to work for me, what browser are you in?

![capture](https://cloud.githubusercontent.com/assets/241819/13731499/6f751dea-e938-11e5-9358-aa8ac56ef9f3.PNG)

**Comment by OleksiiZubko** [comment]
I have the same issue, but with height 100% . Chrome Version 50.0.2661.102 windows. I'm using canvg v 1.3
As I see, this.viewPorts are empty in my case. Please, let me known what additional info should I provide. Thank you.

**Comment by ltodd** [comment]
I was getting this error and it was driving me crazy.  My issue was that the target I was passing into canvg had no parent.  The ViewPort code didn't like that.

**Comment by OleksiiZubko** [comment]
I got the problem. 

Created a pull request https://github.com/gabelerner/canvg/pull/463 .
In our case (with height or width in '%'), the first time  rendering, svg doesn't have initialized any ViewPort if we have no parent node. And in this case the function svg.Property.prototype.toPixels trying  to get the pixels from percents: if (s.match(/%$/)) return this.numValue() * svg.ViewPort.ComputeSize(viewPort);  And svg.ViewPort.ComputeSize produce exeptions, because we do not have any ViewPorts yet

**Comment by kikifang** [comment]
@OleksiiZubko 
Hi guy, was you change integrated into canvg? I run into this problem, working with latest canvg library, yet.

**Comment by OleksiiZubko** [comment]
@kikifang Hi, no. Still in status Open https://github.com/canvg/canvg/pull/463/

**Comment by gabelerner** [comment]
should be fixed by https://github.com/canvg/canvg/pull/623, let me know if not
