### ISSUE TITLE
Adding the <canvas> to the DOM

### ISSUE THREAD

**Issue by holmberd** [canvg/canvg#451]
Hi, any specific reason I have to add the canvas element to the DOM to be able to convert it to PNG? I'm getting an error on the following [line](https://github.com/gabelerner/canvg/blob/master/canvg.js#L65).

More of a inquiry than an issue, since I can live without it, but it would come in handy if possible i.e.
Thanks

**Comment by gabelerner** [comment]
that just caches the class as a property on the canvas element... maybe it's conflicting w/ a native property. what's the full source code of what you're trying to do so i can replicate?
