### ISSUE TITLE
Canvg not working in Firefox

### ISSUE THREAD

**Issue by archerne** [canvg/canvg#456]
#400 might be a duplicate of this but that issue is over 6 months old.

I can see the butterfly in this example: http://gabelerner.github.io/canvg/examples/convert.htm in Chrome and Internet Explorer. However I cannot see it in Firefox.

**Comment by kamerontanseli** [comment]
Add `xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"` to your SVG element.

**Comment by kamerontanseli** [comment]
`<svg xmlns="http://www.w3.org/2000/svg"
xmlns:xlink="http://www.w3.org/1999/xlink">`

**Comment by gabelerner** [comment]
i'll actively try to merge https://github.com/canvg/canvg/pull/504 which will fix this
