### ISSUE TITLE
canvg can't suppot <image>in svg 

### ISSUE THREAD

**Issue by HelenGiser** [canvg/canvg#458]
canvg can't suppot <image>in svg

**Comment by wanyanyan** [comment]
convert image.src to DataURL will work.

**Comment by machadogj** [comment]
Looks like converting png/jpg to data url may result in loss of quality (?). I get the following error message when using an <image> with source to a png:

```
ReferenceError: document is not defined
```

Is there anything we can do?

**Comment by gabelerner** [comment]
closing as we support images: http://canvg.github.io/canvg/demo/index.html?svg=../svgs/32.svg ... please provide more details and reopen.

**Comment by machadogj** [comment]
Hi @gabelerner, thanks for the update. I have tested my svg with the link you provided and it works. So this seems to be a bug in `svg2img`.
