### ISSUE TITLE
axis Lines Are Drawn too thick

### ISSUE THREAD

**Issue by tirupathiraop** [canvg/canvg#461]
lines are drawn thick while converting svg through canvg.
![issue](https://cloud.githubusercontent.com/assets/18027791/15348752/df9dac3c-1cea-11e6-9426-6d1c3bc67902.png)

**Comment by dennieru** [comment]
+1

**Comment by rajarshig** [comment]
@tirupathiraop this issue occurs when the style of the svg element comes from external css class. 
    For solution, embed the css style of the line as inline css. 
For eg. to inline css style for a line chart with class `.linechart`
`$(".linechart").find('svg path').css({"fill":"none"});`

**Comment by gabelerner** [comment]
please attach svg if this is still an issue
