### ISSUE TITLE
"mix-blend-mode: multiply" not support

### ISSUE THREAD

**Issue by dotorimook** [canvg/canvg#464]
Hi, I am new to canvg.

I'd like to take a capture of svg element which has "mix-blend-mode:multipy" in its style.

When I tried to canvg for the element,  the result of the canvg does not affect "mix-blend-mode' property.

Is there any way to capture multiplied elements?

thanks.

**Comment by sameerjain** [comment]
@dotorimook did you find a solution?

**Comment by cailven** [comment]
@gabelerner  when will you fix the bug?

**Comment by gabelerner** [comment]
This is an open source project and there's no expectation of timing. Anybody can fix the bug by opening up a proper pull request.

**Comment by NateAGeek** [comment]
The current support for this can be seen at: https://developer.mozilla.org/en-US/docs/Web/CSS/mix-blend-mode

Currently Firefox seems to be the only one supporting this. However, the way I went around doing this, for cross-browser support, was manipulating the canvas after the initial run of canvg, and appending an image to the canvas with the canvas's blend mode.

```javascript
var canvas              = document.createElement('canvas');
var canvasContext = canvas.getContext("2d");
var overlay_img      = new Image();
var svgString          = ''; //SVG String: <svg>...</svg>

canvasContext.globalCompositeOperation = "multiply"; //This does the blending: https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/globalCompositeOperation
overlay_img.src = ''; //URL or Data

canvg(canvas, svgString);
canvasContext.drawImage(overlay_img, 0, 0, 512, 512);
```

**Comment by gabelerner** [comment]
this is an html style and won't be supported but you can use `feBlend` with `multiply` in svg world when it gets implemented in canvg. can follow this thread: https://github.com/canvg/canvg/issues/667
