### ISSUE TITLE
Text on a path - 

### ISSUE THREAD

**Issue by gabelerner** [canvg/canvg#47]
_From [anthony....@elateral.com](https://code.google.com/u/117183483168478895325/) on May 14, 2010 02:04:24_

What steps will reproduce the problem? 1. Pasted the below SVG into the test page

<svg width="12cm" height="3.6cm" viewBox="0 0 1000 300" version="1.1"
     xmlns=" http://www.w3.org/2000/svg "
xmlns:xlink=" http://www.w3.org/1999/xlink ">
  <defs>
    <path id="MyPath"
          d="M 100 200 
             C 200 100 300   0 400 100
             C 500 200 600 300 700 200
             C 800 100 900 100 900 100" />
  </defs>
  <desc>Example toap01 - simple text on a path</desc>
  <use xlink:href="#MyPath" fill="none" stroke="red"  />
  <text font-family="Verdana" font-size="42.5" fill="blue" >
    <textPath xlink:href="#MyPath">
      We go up, then we go down, then up again
    </textPath>
  </text>
  
  <rect x="1" y="1" width="998" height="298"
        fill="none" stroke="blue" stroke-width="2" />
</svg>

What is the expected output? 

Expected to see text rendered on a path

What do you see instead?

Path but no text What version of the product are you using? On what operating system? Using the test page ( http://canvg.googlecode.com/svn/trunk/examples/index.htm )
Firefox 3.5.9 Please provide any additional information below. I'm interested in using your library to convert SVG text on a path to
visualize on the canvas

_Original issue: http://code.google.com/p/canvg/issues/detail?id=47_

**Comment by therealfly** [comment]
Any progress on this issue? Would be nice to have cause:
"<svg width="261.2744509139151" height="145.14440786838531" viewBox="0 0 64.1090087890625 36.57181930541992" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" preserveAspectRatio="none"><g id="0.4622385623550621"><text fill="#FF0000" stroke="none" stroke-width="0" stroke-linecap="round" stroke-linejoin="round" x="" y="" text-anchor="start" font-size="24px" font-family="Arizonia"><textPath xlink:href="#textPath-item-0">Hello</textPath></text></g><defs><path id="textPath-item-0" d="M 7.3499755859375 29.68229652290156 A 58.12216094836716 58.12216094836716 0 0 1 58.3081322835276 29.682296522901567"/></defs></svg>"

Wil not render without it :(

With kind regards,

Johan van Rijen

**Comment by davidemond** [comment]
Any progress on this issue?

Line 2087 : this.x = child.x + child.measureText(ctx);
child type is textPath
and error is : TypeError: child.measureText is not a function(…)

the solution that I have found is adding this code at line 2230
		// textPath
		svg.Element.textPath = function(node) {
			this.captureTextNodes = true;
			this.base = svg.Element.TextElementBase;
			this.base(node);
			
			this.text = node.nodeValue || node.text || '';
			this.getText = function() {
				return this.text;
			}
		}
		svg.Element.textPath.prototype = new svg.Element.TextElementBase;

**Comment by gabelerner** [comment]
this is pretty hard to do natively w/ canvas, for now still choosing not to work on it until html5 canvas supports it as doing all the calculations myself letter by letter is not trivial.  feel free to open a PR if you have ideas.

**Comment by MarkMaldaba** [comment]
I take your point, but it would be good if it didn't throw a fatal error in the meantime.

Could you maybe just detect this situation and skip it, so you get a rendered image missing the unsupported elements, rather than a fatal JavaScript error that kills the script and produces no image at all?

**Comment by khaledosman** [comment]
thanks @davidemond , drawing them in a straight line is much better than not drawing them at all..

**Comment by gabelerner** [comment]
closing due to PR above that I will push through

**Comment by gabelerner** [comment]
closed by https://github.com/canvg/canvg/pull/687
