### ISSUE TITLE
SVG to Canvas conversion not working properly

### ISSUE THREAD

**Issue by sudeep350** [canvg/canvg#473]
Hi, 
I am facing formatting issue while converting SVG to canvas.  I have attached two SVG below. 
[svg.zip](https://github.com/gabelerner/canvg/files/377619/svg.zip)

so when I convert these svg into canvas , we are not getting desired output.  Please see canvas output file
[CanvasOutput.pdf](https://github.com/gabelerner/canvg/files/377622/CanvasOutput.pdf)

Here one SVG got reversed and other one got rotated.  Can you please take a look and let me the know the issue.

**Comment by alafr** [comment]
It's an issue with stroke-dasharray & stroke-dashoffset. This simpler test should be easier to debug. I will try to look at Canvg's source code if I find time
```
<svg width="200" height="200" xmlns="http://www.w3.org/2000/svg">
  <circle cx="120" cy="75" r="60" stroke-width="20" stroke="red" stroke-dasharray="140 1000" fill="none"/>
  <circle cx="120" cy="75" r="30" stroke-width="20" stroke="orange" stroke-dasharray="140 1000" fill="none"/>
  <line x1="20" y1="0" x2="20" y2="200" stroke="green" stroke-width="20" stroke-dasharray="100 100" stroke-dashoffset="50%"/>
  <line x1="40" y1="0" x2="40" y2="200" stroke="blue" stroke-width="20" stroke-dasharray="100 100" stroke-dashoffset="100"/>
</svg>
```
![image](https://cloud.githubusercontent.com/assets/17966696/19355202/3803dc74-9172-11e6-9fce-3b51ce6bda5c.png)

**Comment by alafr** [comment]
Pull request #489 fixes both the simplified test and @sudeep350's svg files.

**Comment by fors21** [comment]
OWNER
