### ISSUE TITLE
404 error on content delivery

### ISSUE THREAD

**Issue by maccyd10** [canvg/canvg#482]
I'm getting a 404 error for the js files listed in the docs

&lt;script type="text/javascript" src="http://canvg.github.io/canvg/rgbcolor.js"&gt; &lt;/script&gt;
&lt;script type="text/javascript" src="http://canvg.github.io/canvg/StackBlur.js"&gt; &lt;/script&gt;
&lt;script type="text/javascript" src="http://canvg.github.io/canvg/canvg.js"&gt; &lt;/script&gt;

**Comment by gabelerner** [comment]
if you click your links they work

**Comment by maccyd10** [comment]
I just realised it looks like the links were updated at some point?
the ones i have in my site are as follows

  http://gabelerner.github.io/canvg/rgbcolor.js
  http://gabelerner.github.io/canvg/StackBlur.js
  http://gabelerner.github.io/canvg/canvg.js

Sorry for this I should have looked more closely

**Comment by smugamerican** [comment]
I submitted a pull request to fix the jsfiddle in the readme. Someone else has fixed the links (change gabelerner to canvg and they’ll work).

**Comment by gabelerner** [comment]
merged https://github.com/canvg/canvg/pull/481, closing this
