### ISSUE TITLE
Convert SVG object from makerJS to Canvas

### ISSUE THREAD

**Issue by davejack1** [canvg/canvg#483]
If I am not mistaken canvg only accepts URL or text for SVG. How can I convert an SVG object I created with a library, in this case [makerJS](https://github.com/Microsoft/maker.js)

**Comment by gabelerner** [comment]
use outerHTML or jquery html() to grab the text and feed it into canvg or call canvg with no options to convert all svgs (http://canvg.github.io/canvg/examples/convert.htm)
