### ISSUE TITLE
Updated release?

### ISSUE THREAD

**Issue by rcwwilliams** [canvg/canvg#492]
Hi

Thanks for this great component.

Please could you consider an updated release as 1.4 is over a year old and it would be great to have the fix for MS Edge included in the latest release.

Thanks very much.

Robin

**Comment by magnusekstrand** [comment]
I would like to see a new release as well. 

Thanks!
/magnus

**Comment by csvan** [comment]
+1

**Comment by gabelerner** [comment]
been on a good release schedule lately!
