### ISSUE TITLE
One SVG isn't shown in Canvas out put

### ISSUE THREAD

**Issue by rajeshtailored** [canvg/canvg#494]
Canvas doesn't show one SVG. This is the code i used
 `<svg width="851" height="355" xmlns="http://www.w3.org/2000/svg"><g><title></title><text class="titleClass" xml:space="preserve" text-anchor="middle" font-family="Arial" font-size="66.644578313253" id="svg_1" y="260.4921620805369" x="425.5" stroke-width="0" stroke="#000000" fill="#000000">Your Title</text><text class="textClass" xml:space="preserve" text-anchor="middle" font-family="Arial" font-size="164.04819277108433" id="svg_2" y="177.5" x="425.5" stroke-width="0" stroke="#000000" fill="#000000">Your Text</text></g></svg>` 
at http://canvg.github.io/canvg/examples/index.htm by width 851 and height 355. But the "Your Text" svg is missing from the canvas out put. Please see this http://www.awesomescreenshot.com/image/1754142/2f5cca4399fde1216bff10169662fe6a

This problem occurs only in **Chrome Version 54.0.2840.71 m, Operating system is Windows 8.1 pro**

Can any one help me to sort out this?

**Comment by alafr** [comment]
It's strange because it works fine in my Chrome which is exactly the same version but on Windows 10

**Comment by rajeshtailored** [comment]
Thank you. Yes on Window 10, It works fine for me as well.

**Comment by gabelerner** [comment]
if it's working on a future windows, i'm going to chalk it up to a windows issue w/ canvas
