### ISSUE TITLE
"text-anchor = middle" does not render

### ISSUE THREAD

**Issue by sebjwallace** [canvg/canvg#502]
When a svg element has a textAlign attribute it does not render it to canvas.

**Comment by alafr** [comment]
Use **`text-anchor="middle"`** instead, `textAlign` is not a valid svg attribute

**Comment by sebjwallace** [comment]
Sorry, that's what I meant.

**Comment by alafr** [comment]
Then it's probably a bug, do you have some svg code to reproduce it?

**Comment by gabelerner** [comment]
it should be fixed by https://github.com/canvg/canvg/pull/658, if you have svg code that doesn't work please reopen
