### ISSUE TITLE
Calling to canvg parameterless does not work on fire fox

### ISSUE THREAD

**Issue by Luis-Palacios** [canvg/canvg#503]
Hi and thank you for this great library, it has proven really helpful for me in a recent project.

I've encounter this issue on my project, but if you try the demo link on the documentation it does not work either on firefox 50.0.2 [http://canvg.github.io/canvg/examples/convert.htm](http://canvg.github.io/canvg/examples/convert.htm)

Is there any workaround for this? calling the function without paramters works really great for me, i've notice that if i use the function with parameters it works, but in my case i just need to convert all already rendered svg inline into canvas, i am not sure if i can do that using the function with parameters

Any help would be really appreciated.
Chrome on the left mozilla firefox on the right:

![screenshot_44](https://cloud.githubusercontent.com/assets/4844997/20873684/ba9ef59e-ba6f-11e6-8c5b-6c124ec1b57a.png)

**Comment by alafr** [comment]
It appears that Firefox has no support for `clientWidth` & `clientHeight` used by canvg: [canvg.js#L49-L50](https://github.com/canvg/canvg/blob/master/canvg.js#L49-L50)
There have an old but still open [bug #874811](https://bugzilla.mozilla.org/show_bug.cgi?id=874811).

As a workaround try replacing `svgTag.clientWidth` with `svgTag.getBoundingClientRect()['width']` and `svgTag.clientHeight` with `svgTag.getBoundingClientRect()['height']`.

Even in Chrome the example behaves buggily: it's size keeps increasing if I move the mouse over it. The option `{ignoreMouse: true}` should prevent that.

**Comment by LRPalacios** [comment]
Thanks a lot, the workaround is valid.

May i ask why not change the code to the suggested?

**Comment by gabelerner** [comment]
i'll actively try to merge https://github.com/canvg/canvg/pull/504 which will fix this
