### ISSUE TITLE
canvg is crashing browser

### ISSUE THREAD

**Issue by PhpSriptKiddie** [canvg/canvg#505]
I am trying to use canvg to convert paths in a flowchart that I am creating with jquery.flowchart - http://sebastien.drouyer.com/jquery.flowchart-demo/

However, when I have a lot of paths, canvg is crashing the browser. Is this simply because I am trying to convert too many svgs at the same time, or can I do anything to fix this?

Thanks,

**Comment by gabelerner** [comment]
moving to https://github.com/canvg/canvg/issues/669
