### ISSUE TITLE
svg can't be  transformed into canvas  properly

### ISSUE THREAD

**Issue by chongpanyang** [canvg/canvg#506]
I was trying transform a svg to canvas
this is what it‘s supposed to be 
![image](https://cloud.githubusercontent.com/assets/18184470/21515577/0558bff8-cd0c-11e6-91fd-7052c66614b6.png)

and this is what it actually looks like
![image](https://cloud.githubusercontent.com/assets/18184470/21515619/485885d6-cd0c-11e6-9375-de446ad1d49e.png)

**Comment by proshuai** [comment]
@chongpanyang  do you have resolve it ?

**Comment by amenadiel** [comment]
Set the `fill` attribute of your `path` elements to `none`. If your graph has that property defined via classes, canvg won't take them into account.

**Comment by gabelerner** [comment]
please submit an svg file if you still are having issues
