### ISSUE TITLE
Getting an error rendering SVG with fill-opacity defined in style

### ISSUE THREAD

**Issue by frank-rollpin** [canvg/canvg#508]
canvg fails to render the following SVG (note that it works if we remove 'fill-opacity:0' parameter):
```
<svg viewBox="0 0 400 400"> <g>
    <ellipse style="fill: none; fill-opacity:0; stroke-width: 1.6; stroke: #000000" cx="150" cy="150" rx="150" ry="150"></ellipse>
</g></svg>
```
Stack trace:
```
Uncaught TypeError: t is not a constructor
    at r.Property.addOpacity (canvg.min.js:1)
    at r.Element.ellipse.setContext (canvg.min.js:1)
    at r.Element.ellipse.render (canvg.min.js:1)
    at r.Element.g.renderChildren (canvg.min.js:1)
    at r.Element.g.render (canvg.min.js:1)
    at r.Element.svg.renderChildren (canvg.min.js:1)
    at r.Element.svg.render (canvg.min.js:1)
    at a (canvg.min.js:2)
    at Object.r.loadXmlDoc (canvg.min.js:2)
    at Object.r.loadXml (canvg.min.js:2)
```

**Comment by webenji** [comment]
I am getting the same problem with attributes "fill-opacity" and "stroke-opacity"...

**Comment by sameerjain** [comment]
you need to use rgbcolor.js from http://www.phpied.com/rgb-color-parser-in-javascript/ and add it before canvg import on the page
<script type="text/javascript" src="path_to_rgbcolor.js"></script>

**Comment by MichalStoj** [comment]
I've had the same issue. 
As @sameerjain wrote above - You need to reference all 3 js libraries: **rgbcolor.js, StackBlur.js** and **canvg.js**

As canvg description states:
> ## Usage
> Include the following files in your page:

```
<script type="text/javascript" src="http://canvg.github.io/canvg/rgbcolor.js"></script> 
<script type="text/javascript" src="http://canvg.github.io/canvg/StackBlur.js"></script>
<script type="text/javascript" src="http://canvg.github.io/canvg/canvg.js"></script> 
```

**Comment by gabelerner** [comment]
this is cleaner now with readme / modules

**Comment by Emanno** [comment]
https://github.com/canvg/canvg/issues/508#issuecomment-325235904 - What version is this JS files?

**Comment by gabelerner** [comment]
i might have shipped a bugfix for the beta version see https://github.com/canvg/canvg/#usage-on-the-browser
