### ISSUE TITLE
Nested opacity not rendering correctly

### ISSUE THREAD

**Issue by FahmiA** [canvg/canvg#510]
The opacity of an element is not taking the opacity of its parents into account.

For example:

```xml
<svg xmlns="http://www.w3.org/2000/svg" version="1.1">
    <g opacity="0">
        <rect x="0" y="0" width="50" height="20" style="fill:red;stroke:pink;stroke-width:5;" opacity="1" />
        <rect x="50" y="20" width="150" height="100" style="fill:blue;stroke:pink;stroke-width:5;" opacity="0.5" />
    </g>
</svg>
```

Expected: The entire image to be blank because the top-level `g` element has `opacity="0"`.
Actual: Both the `rect` elements are visible with their stated opacity values.

**Comment by gabelerner** [comment]
fixed https://github.com/canvg/canvg/pull/602/files, not released yet
