### ISSUE TITLE
ReferenceError: RGBColor is not defined

### ISSUE THREAD

**Issue by prakashmudano** [canvg/canvg#512]
ReferenceError: RGBColor is not defined while parsing the content in svg. I tried the svg content in online parser and it's works fine.

**Comment by GuiRoCo** [comment]
I´m having the same problem. Did you find a solution?

**Comment by GuiRoCo** [comment]
I found a solution.  The problem is that you don´t have the **RGBColor** dependency.

You just need to install rgb color dependency 
`bower install rgbcolor --save`
And add it to your _index.html_
`<script src="../bower_components/rgb-color/dist/rgb-color.min.js"></script>`

**Comment by gabelerner** [comment]
should all be fixed w/ new build
