### ISSUE TITLE
Not working for http://bl.ocks.org/mbostock/1044242 such kind or graph, while working very well for all svg graphs

### ISSUE THREAD

**Issue by sandeep-daffodilsw** [canvg/canvg#513]
function addConvasCode(){
    try{
        var parentDiv = null;
        var serializer = new XMLSerializer();
        var svgString = null;
        $("svg").each(function(i, obj) {
            parentDiv = $(obj).parent();            
            svgString = serializer.serializeToString(obj);
            svgString = svgString.replace(/xmlns=\"http:\/\/www\.w3\.org\/2000\/svg\"/, '');
            svgString = svgString.trim();
            parentDiv.prepend('<div class="hiddenDiv">'+
                           '<canvas class="hiddenCanvas"></canvas>'+
                       '</div>'
                     );
            var canvasElement = $(parentDiv).find('canvas.hiddenCanvas')[0];
            canvg(canvasElement, svgString, { ignoreMouse: true, ignoreAnimation: true });   
            $(obj).css("display", "none");
        });
        
    }catch(error){
        console.log("Error occurred inside graph downloading code : "+error);
    }
}

This is my generic function converting all the svg tags into canvas, it is working well for all graphs, but not working only such kind of relationship chart created by using D3 js. Kindly help me here.
example chart is http://bl.ocks.org/mbostock/1044242 while when i convert this svg into canvas, that is changed into black black fillable circle as you can see into the attachment.
![58888ee18a555image](https://cloud.githubusercontent.com/assets/16536986/22289530/1d8738e4-e322-11e6-82f3-ed7214568264.png)

**Comment by kaojinz** [comment]
same problem d3js chart 
![screenclip](https://cloud.githubusercontent.com/assets/252305/22495775/4f3797f2-e887-11e6-991b-478fc52bd769.png)

**Comment by amenadiel** [comment]
You might have to manually set the `fill` attribute of the `path` elements to `none` before using canvg, as they are set via classes and canvg doesn't seem to take classes into account. It's just an SVG parser, it shouldn't parse CSS whatsoever.

**Comment by gabelerner** [comment]
correct, you have to bring in your own styles. `canvg` will only care about internal styles not ones on the html page per https://github.com/canvg/canvg/issues/671
