### ISSUE TITLE
Render method fails in scenario when Point or circle is undefined

### ISSUE THREAD

**Issue by pranavq212** [canvg/canvg#515]
Getting error in render function in certain scenario when Point or circle is undefined :

> 
> Uncaught TypeError: Cannot read property 'x' of undefined
>     at svg.Element.marker.node.render (canvg.js:1665)
>     at svg.Element.g.svg.Element.ElementBase.node.renderChildren (canvg.js:824)
>     at svg.Element.g.svg.Element.ElementBase.node.render (canvg.js:805)
>     at svg.Element.g.svg.Element.ElementBase.node.renderChildren (canvg.js:824)
>     at svg.Element.g.svg.Element.ElementBase.node.render (canvg.js:805)
>     at draw (canvg.js:2935)
>     at Object.svg.loadXmlDoc (canvg.js:2945)
>     at Object.svg.loadXml (canvg.js:2849)
>     at canvg (canvg.js:60)

**Comment by pranavq212** [comment]
Raised pull request for the fix working for me.
https://github.com/canvg/canvg/pull/514

**Comment by aungyin** [comment]
is this solution fixed? i am facing the same issue. Kind of solve my problem.

**Comment by aungyin** [comment]
I kind of figure out the problem, I was using <marker> tag without wrapping it with <defs> tag. The problem solved by wrapping <marker> tag inside of <defs> and the error disappear.
But I got another issue, after converting svg to png, the marker is not showing in the correct position. 
Anyhow though hope this can help someone else facing the same problem.

**Comment by gabelerner** [comment]
@pranavq212 @aungyin can one of you reopen and provide an svg file that isn't working

**Comment by gabelerner** [comment]
@pranavq212 i fixed it, your test.zip will render next release. it was due to markers being rendered outside of a path context.
