### ISSUE TITLE
Uncaught TypeError: Cannot read property 'width' of undefined

### ISSUE THREAD

**Issue by Gerarduu** [canvg/canvg#518]
Hello I want to print a Chart, but it throws me this error: 

Uncaught TypeError: Cannot read property 'width' of undefined.

Here is the svg code:

`<svg class="v-m-root" style="left: 0px; top: 0px; height: 100%; width: 100%; display: block; cursor: default;" width="100%" height="100%"><defs></defs>
		<g class="v-m-action-layer-group"></g>
		<g class="v-m-decoration-layer-group"></g>
		<g class="v-m-background"></g><g class="v-m-title" transform="translate(38, 25)"></g>
		<g class="v-m-legendGroup" transform="translate(432, 25)">
		<g class="v-m-legend"><rect class="v-bound" width="0" height="0" visibility="hidden"></rect></g></g>
		<g class="v-m-main" transform="translate(5, 25)"><g class="v-m-plot" transform="translate(33, 0)">
			<rect class="v-background-body viz-plot-background v-morphable-background" x="0" y="0" width="394" height="122" style="fill:transparent"></rect>
			<clipPath id="plot_main_clipPath_ee739eac-2759-4cac-bedf-862d3c80382a">
				<rect y="-1" width="395" height="123"></rect>
			</clipPath>
			<rect class="v-plot-bound v-bound v-zoom-plot" width="394" height="122" fill="transparent"></rect>
			<g clip-path="url(#plot_main_clipPath_ee739eac-2759-4cac-bedf-862d3c80382a)">
				<g class="v-plot-main" transform="translate(0, 0)">
				<g class="v-datapoint-group"><g class="v-stack">
				<g data-id="0" data-datapoint-id="31" class="v-datapoint v-morphable-datapoint v-datapoint-default" transform="translate(0, 10.166666666666666)">
					<rect width="85.45403551" height="20.333333333333332" fill="#748cb2" shape-rendering="crispEdges">
					</rect>
				</g>
			</g>
			<g class="v-stack">
				<g data-id="1" data-datapoint-id="32" class="v-datapoint v-morphable-datapoint v-datapoint-default" transform="translate(0, 50.83333333333333)">
					<rect width="327.58641091704004" height="20.333333333333332" fill="#748cb2" shape-rendering="crispEdges">
					</rect>	
				</g>
			</g>
			<g class="v-stack">
				<g data-id="2" data-datapoint-id="33" class="v-datapoint v-morphable-datapoint v-datapoint-default" transform="translate(0, 91.5)">
					<rect width="374.06536994256" height="20.333333333333336" fill="#748cb2" shape-rendering="crispEdges"></rect>
				</g>
			</g>
		</g>
		<g class="v-datalabel-group">
		<g data-datapoint-id="31" class="v-datalabel v-morphable-label" fill="#333333" font-family="'Open Sans', Arial, Helvetica, sans-serif" font-size="12px" font-weight="normal" font-style="normal" cssString="fill:#333333;font-family:'Open Sans', Arial, Helvetica, sans-serif;font-size:12px;font-weight:normal;font-style:normal;" transform="translate(35.79732894897461,24.83333396911621)"><text>54</text></g><g data-datapoint-id="32" class="v-datalabel v-morphable-label" fill="#333333" font-family="'Open Sans', Arial, Helvetica, sans-serif" font-size="12px" font-weight="normal" font-style="normal" cssString="fill:#333333;font-family:'Open Sans', Arial, Helvetica, sans-serif;font-size:12px;font-weight:normal;font-style:normal;" transform="translate(153.504150390625,65.49999904632568)"><text>208</text></g><g data-datapoint-id="33" class="v-datalabel v-morphable-label" fill="#333333" font-family="'Open Sans', Arial, Helvetica, sans-serif" font-size="12px" font-weight="normal" font-style="normal" cssString="fill:#333333;font-family:'Open Sans', Arial, Helvetica, sans-serif;font-size:12px;font-weight:normal;font-style:normal;" transform="translate(176.74362182617188,106.1666669845581)"><text>237</text></g></g></g></g><g class="v-referenceline-group" clip-path="url(#plot_main_clipPath_ee739eac-2759-4cac-bedf-862d3c80382a)"></g></g><g class="v-m-categoryAxis v-m-yAxis" transform="translate(0, 0)"><rect class="v-bound" width="33" height="122" fill="transparent"></rect><g class="v-axis"><g class="v-m-axisTitle" transform="translate(0,0)"></g><g class="v-m-axisBody" transform="translate(0,0)" clip-path="url(#clip-path-b34a9dc9-c29d-499b-a710-62bc04c29bf6)"><clipPath class="v-clippath" id="clip-path-b34a9dc9-c29d-499b-a710-62bc04c29bf6"><rect x="-1" y="-1" width="35" height="124"></rect></clipPath><g class="v-label-group"><g class="v-label v-morphable-label viz-axis-label v-axis-item index_0" fill="#333333" font-size="12px" font-weight="normal" font-family="'Open Sans', Arial, Helvetica, sans-serif" font-style="normal" categorylabel-id="0" transform="translate(0,0)"><rect class="viz-axis-label-rect" fill="transparent" x="1" y="1" width="31" height="38.666666666666664"></rect><g class="v-axis-label-wrapper"><text x="27" y="24.03333333333333" text-anchor="end">A16</text></g></g><g class="v-label v-morphable-label viz-axis-label v-axis-item index_0" fill="#333333" font-size="12px" font-weight="normal" font-family="'Open Sans', Arial, Helvetica, sans-serif" font-style="normal" categorylabel-id="1" transform="translate(0,40.66666667)"><rect class="viz-axis-label-rect" fill="transparent" x="1" y="1" width="31" height="38.666666666666664"></rect><g class="v-axis-label-wrapper"><text x="27" y="24.03333333333333" text-anchor="end">B16</text></g></g><g class="v-label v-morphable-label viz-axis-label v-axis-item index_0" fill="#333333" font-size="12px" font-weight="normal" font-family="'Open Sans', Arial, Helvetica, sans-serif" font-style="normal" categorylabel-id="2" transform="translate(0,81.33333333)"><rect class="viz-axis-label-rect" fill="transparent" x="1" y="1" width="31" height="38.66666666666667"></rect><g class="v-axis-label-wrapper"><text x="27" y="24.033333333333335" text-anchor="end">A15</text></g></g></g></g></g></g><g class="v-m-valueAxis v-m-xAxis" transform="translate(33, 122)"><rect class="v-bound" width="394" height="0" fill="transparent"></rect><g class="v-axis"><g class="v-m-axisScrollbar" transform="translate(0,0)"></g><g class="v-m-axisTitle" transform="translate(0,0)"></g><g class="v-m-axisBody" transform="translate(0,0)"><rect class="v-bound" width="394" height="0" fill="transparent"></rect></g></g></g><g class="v-m-scrollbar" transform="translate(427, 0)"></g></g></svg>`

I'm using html2canvas and canvg. Can anyone tell whats happening?

Kind regards,

Gerard Riera Puig.

**Comment by Minxine-Yao** [comment]
You might set the attributes `width` and `height` of the `svg` element an accurate number instead of percentage.

**Comment by Minxine-Yao** [comment]
@Gerarduu You might set the attributes width and height of the svg element an accurate number instead of percentage.

**Comment by Minxine-Yao** [comment]
@Gerarduu  You might set the attributes `width` and `height` of the `svg` element an accurate number instead of percentage.

**Comment by Gerarduu** [comment]
@Minxine-Yao Hey, 

Finally I did this:

width=parent().width();
height=parent().height();

And it worked like a charm.

Best Regards,

Gerard Riera Puig.

**Comment by jgallegosl** [comment]
Excuse me @Gerarduu where did you put the width and height properties on your code i have this so far:

$('#imgDownloadPdf').click(function () {

        var svgElements = $('#tcMainPanel').find('svg');

        replace all svgs with a temp canvas
        svgElements.each(function () {
        var canvas, xml;

            canvas = document.createElement("canvas");
            canvas.className = "screenShotTempCanvas";

            console.log('width: ' + $(this).parent().width());
            console.log('height: ' + $(this).parent().height());

            canvas.width = $(this).parent().width();
            canvas.height = $(this).parent().height();

            //convert SVG into a XML string
            xml = (new XMLSerializer()).serializeToString(this);

            // Removing the name space as IE throws an error
            xml = xml.replace(/xmlns=\"http:\/\/www\.w3\.org\/2000\/svg\"/, '');

            //draw the SVG onto a canvas
            canvg(canvas, xml);

            $(canvas).insertAfter(this);

            //hide the SVG element
            this.className = "tempHide";
            $(this).hide();
        });

        var imgData;
        html2canvas($("#tcMainPanel"), {
            useCORS: true,
            onrendered: function (canvas) {
                imgData = canvas.toDataURL('image/png');
                var doc = new jsPDF('p', 'pt', 'a2');
                doc.addImage(imgData, 'PNG', 0, 0);
                doc.save('sample-file.pdf');
                //window.open(imgData);
            }
        });

        //exportPdf($('#tcMainPanel'));
    });

thanks in advance!

**Comment by Gerarduu** [comment]
Hi @jgallegosl ,

You have to modify the canvg.js script itself.

There is a chunk in the code where it defines the width and the height. Like this:

width = 100%;
height = 100%;

So I modified this parameters to this:

width=parent().width();
height=parent().height();

And it worked in my particular case. I don't know if it will work with you.

Try it, and if you don't find the chunk of code where it defines those parameters in the canvg.js script, I'll try to look it up for you and show to you the exact line.

Best Regards,

Gerard Riera Puig.

**Comment by gabelerner** [comment]
chart works on example page. please reread README on how to use this library.
