### ISSUE TITLE
Add support for external svg when using <use xlink:href>

### ISSUE THREAD

**Issue by josche-duplicate** [canvg/canvg#521]
If one were to supply the extra Svg's would be nice to have the compiler also reference other docs to fill
example: 

`<svg version="1.1" >
    <defs>
            <`**use xlink:href="#path-1" fill="black"**`></use>
    </defs>
    <g id="Page-2" stroke="none" stroke-width="1" fill="none">
        <g stroke="#000000">
            `<**use id="Rectangle-Copy" mask="url(#mask-2)" stroke-width="8" xlink:href="#path-1"**`></use>
        </g>
    </g>
</svg>`

**Comment by gabelerner** [comment]
moving into https://github.com/canvg/canvg/issues/673
