### ISSUE TITLE
Marker not getting exported at all

### ISSUE THREAD

**Issue by stripathix** [canvg/canvg#523]
It works for the path but markers are not getting exported to canvas. It just draws the path.

My marker looks like this
`<defs><marker id="meteo-barbheadLight" orient="auto" markerHeight="10" markerWidth="10" refX="-14" refY="1.8"><path d="M0, 0 V4 L6, 2 Z" fill="black"></path></marker></defs>`

**Comment by stripathix** [comment]
Found that with -ve value of refX or refY is causing this problem.
refX="-14"

**Comment by gabelerner** [comment]
markers are supported and can see that in the example page, please provide your full svg or a jsfiddle to your full setup for any help.
