### ISSUE TITLE
Greater-than symbol on canvas

### ISSUE THREAD

**Issue by raulpiiber** [canvg/canvg#525]
On IE 11 using latest code from master I am getting greater-than symbol on output canvas. What could be causing this?

![blackarea](https://cloud.githubusercontent.com/assets/8987543/25487916/41a47932-2b6e-11e7-94e2-43fd83e48395.PNG)

**Comment by gabelerner** [comment]
please provide your full svg or a jsfiddle for me to debug and reopen the issue
