### ISSUE TITLE
High chart become blank

### ISSUE THREAD

**Issue by cseppd** [canvg/canvg#529]
After take whole page, charts are absent. I need whole page as image
my code:
function svgToCanvas(targetElem) {
    var nodesToRecover = [];
    var nodesToRemove = [];

    var svgElem = targetElem.find('svg');

    svgElem.each(function (index, node) {
        var parentNode = node.parentNode;
        var svg = parentNode.innerHTML;

        var canvas = document.createElement('canvas');

        canvg(canvas, svg, { ignoreMouse: true, ignoreAnimation: true, log: true });

        nodesToRecover.push({
            parent: parentNode,
            child: node
        });
        parentNode.removeChild(node);

        nodesToRemove.push({
            parent: parentNode,
            child: canvas
        });

        parentNode.appendChild(canvas);
    });

    html2canvas(targetElem, {
        useCORS: true,
        letterRendering: true,
        taintTest: true,
        onrendered: function (canvas) {
            var ctx = canvas.getContext('2d');
            ctx.webkitImageSmoothingEnabled = false;
            ctx.mozImageSmoothingEnabled = false;
            ctx.imageSmoothingEnabled = false;          
            canvas.toBlob(function (blob) {
                nodesToRemove.forEach(function (pair) {
                    pair.parent.removeChild(pair.child);
                });

                nodesToRecover.forEach(function (pair) {
                    pair.parent.appendChild(pair.child);
                });
                saveAs(blob, 'screenshot' + '.png');
            });
        }
    });

}
PLZ help ?????
![screenshot 1](https://cloud.githubusercontent.com/assets/5753269/26095317/f2d4491a-3a3e-11e7-854c-6f009255338f.png)

Expected Image:
![untitled](https://cloud.githubusercontent.com/assets/5753269/26095402/487db4be-3a3f-11e7-8e90-cb4267f00f4d.png)

**Comment by gabelerner** [comment]
please create a jsfiddle or attach and svg file to receive help
