### ISSUE TITLE
Conflict loading StackBlur and rgbcolor when using require.js

### ISSUE THREAD

**Issue by gonzalocalvo91** [canvg/canvg#534]
Hello, I get an error loading StackBlur.js and rgbcolor.js when require.js is being used. This is the conflicting line (there is a similar one in rgbcolor.js).

	// export as AMD...
	if ( typeof define !== 'undefined' && define.amd ) {
	    define( function () { return stackBlur; });
	}

Since require.js has a function called define this if gets executed and my standard load fails.

<script src=".../lib/canvg/StackBlur.js"
	type="text/javascript" charset="UTF-8"></script>

Anyone had this issue before? Any tips on how to deal with it?

Thanks in advance.

**Comment by amenadiel** [comment]
If you're using `require.js` or `systemjs` then you shouldn't use the script elements of `StackBlur` or `rgbcolor`. Just require them from your main script (for example, `main.js`):

```js
define(['canvg'],function(canvg) {
  ...do something with canvg
});
```
When requiring `canvg` as a dependency, it will in turn require the other two scripts as dependencies.

**Comment by gabelerner** [comment]
should all be fixed w/ new build
