### ISSUE TITLE
Someone check the brace count

### ISSUE THREAD

**Issue by jjc1994** [canvg/canvg#536]
I've been checking the brace count (the number of characters that match { and } do not correspond!) and it is off by one since this commit from Gabe Lerner:

apply styles to svg tag after it is parsed

Please fix it or explain this phenomenon! It's been there since Feb 22, 2015.

**Comment by alafr** [comment]
There could be some unmatched `{}` in strings or regex expressions, for example at [L144](https://github.com/canvg/canvg/blob/master/canvg.js#L144). It would throw a SyntaxError if there was an error.

**Comment by gabelerner** [comment]
^ correct .. here's a link to a SHA for the future https://github.com/canvg/canvg/blob/1b818b2e693ffa19b68e4ddad314fba3f6b1dc7a/src/canvg.js#L184
