### ISSUE TITLE
The font-family is not persisted when convert svg with text to png (IE v11)

### ISSUE THREAD

**Issue by yiddou** [canvg/canvg#538]
I have tested, seems only the custom font family is not applied to PNG.

mycode:
<div class="col-md-10 col-lg-10 col-md-offset-1 col-lg-offset-1 margintop-30" >
        <div id="svg-wrapper" style="position:relative;">
            <svg xmlns="http://www.w3.org/2000/svg" version="1.1" id="svg-01" width="880px" height="500px" style="border:1px solid blue;z-index:0">
               
                <g transform="translate(480 210) rotate(-30 50 70)">
                    <ellipse cx="64.5" cy="64.5" rx="60.9" ry="20.4" style="fill:plum;" />
                    <text id="name" x="38" y="74" font-size="22" style="fill:red;" font-family="站酷酷黑">中文</text>  </g>
            </svg>
        </div>

function addNamePlateTest() {
            window.onbeforeunload = null;
            var mycanvas = document.createElement('canvas');
            var svg = $('#svg-wrapper').html();
            svg = svg.replace(/>\s+</g, '><').trim();
            canvg(mycanvas, svg);
            var src = mycanvas.toDataURL("image/png");
            $('#np').remove();
            $('#product-img').append('<image id="np" class="pbc-preview-layer" src="' + src + '" style="z-index:3"/>');
        }

**Comment by gabelerner** [comment]
please add a jsfiddle with an example. font-family is somewhat supported just need the full setup to debug.
