### ISSUE TITLE
Image with base64 data not converting to canvas

### ISSUE THREAD

**Issue by SharmaRajesh2210** [canvg/canvg#541]
I have this image it is not converting into canvas.

img src="data:image/svg+xml;charset=UTF-8;base64,CiAgCiAgCiAgCiAgPHN2ZyBkYXRhLWFuY2hvclg9IjIxIiBkYXRhLWFuY2hvclk9IjIxIiB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI0MiIgaGVpZ2h0PSI0MiIgdmlld0JveD0iMCAwIDQyIDQyIiB2ZXJzaW9uPSIxLjEiPgogICAgPGcgc3Ryb2tlPSJub25lIiBzdHJva2Utd2lkdGg9IjEiIGZpbGw9Im5vbmUiIGZpbGwtcnVsZT0iZXZlbm9kZCI+CiAgICAgIDxwYXRoIGQ9Ik00MS45IDIzLjFDNDAuOSAzMyAzMyA0MC45IDIzLjEgNDEuOUwyMy4xIDIzLjEgNDEuOSAyMy4xWk00MS45IDE4LjlDNDAuOSA5IDMzIDEuMSAyMy4xIDAuMUwyMy4xIDE4LjkgNDEuOSAxOC45Wk0wLjEgMTguOUMxLjEgOSA5IDEuMSAxOC45IDAuMUwxOC45IDE4LjkgMC4xIDE4LjlaTTAuMSAyMy4xQzEuMSAzMyA5IDQwLjkgMTguOSA0MS45TDE4LjkgMjMuMSAwLjEgMjMuMVoiIGZpbGw9IiM3RkQ3RkYiID48L3BhdGg+CiAgICAgIDxjaXJjbGUgZmlsbD0iIzAwQUVGRiIgY3g9IjIxLjEiIGN5PSIyMS4xIiByPSIxMS44IiA+PC9jaXJjbGU+CiAgICAgIDx0ZXh0IGZvbnQtZmFtaWx5PSJOb3RvIFNhbnMiIGZvbnQtc2l6ZT0iMTAiIGZvbnQtd2VpZ2h0PSJub3JtYWwiIGxldHRlci1zcGFjaW5nPSIwLjQiIGZpbGw9IiNGRkZGRkYiPjx0c3BhbiB4PSIxMSIgeT0iMjUiPjY0MzwvdHNwYW4+PC90ZXh0PgogICAgPC9nPgogIDwvc3ZnPgoKICAK" class="leaflet-marker-icon leaflet-zoom-animated leaflet-clickable" style="margin-left: -21px; margin-top: -21px; transform: translate3d(694px, 351px, 0px); z-index: 351;" tabindex="0"

I need to convert this into canvas for html2canvas plugin because in IE this image not capture. Rest of the browses it is working fine.

**Comment by gabelerner** [comment]
moving to https://github.com/canvg/canvg/issues/673
