### ISSUE TITLE
Keep SVG alive

### ISSUE THREAD

**Issue by adamwlev** [canvg/canvg#547]
Hi,

I am looking for a solution that will export my svg (rather large, around 9MB) to a file but keep the svg on the page. For example, my user can interact with the svg then do an export and then keep interacting. I was trying this package tonight and it seemed to convert the svg element to a canvas element when calling canvg and the svg element seemed to disappear. Am I missing something completely? Or is the functionality I am describing not possible with this project?

Thanks,
Adam

**Comment by gabelerner** [comment]
you want to just export it as an image at different times?

have you seen https://github.com/canvg/canvg#usage ?

you can use `canvg(document.getElementById('drawingArea'), '<svg>...</svg>')` and then use https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/toDataURL to export as image whenever you desire.
