### ISSUE TITLE
Issue converting an svg to canvas

### ISSUE THREAD

**Issue by mattjankowski** [canvg/canvg#548]
I've just started using this library on an application with svgs that need to be converted to canvas. Overall i works great, however I am having trouble with one svg:

`<svg id="object_1191"  x="50" y="50" width="100" height="100"  xmlns="http://www.w3.org/2000/svg"><g id="object_1191" ><rect   id="object_1191"    stroke="#000" height="50" width="50" y="25" x="25" fill-opacity="null" stroke-opacity="null" stroke-width="1.5" fill="#fff"/><path id="object_1191"  transform="rotate(40.87020492553711 19.62812232971194,80.96499633789061) " id="svg_5" d="m11.75312,87.59l7.875,-13.25l7.875,13.25l-15.75,0z" fill-opacity="null" stroke-opacity="null" stroke-width="1.5" stroke="#000" fill="none"/></g></svg>`

You an see the code in action in this [pen](https://codepen.io/mjankowski/pen/xXmGGo)

Is this some issue with canvg or do I need to restructure the svg?

Thanks,
Matt

**Comment by alafr** [comment]
There are two id attributes, `id="object_1191"` and  `id="svg_5"` for the same element

**Comment by mattjankowski** [comment]
alafr, that did the trick! Thank you!
