### ISSUE TITLE
Transform with scale(0 0) results in no scaling.

### ISSUE THREAD

**Issue by netives** [canvg/canvg#551]
The issue seems to be in the scale apply() method, where it assume not having a scale should default to 1 and not 0. I assume this is to make the unapply() method work by inverting the scale.

Assuming that apply is called then unapply... we could correct this by storing the ctx.currentTransform in apply.. apply the scale for 0, 0. And then in unapply.. ctx.resetTransform(), ctx.transform(priorMatrix).

Not sure if there is any kind of transform object caching that might interfere with this solution and making storing state between apply/unapply not work.

Oddly enough.. applyToPoint() does the right thing and defaults to a scale of 0 for undefined.

**Comment by gabelerner** [comment]
i actually think `applyToPoint` is wrong in the sense that it's scaling to 0 where the default should be to scale to 1 (which does nothing). either way, is there a specific svg that's rendering wrong that you can provide?
