### ISSUE TITLE
Highchart vertical bar chart showing extra bar

### ISSUE THREAD

**Issue by Stewart100** [canvg/canvg#552]
Hi,

I am using canvg to convert my highcharts to png's.

My problem is that the horizontal bar charts are rendered fine but the horizontal bar chart shows an extra bar.

How can I resolve this.

Thanks

Stewart

**Comment by morganzysman** [comment]
Hi, I'm also doing the same thing as you are.

I have no issue using Chrome / FF, what browser are you using?

But I have an issue on IE11, only half on mychart is been converted to PNG.

`var svgElements = $(".container").find('svg');

            //replace all svgs with a temp canvas
            svgElements.each(function() {
              var canvas, xml;
              // canvg doesn't cope very well with em font sizes so find the calculated size in pixels and replace it in the element.
              $.each($(this).find('[style*=em]'), function(index, el) {
                $(this).css('font-size', getStyle(el, 'font-size'));
              });
        
              canvas = document.createElement("canvas");
              canvas.className = "screenShotTempCanvas";
              //convert SVG into a XML string
              xml = (new XMLSerializer()).serializeToString(this);
        
              // Removing the name space as IE throws an error
              xml = xml.replace(/xmlns=\"http:\/\/www\.w3\.org\/2000\/svg\"/, '');
        
              //draw the SVG onto a canvas
              canvg(canvas, xml);
              $(canvas).insertAfter(this);
              //hide the SVG element
              ////this.className = "tempHide";
              $(this).attr('class', 'tempHide');
              $(this).hide();
            });`

**Comment by Stewart100** [comment]
Hi, I have found that if I don't use canvg and use:


resultCanvas.getContext("2d").drawImage(chartImg, 0, 0, w, h);


I also get the first vertical bar repeated. I don't get this error on horizontal bar charts?


Any ideas?


By the way, using this method works on Chrome and Edge browsers.


Stewart


________________________________

**Comment by gabelerner** [comment]
please provide a jsfiddle or svg if something is not working
