### ISSUE TITLE
Sorry amendment to pervious post

### ISSUE THREAD

**Issue by Stewart100** [canvg/canvg#553]
Hi,

I should have said that the vertical bar chart has an extra bar. I have also checked that the chart is showing correctly in the <div> before conversion by canvg.

Thanks
Stewart

**Comment by amenadiel** [comment]
@Stewart100  You can always edit the original comment/issue

**Comment by gabelerner** [comment]
yes, please find the original issue and leave a comment there for tracking. reopen if needed.
