### ISSUE TITLE
Canvg: How to implement pattern fill?

### ISSUE THREAD

**Issue by mattjankowski** [canvg/canvg#559]
I am attempting to create an svg with pattern fill:

`<svg height="1000" width="1000" style="float:left" class="pattern-swatch">
   <defs>
    <pattern id="circles-1" patternUnits="userSpaceOnUse" width="6" height="1">
      <image xlink:href="image/svg+xml;base64,PHN2ZyB4bWxucz0naHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmcnIHdpZHRoPScxMCcgaGVpZ2h0PScxMCc+CiAgPHJlY3Qgd2lkdGg9JzEwJyBoZWlnaHQ9JzEwJyBmaWxsPSd3aGl0ZScgLz4KICA8cmVjdCB4PScwJyB5PScwJyB3aWR0aD0nOScgaGVpZ2h0PScxMCcgZmlsbD0nIzU1OTRlNycgLz4KPC9zdmc+"
        x="0" y="0" width="6" height="2">
      </image>
    </pattern>
  </defs>
  <rect style="fill: url(#circles-1) #fff;" x="0" y="0" height="1000" width="1000"></rect>
</svg>`

It renders fine in the [browser](https://codepen.io/mjankowski/pen/goOzJj). However when I try to render it with canvg in the playground or the[ example](https://canvg.github.io/canvg/examples/index.htm)s page it fails. What do I need to do?

Thanks,
Matt

**Comment by alafr** [comment]
The href should be data:image/svg+xml.... Otherwise the browser just creates a pattern with the "not found" image. But i don't know if there is support for dataURIs in canvg...

**Comment by gabelerner** [comment]
dataURIs are not supported yet, but this issue is valid.  will look at some point into supporting `image/svg+xml;base64`

**Comment by gabelerner** [comment]
moving to https://github.com/canvg/canvg/issues/673
