### ISSUE TITLE
Creating some unwanted colors at end of stackBars

### ISSUE THREAD

**Issue by HemanthPaluri** [canvg/canvg#560]
Hi ,
I am using canvg to convert  svg graphs to canvas images. When i am trying to convert the SVG to image at the end of each stackBar there is some unwanted color is being added. I am not getting where it is getting added from? 
Please find the code in JSFiddle [here](https://jsfiddle.net/jjuwgygc/ ) 

i am using above JSFiddle SVG to convert it to image by 

`canvg(canvasId, svg)`

The final `canvasId` output what i am getting is this.
![canvg stack extra color](https://user-images.githubusercontent.com/23453546/34708887-e04835e2-f53a-11e7-82b9-e651e04ade03.PNG)

**Comment by gabelerner** [comment]
valid issue thanks, will look at some point. will probably need to minimize svg to just that one line for easier debugging.
