### ISSUE TITLE
Load multiple SVGs ?

### ISSUE THREAD

**Issue by alexszilagyi** [canvg/canvg#561]
Is there a workaround to load something like ?: 
```
canvg('canvas', 'assets/first-asset.svg');
canvg('canvas', 'assets/second-asset.svg');
```

**Comment by gabelerner** [comment]
ignoreClear: true => does not clear canvas

it's in the readme

**Comment by alexszilagyi** [comment]
@gabelerner : Thanks for the reply! Maybe I wrote it wrong, tried using the following code:
```
    canvg('canvas', 'assets/first-asset.svg', {ignoreClear : true, ignoreAnimation: true});
    canvg('canvas', 'assets/second-asset.svg', {ignoreClear : true, ignoreAnimation: true});
```

And always `second-asset.svg` its draws into my `canvas`.

**Comment by gabelerner** [comment]
http://jsfiddle.net/6r2jug6o/735/ shows both, you might have shapes with a background color or something overlaying the first svg

**Comment by alexszilagyi** [comment]
@gabelerner : you're right but in my case, while opening your link the first canvas strings gets removed / cleared on hovering the canvas element (I just hover the mouse, so no click or any other event fired).

One more thing, could be that I'm loading the svg files by specifying the path and not a simple svg string?

As you can know that a svg file contains also some metadata tags like:

```
<?xml version="1.0" encoding="utf-8"?><!-- Generator: Adobe Illustrator 16.0.0, SVG Export Plug-In . SVG Version: 6.00 Build 0)  --><!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd"><svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" width="1280px"	 height="720px" viewBox="0 0 1280 720" enable-background="new 0 0 1280 720" xml:space="preserve"><g id="bg">	<g>		<defs>
```

That's a snipped from one of my SVGs files.

**Comment by gabelerner** [comment]
the path shouldn't matter ... yea so you need `ignoreMouse: true` as well (updated: http://jsfiddle.net/6r2jug6o/736/ doesn't clear w/ mouse).  the mouse actually redraws it as it moves so it can detect if it needs to fire events or not when it's within a bounding box.  the right solution here would be to cache all bounding boxes as you draw but that' sa big refactor.

also, if the 2nd file has metatags, remember that svgs are just strings after all so you can always download the file using normal ajax and preprocess the string (for example by removing the elements you don't care for).

**Comment by alexszilagyi** [comment]
Thanks, I'll consider your feedback and maybe implement something that can be useful later.

As for now I've switched to `.png` files / sprites.
