### ISSUE TITLE
SVG text-anchor does not work with <tspan>

### ISSUE THREAD

**Issue by Makar8000** [canvg/canvg#564]
`<tspan text-anchor="start|middle|end"` does not work with canvg.

Sample code:
```HTML
<svg width="200" height="200">
  <text x="100" y="50">|
    <tspan x="100" y="50" text-anchor="start">Xtra</tspan>
  </text>
  <text x="100" y="100">|
    <tspan x="100" y="100" text-anchor="middle">Xtra</tspan>
  </text>
  <text x="100" y="150">|
    <tspan x="100" y="150" text-anchor="end">Xtra</tspan>
  </text>
</svg>
```

Using this code with canvg will ignore the `text-anchor` property and use the default value of `start`

**Comment by hsinlive** [comment]
I got the same problem too

**Comment by Puine** [comment]
Hi,
Is this issue fixed ? I downloaded canvg package via npm yesterday, and have still this issue.  
Thanks !

**Comment by gabelerner** [comment]
hey @Puine i fixed it in master but haven't published a new version to npm yet. i'll probably push up a `2.0` release this weekend so look for that

**Comment by Puine** [comment]
Great, Thanks !

**Comment by gabelerner** [comment]
you can now try the 2.0 beta @ https://www.npmjs.com/package/canvg/v/2.0.0-beta.0 or https://cdn.jsdelivr.net/npm/canvg@2.0.0-beta.0/dist/browser/canvg.min.js
