### ISSUE TITLE
Any chance of a 1.5 release?

### ISSUE THREAD

**Issue by MarkMaldaba** [canvg/canvg#570]
The last release was [v1.4](https://github.com/canvg/canvg/releases/tag/v1.4), which is currently 50 commits behind master, and several years old.

Any chance of a 1.5 release?

Note that the canvg.min.js file seems to be out of date, and the release process would obviously also need to pull in the stackblur/rgbcolor dependencies as these are no longer stored in the canvg repository directly.

**Comment by amenadiel** [comment]
@gabelerner you could also release a tag v1.4.1 if you consider that changes are minor

**Comment by gabelerner** [comment]
i just tagged current master w/ 1.5 but i didn't update any of the minified files ... at some point, somebody could include a minifier like uglify along w/ gulp or webpack into this repo with a build script that does that.  

https://github.com/canvg/canvg/releases/tag/v1.5
