### ISSUE TITLE
Does not render an svg with <use> referencing a <symbol> from another svg

### ISSUE THREAD

**Issue by amenadiel** [canvg/canvg#574]
Given a structure:

```html
<svg >
  <symbol id="sym01">
    <path d="M98.5,47.5C96.5,45.5,81,35,62,35c-2.1,0-4.2,0.1-6.2,0.3L39,26c0,4.5,1.3,9,2.4,12.1C31.7,40.7,23.3,44,16,44L0,34
	c0,8,4,16,4,16s-4,8-4,16l16-10c7.3,0,15.7,3.3,25.4,5.9C40.3,65,39,69.5,39,74l16.8-9.3c2,0.2,4.1,0.3,6.2,0.3
	c19,0,34.5-10.5,36.5-12.5S100.5,49.5,98.5,47.5z M85.5,50c-1.4,0-2.5-1.1-2.5-2.5s1.1-2.5,2.5-2.5s2.5,1.1,2.5,2.5
	C88,48.9,86.9,50,85.5,50z"/>  
  </symbol>
</svg>

<svg id="el_svg" style="height:100px;width:100px">
  <use href="#sym01" x="0" y="0" width="100" height="80"/>
</svg>
```

The symbol itself is not rendered (that's the intended behavior), but is instead shown whenever you declare an `svg` element containing the `use` tag.

However, using `canvg` on the element `#el_svg` renders nothing. I've resorted to defining the symbol as:

```html
<svg id="el_svg" style="height:100px;width:100px">
  <symbol id="sym01">
    <path d="M98.5,47.5C96.5,45.5,81,35,62,35c-2.1,0-4.2,0.1-6.2,0.3L39,26c0,4.5,1.3,9,2.4,12.1C31.7,40.7,23.3,44,16,44L0,34
	c0,8,4,16,4,16s-4,8-4,16l16-10c7.3,0,15.7,3.3,25.4,5.9C40.3,65,39,69.5,39,74l16.8-9.3c2,0.2,4.1,0.3,6.2,0.3
	c19,0,34.5-10.5,36.5-12.5S100.5,49.5,98.5,47.5z M85.5,50c-1.4,0-2.5-1.1-2.5-2.5s1.1-2.5,2.5-2.5s2.5,1.1,2.5,2.5
	C88,48.9,86.9,50,85.5,50z"/>  
  </symbol>
  <use href="#sym01" x="0" y="0" width="100" height="80"/>
</svg>
```

but this isn't optimal, since the `symbol` is meant to be reused as many times as you need in other parts of the document.

**Comment by gabelerner** [comment]
The original structure isn't valid xml/svg as it's 2 svg elements with no xml root.  I don't know what you expect to happen in that case ... are you just calling `canvg()` w/o args or are you passing it something different?

**Comment by amenadiel** [comment]
Oh I see exactly what you mean, and you're right. Canvg shouldn't need to scan the document to see if there are other SVG inside of which a referenced symbol could be found. And yeah, I was passing the contents of the second SVG element to canvg expecting it to magically know references to another SVGs in the document, but it sounds silly now.

I'll be closing this issue since it's out of the scope of Canvg.
