### ISSUE TITLE
Part of svg elements disappears during conversion to canvas (Chrome 66)

### ISSUE THREAD

**Issue by GolubevAndreyUA** [canvg/canvg#577]
Hello!
After chome updated to version 66.0.3359.117 such problem appeared (on older versions evrethyng works just fine) - After svg to canvas conversion part of the elements are missing.

**Pre canvg:**
![precanvg](https://user-images.githubusercontent.com/35058702/39129268-beaa6688-4712-11e8-99ea-0dc189adc81b.jpg)

**Post canvg:**
![posrcanvg](https://user-images.githubusercontent.com/35058702/39129279-c6daa7f0-4712-11e8-8947-1831c288d9f2.jpg)

**Missing svg elements:**
![elems](https://user-images.githubusercontent.com/35058702/39129289-d1919adc-4712-11e8-903c-7a9058c6de89.jpg)

P.s. In chrome patchnote mentioned that they changed the mechanism of canvas drawing, is there is hope that library will be updated to handle it?)

**Comment by danielle-prince** [comment]
I am also having problems converting svg to a canvas since chrome updated to v66 and was wondering if a library update is likely to resolve the issue?

**Comment by RoySung** [comment]
I have the same issue in the chrome v66.

**Comment by thangaraju** [comment]
After adding the fix suggested by @RoySung , this breaks in Internet explorer, as namespaced elements are not handled properly by the library.

**Comment by amenadiel** [comment]
Everyone has been able to try Firefox for this? 

I used to have a problem due to chrome using opengl  accelerated 2d canvases.

Is everyone using the xmlserializer to sanitze the input? When I just trimmed the SVG text it would often break or miss elements.

**Comment by gabelerner** [comment]
Please attach the SVG XML and reopen the issue.  That is the only way we are able to debug.
