### ISSUE TITLE
Support for foreignObject

### ISSUE THREAD

**Issue by vijayst** [canvg/canvg#584]
I have a SVG with foreignObject as follows.
`<svg id="comp_gen_summary" width="912" height="200"><text x="912" y="10" text-anchor="end" font-size="10px" font-family="Axiforma" fill="rgba(0,0,0,.56)">Confidence score 95%</text><g><circle class="legend-circle" cx="5" cy="46" r="5" fill="#00229ed4"></circle><circle class="legend-circle" cx="5" cy="64" r="5" fill="#007fc6d4"></circle><text class="legend-text" x="26" y="49" font-size="10px" font-family="Axiforma" fill="#00229ed4">Men</text><text class="legend-text" x="26" y="67" font-size="10px" font-family="Axiforma" fill="#007fc6d4">Women</text><text x="68.30995178222656" y="67" fill="rgba(0,0,0,.56)" font-size="10px" font-family="Axiforma">- Equality Index</text></g><text x="464" y="46" font-size="10px" font-family="Axiforma" fill="#00229ed4">Pay gap 2018</text><text x="496.80995178222656" y="94" text-anchor="middle" font-size="40px" font-family="Axiforma Medium" fill="#00229ed4">10.4%</text><foreignObject x="696" y="46" width="216" height="154"><body style="font: 14px Axiforma; background-color: rgb(255, 255, 255);">In year 2018 Gender Male's pay gap is 10.37. Male employees are being payed above your Equality Index threshold</body></foreignObject></svg>`

While converting, it is ignoring the foreignObject. Is there any workaround to this? Thanks.

**Comment by amenadiel** [comment]
Not supported yet. It isn't even supported in browsers such as explorer 10. 
Also, I believe your svg needs proper namespacing and extensions for that f.o.

**Comment by gabelerner** [comment]
I'm closing because it'll never be supported.  The goal of this project isn't to render html on canvas.

**Comment by tamtakoe** [comment]
@gabelerner write please how difficult it is to implement this feature? I want to move this transformation to web worker because this process is too slow and don't dividable to small chunks. Unfortunately I can't use window.Image there

**Comment by gabelerner** [comment]
@tamtakoe what do you mean window.Image?

**Comment by tamtakoe** [comment]
@gabelerner you can't work with DOM within web worker, but transformation svg to canvas means this popular way:
```
return new Promise(function (resolve, reject) {
    var image = new Image(); // You need Image
    image.onload = function () {
        resolve(image);
    };
    image.onerror = reject;
    image.src = uri; // This is performance bottle neck
}).then(function (image) {
    var canvas = document.createElement('canvas'); //You need document
    canvas.width = options.width;
    canvas.height = options.height;
    canvas.getContext('2d').drawImage(image, 0, 0);
    return canvas;
})
```
Maybe this transformation will be possible to do in background (worker) by your plug-in

**Comment by gabelerner** [comment]
why are you trying to draw an image on a canvas? what's the end goal? can you put up a full demo on a jsfiddle? @tamtakoe

**Comment by tamtakoe** [comment]
A little bit difficult to create fiddle for now. I try to explain on the fingers.

I need to do screenshot of browser window and save thumbnail. I use https://github.com/tsayen/dom-to-image. It is the best plugin for that. Ordinary bootstrap site has ~6kb styles per node and ~2000 nodes. Eventually I have 20-30MB of svg data befor transforming. SVG->Canvas is doing in the main stream and blocks UI and unfortunately I can't move it to background or decouple

**Comment by gabelerner** [comment]
i see, well i won't have `foreignObject` support because that would require me to essentially replicate the `dom-to-image` library in my code base (whole thing i am avoiding w/ this issue).

as for background threads, you can give it a shot w/ my library using the code you mentioned above, with the `then(...)` going to a web worker.  if you run into issues there, let me know via a separate issue like `canvg doesn't work in web worker` and we can go from there

**Comment by tamtakoe** [comment]
It is correct. Actually I try to patch `dom-to-image` by your library. And `foreignObject` providing is only thing which prevents me to do it. And I don't understand how to implement `foreignObject`. Why do you need replicate the `dom-to-image`? This is simple plugin which just clone node and transforms svg to canvas.

It is ok that you don't want to write that, but it will be good if you make some place for middleware. If you make this place and describe what you need then anybody can write code for `foreignObject` etc.

**Comment by gabelerner** [comment]
give me a small (non 30mb) svg string that has a foreignObject that you're looking to render @tamtakoe

**Comment by tamtakoe** [comment]
Example
```svg
<svg xmlns="http://www.w3.org/2000/svg" width="200" height="120">
  <foreignObject x="0" y="0" width="100%" height="100%">
    <body style="padding: 0px 0px 0px 60px; width: 200px; xmlns="http://www.w3.org/1999/xhtml">
      <main-nav style="color: rgb(51, 51, 51); padding: 0px;">
        Test
      </main-nav>
    </body>
  </foreignObject>
</svg>
```

**Comment by gabelerner** [comment]
so that's my point, `foreignObject` is html right? therefore i need to know how to convert html to canvas.  therefore i need to know how to convert all html tags to canvas.  that's not in scope here, something like https://html2canvas.hertzen.com/ seems like it works fast.

**Comment by tamtakoe** [comment]
This was first plugin which I tried :-) It looks slowly and has big size for me and I found lots of `new Image()` in the source code. But ok, I will see this more intently. Maybe it actually contains  html->canvas code without dom-methods

**Comment by mdnaserhassan** [comment]
I think you have used foreignObject to wrap text inside it . Try using text with tspan . It will be able to convert into canvas
