### ISSUE TITLE
React build fails to minify utils.js

### ISSUE THREAD

**Issue by DinkelborgAtMilchbar** [canvg/canvg#589]
I tried to create a build of a react project where I needed your plugin in, now I'm getting the following console output:

>Creating an optimized production build...
>Failed to compile.

>Failed to minify the code from this file: 

 	./node_modules/canvg/node_modules/jsdom/lib/jsdom/living/generated/utils.js:5 

>Read more here: http://bit.ly/2tRViJ9

Is there anything I can do myself to overcome this issue?

**Comment by gabelerner** [comment]
try again, we fixed the builds! please reopen if it still doesn't work.
