### ISSUE TITLE
Web font support is broken since 1.5

### ISSUE THREAD

**Issue by martynasma** [canvg/canvg#593]
It looks like web font (like Google Fonts) support, which was working on 1.4, is now broken in 1.5.

### In 1.4

Custom font is being carried on to canvas:

![image](https://user-images.githubusercontent.com/1458520/43689066-2f11a076-98fd-11e8-9300-e487711d9b22.png)

CodePen:
https://codepen.io/team/amcharts/pen/e43ed79a121a5b613715e6f90a54482f

### 1.5

Converting to canvas loses the text font for the same SVG:

![image](https://user-images.githubusercontent.com/1458520/43689080-6784bf92-98fd-11e8-84cc-9341b6b594b2.png)

CodePen:
https://codepen.io/team/amcharts/pen/ea17f41fc721247ceac9c08c47a42428

**Comment by gabelerner** [comment]
I debugged and seems like https://github.com/canvg/canvg/commit/623676abbb08dc7d4d2c26db3da922c7e89ac8bf is the regression.  Opened https://github.com/canvg/canvg/pull/594 to fix.
