### ISSUE TITLE
The Canvg is not working anymore even on JSFiddle as well

### ISSUE THREAD

**Issue by muhammadumarmightyobjects** [canvg/canvg#608]
Hi,

It has been found that in Firefox the latest version of Canvg is not working, even the [JSFiddle Example](http://jsfiddle.net/6r2jug6o/2590/) (given in readme) is not showing output. Also the example links given in the readme are not working.

The Firebug is showing this err:
TypeError: Argument 1 of DOMParser.constructor does not implement interface Principal.

Can you fix it?

Thanks

**Comment by gabelerner** [comment]
It works on 2 of my browsers.  I assume it's your browser or extensions.  Please paste a specific error from your console here and reopen the issue.

**Comment by ThorstenD** [comment]
Hi there,
Just wanted to add that I'm getting the same error in Firefox 59.0

Works fine in IE and Chrome.

I tried it with a reduced SVG:

`var data = '<svg xmlns="http://www.w3.org/2000/svg" width="400" height="110"><rect width="300" height="100" style="fill:rgb(0,0,255);stroke-width:3;stroke:rgb(0,0,0)" /></svg>'

[...]

ctx.drawSvg(data, 20,20,440,150);
`

Best,
Thorsten

**Comment by gabelerner** [comment]
@ThorstenD the linked PR above will fix, thanks
