### ISSUE TITLE
Using "em"/"rem" for font size results in super-large text

### ISSUE THREAD

**Issue by martynasma** [canvg/canvg#620]
This has already been mentioned in #532, but there has been a major version released since then, so posting it a new.

The issue is still there. If text size is specified in `em`/`rem` rather than `px`, text results in super size.

With `em` (incorrect):
![image](https://user-images.githubusercontent.com/1458520/45073780-71540380-b0e9-11e8-946f-e341d9ac8d94.png)

With `px` (correct):
![image](https://user-images.githubusercontent.com/1458520/45073824-a06a7500-b0e9-11e8-9f50-15b597c5ba42.png)

Working example using latest 1.5.2:
https://codepen.io/team/amcharts/pen/51e1d73123884a5024c4ac6a1f81c92b

**Comment by martynasma** [comment]
One more thing. Seems like using `1em` produces correct results, so there seems to be some calculation going on for em/rem.

Possibly it does not account for `pixelRatio`?

**Comment by gabelerner** [comment]
Thanks for the issue report and it is a separate problem from the previous one.

What's happening is that in some parent element, it encounters a "2em" and let's say the current font is "16px" so it says the new font is "32px".  Then later, it encounters a "2em" again but now the current font is "32px" so the new current font is "64px".  This continues and so a nested child element would render a bigger font.

The solution will be to keep track of the last seen "pixel" value separately, only set it when we encounter a new pixel value, and do all `em` calculations on that.  Will get to it soon.

**Comment by martynasma** [comment]
Awesome. Thanks!
