### ISSUE TITLE
No rendering of circles

### ISSUE THREAD

**Issue by evgeniyefimchenko** [canvg/canvg#630]
Hi, great solution!
I use the simplest settings in my code:
`<body onload="canvg()">`
But on the way out I get an empty canvas on the spot with circles.
Code without processing: http://vibr.efimchenko.ru/new.php?code_vibr=6f4IGJEbzGUe3i
Code after processing: http://vibr.efimchenko.ru/new_test.php?code_vibr=6f4IGJEbzGUe3i

Tell me what I'm doing wrong?

**Comment by gabelerner** [comment]
you have an extra semicolon on your first line
`<svg xmlns="http://www.w3.org/2000/svg" version="1.1" height="316px" width="316px";>` should be
`<svg xmlns="http://www.w3.org/2000/svg" version="1.1" height="316px" width="316px">`.

please validate your svg to be valid and then it will work http://jsfiddle.net/6r2jug6o/3670/
