### ISSUE TITLE
missing class definitions in node version

### ISSUE THREAD

**Issue by webarchymeta** [canvg/canvg#633]
Tried to use the lib using node style `require("canvg")`, we found various lack of class definitions:
```
CanvasClass: e.g. in issue50.svg, issue89.svg, issue91.svg
ImageClass: e.g. in issue97.svg
etc
```
Did I mssing including something besides including `canvg`?

**Comment by webarchymeta** [comment]
OK, it maybe is related to #627

**Comment by gabelerner** [comment]
are you in electron as well @webarchymeta ?

**Comment by webarchymeta** [comment]
Yes, I am.

**Comment by gabelerner** [comment]
ok then let's just have the discussion in https://github.com/canvg/canvg/issues/627
