### ISSUE TITLE
Typing not matching implementation

### ISSUE THREAD

**Issue by jemerald** [canvg/canvg#635]
First of all, thanks for the recent work of publishing the latest canvg package.

I can now use the canvg library with npm and import it in my Angular project like this

```
import * as canvg from 'canvg';

(<any>canvg)(c, svg, {
      ignoreMouse: true,
      ignoreAnimation: true,
      ignoreDimensions: true,
      offsetX: 40,
      offsetY: 35
});
```

## Problem

The above code works. However, I had to cast `canvg` to `any` type, otherwise typescript would complain:

> error TS2349: Cannot invoke an expression whose type lacks a call signature.

The error goes away if I change my import statement to:

```
import canvg from 'canvg';
```

However it does not work in run time the value is undefined.

It looks like the library doesn't actually use `export default canvg` as suggested by the typing `canvg.d.ts`, but uses `exports = canvg`.

## Potential fix

Change canvg.d.ts to:

```
declare namespace canvg {
  export interface Options {
    log?: boolean;
    useCORS?: boolean;
    ignoreMouse?: boolean;
    ignoreDimensions?: boolean;
    ignoreClear?: boolean;
    ignoreAnimation?: boolean;
    enableRedraw?: boolean;

    offsetX?: number;
    offsetY?: number;
    scaleWidth?: number;
    scaleHeight?: number;

    renderCallback?: (dom: Document) => void;
    forceRedraw?: () => boolean;
  }
}
declare function canvg(target?: string | HTMLCanvasElement, s?: string | Document, opts?: canvg.Options): void;

export = canvg;
```

**Comment by gabelerner** [comment]
@jemerald you're correct I'll open a PR for this at some point

**Comment by jemerald** [comment]
@gabelerner thanks for confirmation. I can raise a PR for this.

Would you say this is the best way to use canvg in an front-end node (SPA) app? i.e.

```
npm install canvg
```

and then

```
import * as canvg from 'canvg';

canvg('canvas', '../path/to/your.svg');
```

If so, should the official documentation be updated?

**Comment by gabelerner** [comment]
That should be good @jemerald  ,,, I don't want to have to document how to do it in a particular flavor of javascript and play favorites (many ways to require a file in es6, typescript, dart, etc.). Generally, you just need to require the file in some way per https://github.com/canvg/canvg#usage-on-the-browser.  Your stack should respect https://docs.npmjs.com/files/package.json#browser.  One thing I might need to do if this doesn't work for you is also add the typed definition file into the https://github.com/canvg/canvg/tree/master/dist/browser folder.

**Comment by jemerald** [comment]
Thanks @gabelerner, this should work as `dist/node/canvg.d.ts` is what the `types` field set to in [package.json](https://github.com/canvg/canvg/blob/master/package.json#L18).

Will let you know if it doesn't.
