### ISSUE TITLE
ES6/ES6 Modules

### ISSUE THREAD

**Issue by brettz9** [canvg/canvg#637]
For SVG-Edit, I converted the earlier version of your code we were using to ES6 Modules and using ES6 features like classes, const/let, etc.

Unfortunately, I did the work before taking a look to find you had been maintaining the code further along.

I'd firstly like to request an update to at least switch to ES6 Modules in source and with a `module` property in `package.json` pointing to an ES6 distribution (as well as `main` and/or `browser` pointing to UMD or what not). Since browserify isn't moving to ES6 Modules now, I might suggest moving to Rollup, which is easy to use as well as having a rich, helpful plugin environment.

If you were amenable to it, I'd also like to see more ES6 features used for greater readability and in supporting environments, potential optimization.

And I'd love to see JSDocs...

If I manage to find the time, I might submit a PR, but this is a big "if" at the moment, yet I'd like to find out now whether you'd accept and in what form, in case I do find the time. And if I don't get to it or in a timely manner, I thought it'd be good to at least get in the request.

Thanks for your hard work on this very helpful library!

**Comment by gabelerner** [comment]
Thanks for the submission @brettz9 . I agree that the Javascript language/ecosystem has evolved considerably in the time that I started canvg and would personally use TypeScript if starting it from scratch today. We also now have a fairly extensive test suite and convering to es6/TypeScript can be done in small pieces while making sure nothing breaks. We're already [using rollup](https://github.com/canvg/canvg/blob/master/rollup.config.js) in this project to generate a node vs. browser release and can do the same for a "module" release. If you submit small, atomic PRs that start converting things section by section, those would be appreciated and merged as I have time to review.  Architecturally, I'd eventually like to split each `svg.foo` tag into its own class and file.

**Comment by gabelerner** [comment]
more than ok w/ that @brettz9

**Comment by gabelerner** [comment]
closing, discussion moved to #654
