### ISSUE TITLE
Use of bitwise OR

### ISSUE THREAD

**Issue by brettz9** [canvg/canvg#649]
Hi,

(Filing this issue found in the course of SVG-Edit linting before I get back to those PRs.)

There are two uses of the bitwise OR operator here which I am guessing are not really needed?

https://github.com/canvg/canvg/blob/d1c1a40d25bd7af20b41f992be6683f2ec9463f3/src/canvg.js#L3174-L3180

These would always ensure that the second condition was run even if `needUpdate` were already truthy. I haven't looked close enough to see if this were actually necessary, and figured you might be more familiar to assess it.

Even if it is intentional, I think it'd be better done without bitwise operators for the sake of less obscurity as to intent.

**Comment by gabelerner** [comment]
not intentional, switched to normal `or`
