### ISSUE TITLE
ScaleWidth and ScaleHeight is not work well

### ISSUE THREAD

**Issue by WisestCoder** [canvg/canvg#659]
**Problem**
This is my code:
```javascript
const width = 1640;
const height = 850;
canvg(this.background, `<svg width="${width}" height="${height}">...</svg>`, {
    scaleWidth: width * 2,
    scaleHeight: height * 2,
})
```
After first render,I find the width and height of canvas is not same as scaleWidth and scaleHeight

![image](https://user-images.githubusercontent.com/21785332/50437257-f62a8d80-0923-11e9-94ce-f1a5a0c49941.png)
But once after I click the canvas,it will draw again,the width and height of canvas is same as scaleWidth and scaleHeight,That is what i expect。

![image](https://user-images.githubusercontent.com/21785332/50437407-997ba280-0924-11e9-99f1-af98b3133482.png)

**Comment by gabelerner** [comment]
can you provide an example on jsfiddle.com or upload a zip file that has your issue?

canvg typically ignores the canvas width/height in favor of the svg width/height.  scaleWidth/scaleHeight are mostly used to adjust the width/height independent from what's defined in the svg in case you want to stretch it.

**Comment by WisestCoder** [comment]
Address of demo: https://jsfiddle.net/n5u2wwjg/259051/
please open the developer tools before you run the code，Also after run the code，please keep your mouse not to the preview area。

You will get the result：
![image](https://user-images.githubusercontent.com/21785332/50464608-eb780300-09cc-11e9-8d44-4bed1625eb4a.png)

But if you click the canvas
You will get the result：
![image](https://user-images.githubusercontent.com/21785332/50464730-a1dbe800-09cd-11e9-9cd0-a7ee7be8c23b.png)

**Comment by gabelerner** [comment]
ok great i can replicate it now, will look into fixing!
