### ISSUE TITLE
Trim fails on Circleful SVG

### ISSUE THREAD

**Issue by JSalvo220** [canvg/canvg#680]
Trying to use CanVG to let me take a HTML2CANVAS screenshot of the page which includes animated SVG graphs using CIRCLEFUL.  The TRIM function fails with "s is undefined".

![image](https://user-images.githubusercontent.com/30663467/52423211-a19f3400-2ac5-11e9-80b6-e4c556df4b98.png)

**Comment by gabelerner** [comment]
please provide your full svg string and reopen

**Comment by JSalvo220** [comment]
Attached is the SVG that is being passed into canvg
[svg_string.txt](https://github.com/canvg/canvg/files/2842952/svg_string.txt)

**Comment by gabelerner** [comment]
@JSalvo220 you have `style="font-size: 22px; undefined;font-size: 12px;"` in your svg. `undefined;` is not a valid style.

**Comment by JSalvo220** [comment]
Thanks.  I really thought the root cause was the circleful plugin - this
just confirms it.
