### ISSUE TITLE
Closure varibles use too much memory

### ISSUE THREAD

**Issue by stupppid** [canvg/canvg#681]
There is an varible named 'A' in the canvg min file, and it uses too much memory, i use canvg to convert a big svg file, and i want to clear the svg elements in the varible 'A' after render, the varible 'A' uses about 30MB.

**Comment by gabelerner** [comment]
can you run it through the unminified version and let me know what variable it is? or take a heap snapshot from chrome and attach?

**Comment by stupppid** [comment]
i took a snapshot from chrome, here it is.
![picture](https://user-images.githubusercontent.com/20572419/52682004-e79e4100-2f78-11e9-8249-2fb65c1109fb.png)

**Comment by gabelerner** [comment]
after thinking about this, 30MB isn't a lot for chrome in general (it's a mem hog) for something that holds state in case of animations or mouse movements or rerenders. if you don't want this state then just `delete` the svg object that's sitting attached to your canvas (`delete document.getElementById('canvas').svg`)
