### ISSUE TITLE
Canvg 2.0 in browser

### ISSUE THREAD

**Issue by minalkumar2893** [canvg/canvg#682]
How to use the latest version of canvg in the browser. What are the dependencies that need to be imported along with canvg? I tried importing canvg along with stackblur and rgbcolor, but window.canvg object is undefined.

**Comment by gabelerner** [comment]
see resources on left side this uses the 2.0 => http://jsfiddle.net/fvhte4g6/. the original fiddle link on the readme uses the 1.x branch.

**Comment by minalkumar2893** [comment]
But for using the 2.0 version do we need to use any tools like webpack?

**Comment by gabelerner** [comment]
you shouldn't need to, make sure that your package manager respects https://github.com/canvg/canvg/blob/master/package.json#L26. that's the file that should be required on the browser
