### ISSUE TITLE
About output size of canvg

### ISSUE THREAD

**Issue by Super-dj** [canvg/canvg#683]
I preset the canvas's width and height to 300px, but when I output SVG as canvas, the canvas's width and height will be overwritten again and fill the whole screen.

![image](https://user-images.githubusercontent.com/29654657/53321792-6483d000-3914-11e9-89e5-71ffa8b0b5d5.png)

![image](https://user-images.githubusercontent.com/29654657/53321810-6fd6fb80-3914-11e9-9345-76fb25ca82a6.png)

**Comment by gabelerner** [comment]
Please attach your full svg string and the canvg call you're making or link to a jsfiddle or similar site that replicates your problem
