### ISSUE TITLE
d3js charts axis problem

### ISSUE THREAD

**Issue by sabriozer33** [canvg/canvg#685]
I am using canvg to create canvas of  charts created by using d3js. The problem is the axes of charts are not rendered.
Here a picture of a d3js chart:
![github canvg issue chart](https://user-images.githubusercontent.com/45690424/53422098-1a1b5580-39df-11e9-8419-405682ad2e4f.PNG)

and here the canvas:
![github canvg issue canvas](https://user-images.githubusercontent.com/45690424/53422107-21426380-39df-11e9-9a58-c806d18d00ba.PNG)

and the code that generates this output:

```
    const svgElem = document.getElementById('svg-container');

    const canvas = document.createElement('canvas');
    canvas.width = svgElem.clientWidth;
    canvas.height = svgElem.clientHeight;

    canvg(canvas, svgElem.innerHTML, {ignoreMouse: true});
    svgElem.removeChild(svgElem.lastChild);
    svgElem.appendChild(canvas);
```
With other charts without axes I didn't encounter this problem.
What am I missing here?

Thanks for your help

**Comment by gabelerner** [comment]
please provide the full svg string (`svgElem.innerHTML`) so that we can debug

**Comment by sabriozer33** [comment]
`"<svg preserveAspectRatio="xMinYMin meet" viewBox="0 0 600 360" class="svg-content-responsive" id="svg-content-responsive"><g class="x axis" transform="translate(50,285)" fill="none" font-size="10" font-family="sans-serif" text-anchor="middle"><path class="domain" stroke="currentColor" d="M0.5,6V0.5H500.5V6"></path><g class="tick" opacity="1" transform="translate(11.164693670949923,0)"><line stroke="currentColor" y2="6"></line><text fill="currentColor" y="9" dy="0.71em">Tue 29</text></g><g class="tick" opacity="1" transform="translate(43.42275652503719,0)"><line stroke="currentColor" y2="6"></line><text fill="currentColor" y="9" dy="0.71em">Thu 31</text></g><g class="tick" opacity="1" transform="translate(59.551787952080815,0)"><line stroke="currentColor" y2="6"></line><text fill="currentColor" y="9" dy="0.71em">February</text></g><g class="tick" opacity="1" transform="translate(91.80985080616807,0)"><line stroke="currentColor" y2="6"></line><text fill="currentColor" y="9" dy="0.71em">Feb 03</text></g><g class="tick" opacity="1" transform="translate(124.06791366025534,0)"><line stroke="currentColor" y2="6"></line><text fill="currentColor" y="9" dy="0.71em">Tue 05</text></g><g class="tick" opacity="1" transform="translate(156.3259765143426,0)"><line stroke="currentColor" y2="6"></line><text fill="currentColor" y="9" dy="0.71em">Thu 07</text></g><g class="tick" opacity="1" transform="translate(188.58403936842987,0)"><line stroke="currentColor" y2="6"></line><text fill="currentColor" y="9" dy="0.71em">Sat 09</text></g><g class="tick" opacity="1" transform="translate(220.84210222251713,0)"><line stroke="currentColor" y2="6"></line><text fill="currentColor" y="9" dy="0.71em">Mon 11</text></g><g class="tick" opacity="1" transform="translate(253.10016507660438,0)"><line stroke="currentColor" y2="6"></line><text fill="currentColor" y="9" dy="0.71em">Wed 13</text></g><g class="tick" opacity="1" transform="translate(285.35822793069167,0)"><line stroke="currentColor" y2="6"></line><text fill="currentColor" y="9" dy="0.71em">Fri 15</text></g><g class="tick" opacity="1" transform="translate(317.6162907847789,0)"><line stroke="currentColor" y2="6"></line><text fill="currentColor" y="9" dy="0.71em">Feb 17</text></g><g class="tick" opacity="1" transform="translate(349.8743536388662,0)"><line stroke="currentColor" y2="6"></line><text fill="currentColor" y="9" dy="0.71em">Tue 19</text></g><g class="tick" opacity="1" transform="translate(382.13241649295344,0)"><line stroke="currentColor" y2="6"></line><text fill="currentColor" y="9" dy="0.71em">Thu 21</text></g><g class="tick" opacity="1" transform="translate(414.3904793470407,0)"><line stroke="currentColor" y2="6"></line><text fill="currentColor" y="9" dy="0.71em">Sat 23</text></g><g class="tick" opacity="1" transform="translate(446.648542201128,0)"><line stroke="currentColor" y2="6"></line><text fill="currentColor" y="9" dy="0.71em">Mon 25</text></g><g class="tick" opacity="1" transform="translate(478.90660505521527,0)"><line stroke="currentColor" y2="6"></line><text fill="currentColor" y="9" dy="0.71em">Wed 27</text></g></g><text transform="translate(300 ,325)" style="text-anchor: middle;">Date</text><g class="y1 axis" transform="translate(50,25)" fill="none" font-size="10" font-family="sans-serif" text-anchor="end"><path class="domain" stroke="currentColor" d="M-6,260.5H0.5V0.5H-6"></path><g class="tick" opacity="1" transform="translate(0,260.5)"><line stroke="currentColor" x2="-6"></line><text fill="currentColor" x="-9" dy="0.32em">0</text></g><g class="tick" opacity="1" transform="translate(0,208.5)"><line stroke="currentColor" x2="-6"></line><text fill="currentColor" x="-9" dy="0.32em">20</text></g><g class="tick" opacity="1" transform="translate(0,156.5)"><line stroke="currentColor" x2="-6"></line><text fill="currentColor" x="-9" dy="0.32em">40</text></g><g class="tick" opacity="1" transform="translate(0,104.5)"><line stroke="currentColor" x2="-6"></line><text fill="currentColor" x="-9" dy="0.32em">60</text></g><g class="tick" opacity="1" transform="translate(0,52.5)"><line stroke="currentColor" x2="-6"></line><text fill="currentColor" x="-9" dy="0.32em">80</text></g><g class="tick" opacity="1" transform="translate(0,0.5)"><line stroke="currentColor" x2="-6"></line><text fill="currentColor" x="-9" dy="0.32em">100</text></g></g><text transform="rotate(-90)" dy="1em" class="y1label" y="50" x="-160" style="text-anchor: middle;">Label1</text><rect transform="translate(45.06578947368421,25)" x="16.129031427043632" width="9.868421052631577" y="158.6" height="101.4" style="fill: gray;"><title>39</title></rect><rect transform="translate(45.06578947368421,25)" x="32.258062854087264" width="9.868421052631577" y="156" height="104" style="fill: gray;"><title>40</title></rect><rect transform="translate(45.06578947368421,25)" x="48.38709428113089" width="9.868421052631577" y="223.6" height="36.400000000000006" style="fill: gray;"><title>14</title></rect><rect transform="translate(45.06578947368421,25)" x="64.51612570817453" width="9.868421052631577" y="208" height="52" style="fill: gray;"><title>20</title></rect><rect transform="translate(45.06578947368421,25)" x="80.64515713521817" width="9.868421052631577" y="85.79999999999998" height="174.20000000000002" style="fill: gray;"><title>67</title></rect><rect transform="translate(45.06578947368421,25)" x="96.77418856226178" width="9.868421052631577" y="257.4" height="2.6000000000000227" style="fill: gray;"><title>1</title></rect><rect transform="translate(45.06578947368421,25)" x="112.90321998930543" width="9.868421052631577" y="39" height="221" style="fill: gray;"><title>85</title></rect><rect transform="translate(45.06578947368421,25)" x="129.03225141634906" width="9.868421052631577" y="39" height="221" style="fill: gray;"><title>85</title></rect><rect transform="translate(45.06578947368421,25)" x="145.16128284339268" width="9.868421052631577" y="31.19999999999999" height="228.8" style="fill: gray;"><title>88</title></rect><rect transform="translate(45.06578947368421,25)" x="161.29031427043634" width="9.868421052631577" y="241.8" height="18.19999999999999" style="fill: gray;"><title>7</title></rect><rect transform="translate(45.06578947368421,25)" x="177.41934569747994" width="9.868421052631577" y="174.2" height="85.80000000000001" style="fill: gray;"><title>33</title></rect><rect transform="translate(45.06578947368421,25)" x="193.54837712452357" width="9.868421052631577" y="195" height="65" style="fill: gray;"><title>25</title></rect><rect transform="translate(45.06578947368421,25)" x="209.67740855156723" width="9.868421052631577" y="236.6" height="23.400000000000006" style="fill: gray;"><title>9</title></rect><rect transform="translate(45.06578947368421,25)" x="225.80643997861085" width="9.868421052631577" y="254.8" height="5.199999999999989" style="fill: gray;"><title>2</title></rect><rect transform="translate(45.06578947368421,25)" x="241.93547140565445" width="9.868421052631577" y="13" height="247" style="fill: gray;"><title>95</title></rect><rect transform="translate(45.06578947368421,25)" x="258.0645028326981" width="9.868421052631577" y="228.8" height="31.19999999999999" style="fill: gray;"><title>12</title></rect><rect transform="translate(45.06578947368421,25)" x="274.19353425974174" width="9.868421052631577" y="20.799999999999983" height="239.20000000000002" style="fill: gray;"><title>92</title></rect><rect transform="translate(45.06578947368421,25)" x="290.32256568678537" width="9.868421052631577" y="88.4" height="171.6" style="fill: gray;"><title>66</title></rect><rect transform="translate(45.06578947368421,25)" x="306.451597113829" width="9.868421052631577" y="161.2" height="98.80000000000001" style="fill: gray;"><title>38</title></rect><rect transform="translate(45.06578947368421,25)" x="322.5806285408727" width="9.868421052631577" y="197.6" height="62.400000000000006" style="fill: gray;"><title>24</title></rect><rect transform="translate(45.06578947368421,25)" x="338.70965996791625" width="9.868421052631577" y="187.2" height="72.80000000000001" style="fill: gray;"><title>28</title></rect><rect transform="translate(45.06578947368421,25)" x="354.8386913949599" width="9.868421052631577" y="10.400000000000006" height="249.6" style="fill: gray;"><title>96</title></rect><rect transform="translate(45.06578947368421,25)" x="370.9677228220035" width="9.868421052631577" y="31.19999999999999" height="228.8" style="fill: gray;"><title>88</title></rect><rect transform="translate(45.06578947368421,25)" x="387.09675424904714" width="9.868421052631577" y="127.4" height="132.6" style="fill: gray;"><title>51</title></rect><rect transform="translate(45.06578947368421,25)" x="403.2257856760908" width="9.868421052631577" y="226.2" height="33.80000000000001" style="fill: gray;"><title>13</title></rect><rect transform="translate(45.06578947368421,25)" x="419.35481710313445" width="9.868421052631577" y="156" height="104" style="fill: gray;"><title>40</title></rect><rect transform="translate(45.06578947368421,25)" x="435.4838485301781" width="9.868421052631577" y="20.799999999999983" height="239.20000000000002" style="fill: gray;"><title>92</title></rect><rect transform="translate(45.06578947368421,25)" x="451.6128799572217" width="9.868421052631577" y="210.6" height="49.400000000000006" style="fill: gray;"><title>19</title></rect><rect transform="translate(45.06578947368421,25)" x="467.7419113842653" width="9.868421052631577" y="166.4" height="93.6" style="fill: gray;"><title>36</title></rect><rect transform="translate(45.06578947368421,25)" x="483.8709428113089" width="9.868421052631577" y="83.19999999999999" height="176.8" style="fill: gray;"><title>68</title></rect></svg>"`

sorry for the late answer due to different timezones

**Comment by gabelerner** [comment]
```
<svg preserveAspectRatio="xMinYMin meet" viewBox="0 0 600 360" class="svg-content-responsive" id="svg-content-responsive"><g class="x axis" transform="translate(50,285)" fill="none" font-size="10" font-family="sans-serif" text-anchor="middle"><path class="domain" stroke="currentColor" d="M0.5,6V0.5H500.5V6"></path><g class="tick" opacity="1" transform="translate(11.164693670949923,0)"><line stroke="currentColor" y2="6"></line><text fill="currentColor" y="9" dy="0.71em">Tue 29</text></g></g></svg>
```

reproduces it also. the main problem is no color is defined so canvg doesn't know where to grab the `currentColor` from. if you, for example, add `style="color: red;"` to the `<svg>` tag, it starts working. i'll reopen this as an issue that somebody can make a PR for at some time by reading the current color off the parent element or something.

**Comment by sabriozer33** [comment]
thanks for the support.
adding `.style('color', 'black');` to the parent of axis resolved the problem

**Comment by sabriozer33** [comment]
FYI
I have experienced similar problem with text-tags too. They disappeared (more truly, their colors are white) when I set ignoreClear option true, hence I changed the background color of canvas to white by doing that.

**Comment by gabelerner** [comment]
moving to https://github.com/canvg/canvg/issues/671 for `currentColor` support
