### ISSUE TITLE
SVG use elements fail with forward references

### ISSUE THREAD

**Issue by yGuy** [canvg/canvg#694]
It seems <use> elements may only reference elements that come before the use has been declared, which is against the spec and breaks many SVGs

At the time the definitions are looked up in the "use" rendering code, not all elements have been collected and the reference becomes undefined resulting in the use not rendering.
I have only skimmed briefly through the code, but I guess the issue is this line:
https://github.com/canvg/canvg/blob/a98c42da5755d5f6296f6b38e82d9083919fc50c/src/canvg.js#L3498
I assume that line should not be evaluated at initialization time when not all elements have been collected, yet, but rather at "render" time, when it actually resolves to a value.

You can find a complete test-case, here: http://jsfiddle.net/w6aft4hd/8/

It uses this SVG:
```xml
<svg xmlns="http://www.w3.org/2000/svg">
  <defs>
    <rect id="item1" fill="red" width="10" height="10"/>
  </defs>
  <use href="#item1"/>
  <use href="#item2"/>
  <defs>
    <rect id="item2" fill="green" width="10" height="10"/>
  </defs>
</svg>
```

The image should show a green rectangle, however it shows a red one (which should be hidden behind the green one). Moving the second use element behind the definition of the the second item works around the bug.

**Comment by gabelerner** [comment]
accepted as a bug. i parse the xml depth first so it only knows about the `item1` definition when it reaches the `use` tags and then later picks up the `item2` definition. whoever fixes it can do a 2 pass, one looking for `defs` and another actually rendering.
