### ISSUE TITLE
Print c3 chart in IE

### ISSUE THREAD

**Issue by PreetiDileep** [canvg/canvg#695]
I am trying to print kendo chart using html2canvas , but seems like it supports only chrome. Please suggest a proper way to print the charts so that it works well in all browsers.
 
PagePrint(): void {
      
        ES6Promise.polyfill(); 
        //this.svgToCanvas(document.getElementById("capture"));
        html2canvas(document.getElementById("capture")).then(canvas => {
                let popupWin;    
                popupWin = window.open('', '_blank', 'top=0,left=0,height=auto,width=auto');
                popupWin.document.open();
                var dataUrl = canvas.toDataURL('image/jpeg', 1.0);
                let windowContent = '<!DOCTYPE html>';
                windowContent += '<html>';
                windowContent += '<head><title>Print Report</title></head>';
                windowContent += '<body onload="window.print();window.close()">';
                windowContent += '<img src="' + dataUrl + '">';
                windowContent += '</body>';
                windowContent += '</html>';
                popupWin.document.write(windowContent);
                popupWin.document.close();
              
        });
    }

**Comment by gabelerner** [comment]
this is `canvg`, not `html2canvas` ... please move the issue there
