### ISSUE TITLE
broken filters

### ISSUE THREAD

**Issue by gabelerner** [canvg/canvg#696]
no filter, works:
```svg
<svg width="300px" height="200px">
  <defs>
    <filter id="testfilter">
      <feColorMatrix type="hueRotate"
        values="180"></feColorMatrix>
    </filter>
  </defs>
  <g fill="#67b7dc">
    <path d="M150 0 L75 200 L225 200 Z" />
  </g>
</svg>
```
![image](https://user-images.githubusercontent.com/241819/55241778-d5672200-5209-11e9-93f2-8c9d3eecfbed.png)

color rotate doesn't have correct color
```svg
<svg width="300px" height="200px">
  <defs>
    <filter id="testfilter">
      <feColorMatrix type="hueRotate"
        values="180"></feColorMatrix>
    </filter>
  </defs>
  <g fill="#67b7dc" filter="url('#testfilter')">
    <path d="M150 0 L75 200 L225 200 Z" />
  </g>
</svg>
```
![image](https://user-images.githubusercontent.com/241819/55241814-ea43b580-5209-11e9-90a5-2c3550ddc24d.png)

also broken when destination width/height = 0

**Comment by dangreen** [comment]
@gabelerner 

<img width="1049" alt="Снимок экрана 2020-10-17 в 14 15 07" src="https://user-images.githubusercontent.com/986756/96330865-2ad08180-1083-11eb-820a-d6435bbb10aa.png">
<img width="1054" alt="Снимок экрана 2020-10-17 в 14 15 28" src="https://user-images.githubusercontent.com/986756/96330873-37ed7080-1083-11eb-8bb2-1c947f3c2129.png">
<img width="1046" alt="Снимок экрана 2020-10-17 в 14 15 47" src="https://user-images.githubusercontent.com/986756/96330899-420f6f00-1083-11eb-86b9-65933ba7503b.png">
<img width="1040" alt="Снимок экрана 2020-10-17 в 14 16 14" src="https://user-images.githubusercontent.com/986756/96330930-52274e80-1083-11eb-9016-369c59b0d6be.png">

**Comment by gabelerner** [comment]
it's still not 1 to 1 perfect but it's closer than original issue which was way off. we can close due to the algorithms for colors being opinionated.
