### ISSUE TITLE
Font is not parsed correctly when font attributes are not explicitly defined

### ISSUE THREAD

**Issue by fargyriou** [canvg/canvg#702]
We noticed that font is not correctly parsed when the font attributes are not explicitly defined in a <g> element. For example like: style="font: 40px Tahoma, Verdana, sans-serif;". In this case, the font is returned as undefined when the children are rendered and the browser's default style is set instead.

Try this svg:
```
<svg xmlns="http://www.w3.org/2000/svg" width="200" height="30" viewBox="0 0 100 30">
  <g style="font: 40px Tahoma, Verdana, sans-serif;" transform="translate(20 0)">
    <text dy="1em" stroke="rgb(94,103,130)" stroke-width="7px" stroke-linejoin="round" text-anchor="middle" transform="translate(50 0)">My template Label</text>
    <text dy="1em" fill="rgb(229,233,240)" text-anchor="middle" transform="translate(50 0)">My template Label</text>
  </g>
</svg>
```

**Comment by fargyriou** [comment]
The same also happens if some font attributes are missing. For example, if only font-size is defined.

**Comment by gabelerner** [comment]
i agree this is broken. `font-size: 20px` works on its own. also `font-family: Tahoma, Verdana, sans-serif; font-size: 20px;` works. but `font` on its own does not. would need to update https://github.com/canvg/canvg/blob/master/src/canvg.js#L1099 to handle `font` on its own.

**Comment by HackbrettXXX** [comment]
The function at [L498](https://github.com/canvg/canvg/blob/master/src/canvg.js#L498) is also broken.
