### ISSUE TITLE
canvg returns black area

### ISSUE THREAD

**Issue by sunildipun** [canvg/canvg#703]
canvg.toDataUrl return a black rectangle area. with x axis label

**Comment by gabelerner** [comment]
Please provide your full svg string so that I could debug.

**Comment by sunildipun** [comment]
@gabelerner 
data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iOTAwIiBoZWlnaHQ9IjQwMCI+PGcgdHJhbnNmb3JtPSJ0cmFuc2xhdGUoNDAsNjApIj48cGF0aCBjbGFzcz0ibGluZSByYXRpby1saW5lIiBzdHlsZT0iZmlsbDogbm9uZTsiIGQ9Ik04MjAsMTA1LjU3TDc5Mi42NjY2NjY2NjY2NjY2LDEwNS42TDc2OC4wNjY2NjY2NjY2NjY2LDEwNS42TDc0MC43MzMzMzMzMzMzMzMzLDEwNS42M0w3MTMuNCwxMDUuNjNMNjg2LjA2NjY2NjY2NjY2NjcsMTA1LjY2TDY1OC43MzMzMzMzMzMzMzMzLDEwNS42Nkw2MzEuNCwxMDUuNjkwMDAwMDAwMDAwMDNMNjAxLjMzMzMzMzMzMzMzMzMsMTA1LjcxOTk5OTk5OTk5OTk3TDU3NCwxMDUuNzE5OTk5OTk5OTk5OTdMNTQ2LjY2NjY2NjY2NjY2NjYsMTA1Ljc1TDUxOS4zMzMzMzMzMzMzMzMzLDEwNS43NUw0OTQuNzMzMzMzMzMzMzMzNCwxMDUuNzhMNDY3LjQsMTA1LjgxTDQ0MC4wNjY2NjY2NjY2NjY2LDEwNS44MUw0MTIuNzMzMzMzMzMzMzMzMywxMDUuODRMMzg1LjQsMTA1Ljg0TDM1NS4zMzMzMzMzMzMzMzMzNywxMDUuODcwMDAwMDAwMDAwMDNMMzI4LDEwNS45TDMwMC42NjY2NjY2NjY2NjY2MywxMDUuOUwyNzMuMzMzMzMzMzMzMzMzMywxMDUuOTI5OTk5OTk5OTk5OThMMjQ2LDEwNS45Mjk5OTk5OTk5OTk5OEwyMjEuNCwxMDUuOTU5OTk5OTk5OTk5OThMMTk0LjA2NjY2NjY2NjY2NjY2LDEwNS45NTk5OTk5OTk5OTk5OEwxNjYuNzMzMzMzMzMzMzMzMzUsMTA1Ljk4OTk5OTk5OTk5OTk4TDEzNi42NjY2NjY2NjY2NjY2NiwxMDYuMDIwMDAwMDAwMDAwMDFMMTA5LjMzMzMzMzMzMzMzMzMzLDEwNi4wMjAwMDAwMDAwMDAwMUw4MiwxMDYuMDQ5OTk5OTk5OTk5OThMNTQuNjY2NjY2NjY2NjY2NjY0LDEwNi4wNDk5OTk5OTk5OTk5OEwyNy4zMzMzMzMzMzMzMzMzMzIsMTA2LjA4MDAwMDAwMDAwMDAxTDAsMTA2LjExMDAwMDAwMDAwMDAxIj48Y2lyY2xlPjwvY2lyY2xlPjxjaXJjbGU+PC9jaXJjbGU+PGNpcmNsZT48L2NpcmNsZT48Y2lyY2xlPjwvY2lyY2xlPjxjaXJjbGU+PC9jaXJjbGU+PC9wYXRoPjxwYXRoIGNsYXNzPSJsaW5lIGxhbi1saW5lIiBzdHlsZT0iZmlsbDogbm9uZTsiIGQ9Ik04MjAsMjI1TDc5Mi42NjY2NjY2NjY2NjY2LDIyNUw3NjguMDY2NjY2NjY2NjY2NiwyMjVMNzQwLjczMzMzMzMzMzMzMzMsMjI1TDcxMy40LDIyNUw2ODYuMDY2NjY2NjY2NjY2NywyMjVMNjU4LjczMzMzMzMzMzMzMzMsMjI1TDYzMS40LDIyNUw2MDEuMzMzMzMzMzMzMzMzMywyMjVMNTc0LDIyNUw1NDYuNjY2NjY2NjY2NjY2NiwyMjVMNTE5LjMzMzMzMzMzMzMzMzMsMjI1TDQ5NC43MzMzMzMzMzMzMzM0LDIyNUw0NjcuNCwyMjVMNDQwLjA2NjY2NjY2NjY2NjYsMjI1TDQxMi43MzMzMzMzMzMzMzMzLDIyNUwzODUuNCwyMjVMMzU1LjMzMzMzMzMzMzMzMzM3LDIyNUwzMjgsMjI1TDMwMC42NjY2NjY2NjY2NjY2MywyMjVMMjczLjMzMzMzMzMzMzMzMzMsMjI1TDI0NiwyMjVMMjIxLjQsMjI1TDE5NC4wNjY2NjY2NjY2NjY2NiwyMjVMMTY2LjczMzMzMzMzMzMzMzM1LDIyNUwxMzYuNjY2NjY2NjY2NjY2NjYsMjI1TDEwOS4zMzMzMzMzMzMzMzMzMywyMjVMODIsMjI1TDU0LjY2NjY2NjY2NjY2NjY2NCwyMjVMMjcuMzMzMzMzMzMzMzMzMzMyLDIyNUwwLDIyNSI+PGNpcmNsZSBjbGFzcz0ibGFuLXByb2dyZXNzIiByPSI1IiBzdHlsZT0iZmlsbDogcmVkOyI+PC9jaXJjbGU+PC9wYXRoPjxwYXRoIGNsYXNzPSJsaW5lIHdhbi1saW5lIiBzdHlsZT0iZmlsbDogbm9uZTsiIGQ9Ik04MjAsMEw3OTIuNjY2NjY2NjY2NjY2NiwwTDc2OC4wNjY2NjY2NjY2NjY2LDBMNzQwLjczMzMzMzMzMzMzMzMsMEw3MTMuNCwwTDY4Ni4wNjY2NjY2NjY2NjY3LDBMNjU4LjczMzMzMzMzMzMzMzMsMEw2MzEuNCwwTDYwMS4zMzMzMzMzMzMzMzMzLDBMNTc0LDBMNTQ2LjY2NjY2NjY2NjY2NjYsMEw1MTkuMzMzMzMzMzMzMzMzMywwTDQ5NC43MzMzMzMzMzMzMzM0LDBMNDY3LjQsMEw0NDAuMDY2NjY2NjY2NjY2NiwwTDQxMi43MzMzMzMzMzMzMzMzLDBMMzg1LjQsMEwzNTUuMzMzMzMzMzMzMzMzMzcsMEwzMjgsMEwzMDAuNjY2NjY2NjY2NjY2NjMsMEwyNzMuMzMzMzMzMzMzMzMzMywwTDI0NiwwTDIyMS40LDBMMTk0LjA2NjY2NjY2NjY2NjY2LDBMMTY2LjczMzMzMzMzMzMzMzM1LDBMMTM2LjY2NjY2NjY2NjY2NjY2LDBMMTA5LjMzMzMzMzMzMzMzMzMzLDBMODIsMEw1NC42NjY2NjY2NjY2NjY2NjQsMEwyNy4zMzMzMzMzMzMzMzMzMzIsMEwwLDI1Ij48L3BhdGg+PGcgY2xhc3M9IngtYXhpcyIgdHJhbnNmb3JtPSJ0cmFuc2xhdGUoMCwzMDApIiBmaWxsPSJub25lIiBmb250LXNpemU9IjEwIiBmb250LWZhbWlseT0ic2Fucy1zZXJpZiIgdGV4dC1hbmNob3I9Im1pZGRsZSI+PHBhdGggY2xhc3M9ImRvbWFpbiIgc3Ryb2tlPSJjdXJyZW50Q29sb3IiIGQ9Ik0wLjUsNlYwLjVIODIwLjVWNiI+PC9wYXRoPjxnIGNsYXNzPSJ0aWNrIiBvcGFjaXR5PSIxIiB0cmFuc2Zvcm09InRyYW5zbGF0ZSgzOC43NjY2NjY2NjY2NjY2NjYsMCkiPjxsaW5lIHN0cm9rZT0iY3VycmVudENvbG9yIiB5Mj0iNiI+PC9saW5lPjx0ZXh0IGZpbGw9ImN1cnJlbnRDb2xvciIgeT0iOSIgZHk9IjAuNzFlbSI+IDY6MDIgQU0gNC8xOS8xOTwvdGV4dD48L2c+PGcgY2xhc3M9InRpY2siIG9wYWNpdHk9IjEiIHRyYW5zZm9ybT0idHJhbnNsYXRlKDEyMC43NjY2NjY2NjY2NjY2NywwKSI+PGxpbmUgc3Ryb2tlPSJjdXJyZW50Q29sb3IiIHkyPSI2Ij48L2xpbmU+PHRleHQgZmlsbD0iY3VycmVudENvbG9yIiB5PSI5IiBkeT0iMC43MWVtIj42OjAyIEFNPC90ZXh0PjwvZz48ZyBjbGFzcz0idGljayIgb3BhY2l0eT0iMSIgdHJhbnNmb3JtPSJ0cmFuc2xhdGUoMjAyLjc2NjY2NjY2NjY2NjY4LDApIj48bGluZSBzdHJva2U9ImN1cnJlbnRDb2xvciIgeTI9IjYiPjwvbGluZT48dGV4dCBmaWxsPSJjdXJyZW50Q29sb3IiIHk9IjkiIGR5PSIwLjcxZW0iPjY6MDMgQU08L3RleHQ+PC9nPjxnIGNsYXNzPSJ0aWNrIiBvcGFjaXR5PSIxIiB0cmFuc2Zvcm09InRyYW5zbGF0ZSgyODQuNzY2NjY2NjY2NjY2NjUsMCkiPjxsaW5lIHN0cm9rZT0iY3VycmVudENvbG9yIiB5Mj0iNiI+PC9saW5lPjx0ZXh0IGZpbGw9ImN1cnJlbnRDb2xvciIgeT0iOSIgZHk9IjAuNzFlbSI+NjowMyBBTTwvdGV4dD48L2c+PGcgY2xhc3M9InRpY2siIG9wYWNpdHk9IjEiIHRyYW5zZm9ybT0idHJhbnNsYXRlKDM2Ni43NjY2NjY2NjY2NjY2NSwwKSI+PGxpbmUgc3Ryb2tlPSJjdXJyZW50Q29sb3IiIHkyPSI2Ij48L2xpbmU+PHRleHQgZmlsbD0iY3VycmVudENvbG9yIiB5PSI5IiBkeT0iMC43MWVtIj42OjA0IEFNPC90ZXh0PjwvZz48ZyBjbGFzcz0idGljayIgb3BhY2l0eT0iMSIgdHJhbnNmb3JtPSJ0cmFuc2xhdGUoNDQ4Ljc2NjY2NjY2NjY2NjY1LDApIj48bGluZSBzdHJva2U9ImN1cnJlbnRDb2xvciIgeTI9IjYiPjwvbGluZT48dGV4dCBmaWxsPSJjdXJyZW50Q29sb3IiIHk9IjkiIGR5PSIwLjcxZW0iPjY6MDQgQU08L3RleHQ+PC9nPjxnIGNsYXNzPSJ0aWNrIiBvcGFjaXR5PSIxIiB0cmFuc2Zvcm09InRyYW5zbGF0ZSg1MzAuNzY2NjY2NjY2NjY2NywwKSI+PGxpbmUgc3Ryb2tlPSJjdXJyZW50Q29sb3IiIHkyPSI2Ij48L2xpbmU+PHRleHQgZmlsbD0iY3VycmVudENvbG9yIiB5PSI5IiBkeT0iMC43MWVtIj42OjA1IEFNPC90ZXh0PjwvZz48ZyBjbGFzcz0idGljayIgb3BhY2l0eT0iMSIgdHJhbnNmb3JtPSJ0cmFuc2xhdGUoNjEyLjc2NjY2NjY2NjY2NjcsMCkiPjxsaW5lIHN0cm9rZT0iY3VycmVudENvbG9yIiB5Mj0iNiI+PC9saW5lPjx0ZXh0IGZpbGw9ImN1cnJlbnRDb2xvciIgeT0iOSIgZHk9IjAuNzFlbSI+NjowNSBBTTwvdGV4dD48L2c+PGcgY2xhc3M9InRpY2siIG9wYWNpdHk9IjEiIHRyYW5zZm9ybT0idHJhbnNsYXRlKDY5NC43NjY2NjY2NjY2NjY3LDApIj48bGluZSBzdHJva2U9ImN1cnJlbnRDb2xvciIgeTI9IjYiPjwvbGluZT48dGV4dCBmaWxsPSJjdXJyZW50Q29sb3IiIHk9IjkiIGR5PSIwLjcxZW0iPjY6MDYgQU08L3RleHQ+PC9nPjxnIGNsYXNzPSJ0aWNrIiBvcGFjaXR5PSIxIiB0cmFuc2Zvcm09InRyYW5zbGF0ZSg3NzYuNzY2NjY2NjY2NjY2NywwKSI+PGxpbmUgc3Ryb2tlPSJjdXJyZW50Q29sb3IiIHkyPSI2Ij48L2xpbmU+PHRleHQgZmlsbD0iY3VycmVudENvbG9yIiB5PSI5IiBkeT0iMC43MWVtIj4gNjowNiBBTSA0LzE5LzE5PC90ZXh0PjwvZz48L2c+PHRleHQgdHJhbnNmb3JtPSJ0cmFuc2xhdGUoNDEwICwzNDApIiBzdHlsZT0idGV4dC1hbmNob3I6IG1pZGRsZTsiPlRpbWU8L3RleHQ+PGcgY2xhc3M9Indhbi1sYW4tYXhpcyIgZmlsbD0ibm9uZSIgZm9udC1zaXplPSIxMCIgZm9udC1mYW1pbHk9InNhbnMtc2VyaWYiIHRleHQtYW5jaG9yPSJlbmQiPjxnIGNsYXNzPSJ0aWNrIiBvcGFjaXR5PSIxIiB0cmFuc2Zvcm09InRyYW5zbGF0ZSgwLDMwMC41KSI+PGxpbmUgc3Ryb2tlPSJjdXJyZW50Q29sb3IiIHgyPSI4MjAiPjwvbGluZT48dGV4dCBmaWxsPSJjdXJyZW50Q29sb3IiIHg9Ii0zIiBkeT0iMC4zMmVtIj4wS2JwczwvdGV4dD48L2c+PGcgY2xhc3M9InRpY2siIG9wYWNpdHk9IjEiIHRyYW5zZm9ybT0idHJhbnNsYXRlKDAsMjUwLjUpIj48bGluZSBzdHJva2U9ImN1cnJlbnRDb2xvciIgeDI9IjgyMCI+PC9saW5lPjx0ZXh0IGZpbGw9ImN1cnJlbnRDb2xvciIgeD0iLTMiIGR5PSIwLjMyZW0iPjJLYnBzPC90ZXh0PjwvZz48ZyBjbGFzcz0idGljayIgb3BhY2l0eT0iMSIgdHJhbnNmb3JtPSJ0cmFuc2xhdGUoMCwyMDAuNSkiPjxsaW5lIHN0cm9rZT0iY3VycmVudENvbG9yIiB4Mj0iODIwIj48L2xpbmU+PHRleHQgZmlsbD0iY3VycmVudENvbG9yIiB4PSItMyIgZHk9IjAuMzJlbSI+NEticHM8L3RleHQ+PC9nPjxnIGNsYXNzPSJ0aWNrIiBvcGFjaXR5PSIxIiB0cmFuc2Zvcm09InRyYW5zbGF0ZSgwLDE1MC41KSI+PGxpbmUgc3Ryb2tlPSJjdXJyZW50Q29sb3IiIHgyPSI4MjAiPjwvbGluZT48dGV4dCBmaWxsPSJjdXJyZW50Q29sb3IiIHg9Ii0zIiBkeT0iMC4zMmVtIj42S2JwczwvdGV4dD48L2c+PGcgY2xhc3M9InRpY2siIG9wYWNpdHk9IjEiIHRyYW5zZm9ybT0idHJhbnNsYXRlKDAsMTAwLjUpIj48bGluZSBzdHJva2U9ImN1cnJlbnRDb2xvciIgeDI9IjgyMCI+PC9saW5lPjx0ZXh0IGZpbGw9ImN1cnJlbnRDb2xvciIgeD0iLTMiIGR5PSIwLjMyZW0iPjhLYnBzPC90ZXh0PjwvZz48ZyBjbGFzcz0idGljayIgb3BhY2l0eT0iMSIgdHJhbnNmb3JtPSJ0cmFuc2xhdGUoMCw1MC41KSI+PGxpbmUgc3Ryb2tlPSJjdXJyZW50Q29sb3IiIHgyPSI4MjAiPjwvbGluZT48dGV4dCBmaWxsPSJjdXJyZW50Q29sb3IiIHg9Ii0zIiBkeT0iMC4zMmVtIj4xMEticHM8L3RleHQ+PC9nPjxnIGNsYXNzPSJ0aWNrIiBvcGFjaXR5PSIxIiB0cmFuc2Zvcm09InRyYW5zbGF0ZSgwLDAuNSkiPjxsaW5lIHN0cm9rZT0iY3VycmVudENvbG9yIiB4Mj0iODIwIj48L2xpbmU+PHRleHQgZmlsbD0iY3VycmVudENvbG9yIiB4PSItMyIgZHk9IjAuMzJlbSI+MTJLYnBzPC90ZXh0PjwvZz48L2c+PGcgY2xhc3M9ImdyaWQiIGZpbGw9Im5vbmUiIGZvbnQtc2l6ZT0iMTAiIGZvbnQtZmFtaWx5PSJzYW5zLXNlcmlmIiB0ZXh0LWFuY2hvcj0iZW5kIj48cGF0aCBjbGFzcz0iZG9tYWluIiBzdHJva2U9ImN1cnJlbnRDb2xvciIgZD0iTTgyMCwzMDAuNUgwLjVWMC41SDgyMCI+PC9wYXRoPjwvZz48ZyBjbGFzcz0icmF0aW8tYXhpcyIgdHJhbnNmb3JtPSJ0cmFuc2xhdGUoODIwICwgMCkiIGZpbGw9Im5vbmUiIGZvbnQtc2l6ZT0iMTAiIGZvbnQtZmFtaWx5PSJzYW5zLXNlcmlmIiB0ZXh0LWFuY2hvcj0ic3RhcnQiPjxnIGNsYXNzPSJ0aWNrIiBvcGFjaXR5PSIxIiB0cmFuc2Zvcm09InRyYW5zbGF0ZSgwLDMwMC41KSI+PGxpbmUgc3Ryb2tlPSJjdXJyZW50Q29sb3IiIHgyPSI2Ij48L2xpbmU+PHRleHQgZmlsbD0iY3VycmVudENvbG9yIiB4PSI5IiBkeT0iMC4zMmVtIj4wJTwvdGV4dD48L2c+PGcgY2xhc3M9InRpY2siIG9wYWNpdHk9IjEiIHRyYW5zZm9ybT0idHJhbnNsYXRlKDAsMjQwLjUpIj48bGluZSBzdHJva2U9ImN1cnJlbnRDb2xvciIgeDI9IjYiPjwvbGluZT48dGV4dCBmaWxsPSJjdXJyZW50Q29sb3IiIHg9IjkiIGR5PSIwLjMyZW0iPjIwJTwvdGV4dD48L2c+PGcgY2xhc3M9InRpY2siIG9wYWNpdHk9IjEiIHRyYW5zZm9ybT0idHJhbnNsYXRlKDAsMTgwLjUpIj48bGluZSBzdHJva2U9ImN1cnJlbnRDb2xvciIgeDI9IjYiPjwvbGluZT48dGV4dCBmaWxsPSJjdXJyZW50Q29sb3IiIHg9IjkiIGR5PSIwLjMyZW0iPjQwJTwvdGV4dD48L2c+PGcgY2xhc3M9InRpY2siIG9wYWNpdHk9IjEiIHRyYW5zZm9ybT0idHJhbnNsYXRlKDAsMTIwLjUpIj48bGluZSBzdHJva2U9ImN1cnJlbnRDb2xvciIgeDI9IjYiPjwvbGluZT48dGV4dCBmaWxsPSJjdXJyZW50Q29sb3IiIHg9IjkiIGR5PSIwLjMyZW0iPjYwJTwvdGV4dD48L2c+PGcgY2xhc3M9InRpY2siIG9wYWNpdHk9IjEiIHRyYW5zZm9ybT0idHJhbnNsYXRlKDAsNjAuNSkiPjxsaW5lIHN0cm9rZT0iY3VycmVudENvbG9yIiB4Mj0iNiI+PC9saW5lPjx0ZXh0IGZpbGw9ImN1cnJlbnRDb2xvciIgeD0iOSIgZHk9IjAuMzJlbSI+ODAlPC90ZXh0PjwvZz48ZyBjbGFzcz0idGljayIgb3BhY2l0eT0iMSIgdHJhbnNmb3JtPSJ0cmFuc2xhdGUoMCwwLjUpIj48bGluZSBzdHJva2U9ImN1cnJlbnRDb2xvciIgeDI9IjYiPjwvbGluZT48dGV4dCBmaWxsPSJjdXJyZW50Q29sb3IiIHg9IjkiIGR5PSIwLjMyZW0iPjEwMCU8L3RleHQ+PC9nPjwvZz48bGluZSBjbGFzcz0iYmlzZWN0b3ItbGluZSIgc3Ryb2tlPSIjY2NjIiB4MT0iNTc0IiB4Mj0iNTc0IiB5MT0iMCIgeTI9IjMwMCIgc3R5bGU9ImRpc3BsYXk6IG5vbmU7Ij48L2xpbmU+PGNpcmNsZSBjbGFzcz0ibGFuLXZhbHVlIiByPSIzIiBjeD0iNTc0IiBjeT0iMjI1IiBzdHlsZT0iZGlzcGxheTogbm9uZTsiPjwvY2lyY2xlPjxjaXJjbGUgY2xhc3M9Indhbi12YWx1ZSIgcj0iMyIgY3g9IjU3NCIgY3k9IjAiIHN0eWxlPSJkaXNwbGF5OiBub25lOyI+PC9jaXJjbGU+PGNpcmNsZSBjbGFzcz0icmF0aW8tdmFsdWUiIHI9IjMiIGN4PSI1NzQiIGN5PSIxMDUuNzE5OTk5OTk5OTk5OTciIHN0eWxlPSJkaXNwbGF5OiBub25lOyI+PC9jaXJjbGU+PGcgY2xhc3M9ImhvdmVyLWdyb3VwIj48L2c+PHJlY3QgY2xhc3M9Im1vdXNlLW92ZXItcmVjdCIgd2lkdGg9IjgyMCIgaGVpZ2h0PSIzMDAiPjwvcmVjdD48L2c+PC9zdmc+

This is the svg string 
returning me black area

**Comment by gabelerner** [comment]
the axes aren't displaying because you're using `currentColor` and canvg will not look outside the svg to determine what this is. here's a proposed fix: https://github.com/canvg/canvg/issues/685#issuecomment-468167975

the black box appears on all svg renderers including chrome. that's just a problem in your svg.

moving to #671 for `currentColor` support
