### ISSUE TITLE
Publish on bower

### ISSUE THREAD

**Issue by preraksola** [canvg/canvg#704]
Can you please publish the package on bower as well?
Thank you.

**Comment by brettz9** [comment]
I would advise against this. People have generally moved to npm and I think we should encourage that. Bower's own site says, "While Bower is maintained, we recommend using Yarn and Webpack or Parcel for front-end projects read how to migrate!"

**Comment by gabelerner** [comment]
i'm in agreement here, `bower` is considered deprecated for `canvg`. feel free to publish your own versions there if you think it's worthwhile, i won't mind, just don't call it the official one.
