### ISSUE TITLE
SVG Group scale 0 not applied

### ISSUE THREAD

**Issue by SmythConor** [canvg/canvg#713]
Hello,

I have an issue where a circle tag inside a group tag gets rendered on the canvas if the group scaling is set to 0, which shouldn't render anything inside the group.

Here's a sample I've come up with to demonstrate:
```
<html>
<head>
	<meta http-equiv="X-UA-Compatible" content="IE=edge" />
	<title>SVG Group Scaling</title>
	<!-- Required to convert named colors to RGB -->
	<script src="https://cdn.jsdelivr.net/npm/rgbcolor@^1/index.js"></script>
	<!-- Optional if you want blur -->
	<script src="https://cdn.jsdelivr.net/npm/stackblur-canvas@^1/dist/stackblur.min.js"></script>
	<!-- Main canvg code -->
	<script src="https://cdn.jsdelivr.net/npm/canvg/dist/browser/canvg.js"></script>
</head>
<body>
	<canvas id="canvas" width="200px" height="200px"></canvas>
	<svg id="svg" style="left: 500px; top: 0px">
		<g transform="scale(0 0)" fill="#b6d957">
			<circle cx="6" cy="6" r="5"></circle>
		</g>
	</svg>
	<script type="text/javascript">
		const svg =
			'<svg id="svg" style="left: 500px; top: 0px"><g transform="scale(0 0)" fill="#b6d957"><circle cx="6" cy="6" r="5"></circle></g></svg>';

		const ctx = document.getElementById('canvas').getContext('2d');
		ctx.drawSvg(svg, 0, 0, 20, 20);
	</script>
</body>
</html>
```

The canvas is rendered with the circle and the svg shows renders nothing, as I would expect.

**Comment by SmythConor** [comment]
I cloned and built a copy of canvg to try the fix, it doesn't seem to be working for me.

Ran a `npm run build` and took the browser copy of `canvg.js`

**Comment by gabelerner** [comment]
whoops i remember that my PR only fixed part of the issue and i was waiting to do the 2nd part. will reopen for somebody to attack what's left.

**Comment by dangreen** [comment]
@gabelerner 

<img width="1050" alt="Снимок экрана 2020-10-17 в 14 13 04" src="https://user-images.githubusercontent.com/986756/96330841-e0e79b80-1082-11eb-90f9-54286df96fcb.png">

😀

**Comment by gabelerner** [comment]
yup seems fixed! blank==blank

**Comment by SmythConor** [comment]
Just as a matter of interest, which merge fixed this?

**Comment by dangreen** [comment]
@SmythConor https://github.com/canvg/canvg/commit/7e0178901de58c95880961cab72a123f769604b0#diff-5828068395ce2da80ec845eeab2f5ad14f910caaa2c1cb6d5e8fd5f48ba6b898
