### ISSUE TITLE
Viewbox ignored when positioning markers

### ISSUE THREAD

**Issue by cooljingle** [canvg/canvg#719]
Markers with a viewbox are misaligned.

e.g.
`<svg width="500" height="500">
    <g>
        <g style="stroke: rgb(153, 153, 153); stroke-width: 2px;">
            <polyline marker-mid="url(#arrow)" points="100,200 200,150 300,100"/>
        </g>
    </g>
    <defs>
        <marker id="arrow" viewBox="0 -5 6 10" markerWidth="6" markerHeight="10" orient="auto">
            <path d="M1,-5L6,0L1,5L0,4L4,0L0,-4" style="fill: rgb(35, 153, 196)">
            </path>
        </marker>
    </defs>
</svg>`

![image](https://user-images.githubusercontent.com/7450155/60185154-016f5f00-985c-11e9-9142-14a04dce1f89.png)

**Comment by dangreen** [comment]
@gabelerner outdated issue

<img width="1080" alt="Снимок экрана 2020-10-17 в 13 37 34" src="https://user-images.githubusercontent.com/986756/96330229-ebebfd00-107d-11eb-9500-348762022f2d.png">

**Comment by gabelerner** [comment]
agreed! closing this. we can also bisect to find the exact PR that fixed at some point if we want a good history.

**Comment by dangreen** [comment]
Maybe it was https://github.com/canvg/canvg/pull/784
