### ISSUE TITLE
Module is not defined when using rgbcolor on browser

### ISSUE THREAD

**Issue by Luis-Palacios** [canvg/canvg#720]
Hello,

I'm trying to use canvg on the browser simply by adding it directly on the web page as the instructions suggest on the readme I add the scripts reference:

```html
<script src="https://cdn.jsdelivr.net/npm/rgbcolor@^1/index.js"></script>
<script src="https://cdn.jsdelivr.net/npm/canvg/dist/browser/canvg.min.js"></script>
```

but when the page load I get an error message saying: 
```
index.js:6 Uncaught ReferenceError: module is not defined
    at index.js:6
```
The index file refers to the rgbcolor file 
![image](https://user-images.githubusercontent.com/4844997/60207346-e1677d80-9812-11e9-8d5e-ffadea04c3cf.png)

Is there any work around for this?

Thank you

**Comment by gabelerner** [comment]
you can use `https://cdnjs.cloudflare.com/ajax/libs/canvg/1.4/rgbcolor.min.js` for now which is the old version.

@bz2 i think https://github.com/canvg/canvg/commit/2d75e00ff3a9914ba65e7f701559a8e939e91f58#diff-04c6e90faac2675aa89e2176d2eec7d8R62 messed it up since we started including a node module on the browser

**Comment by Luis-Palacios** [comment]
Thanks @gabelerner , I did find that link while looking at older versions of the README.md file, do you think it plays along nicely with the latest version of canvg? `https://cdn.jsdelivr.net/npm/canvg/dist/browser/canvg.min.js"` it seems to be

**Comment by gabelerner** [comment]
yea it'll play nice, at some point i'll just change the readme to point at that file again when i have time

**Comment by Luis-Palacios** [comment]
I created a pull request #722  in order to change it
