### ISSUE TITLE
Not working with OffscreenCanvas

### ISSUE THREAD

**Issue by mdnaserhassan** [canvg/canvg#723]
Created a OffscreenCanvas and pass into canvg function . It is not able load svg snippet in canvas.
var svg =$('svg')[0].outerHTML
var offscreen =OffscreenCanvas(width,height);
canvg(offscreen,svg);
https://developer.mozilla.org/en-US/docs/Web/API/OffscreenCanvas

**Comment by gabelerner** [comment]
can you provide a link to a jsfiddle/codepen example that's breaking?

**Comment by mdnaserhassan** [comment]
https://codepen.io/mdnaserhassan/project/editor/ZbBPRb

**Comment by mdnaserhassan** [comment]
It is working in main UI but when I am importing scripts in web worker then it is breaking

**Comment by gabelerner** [comment]
your codepen shows canvg isn't defined in the web worker. it seems like you're looking for something like https://developer.mozilla.org/en-US/docs/Web/API/WorkerGlobalScope/importScripts ... it's not specific to canvg as any other script would also fail in your web worker so i'm closing the issue.

**Comment by mdnaserhassan** [comment]
I had commented code where I was importing canvg in web worker. I am able to import other scripts but its failing only for canvg .  I have commented canvg import. check once more

**Comment by gabelerner** [comment]
are you able to debug it more? i see `uncaught null` in my chrome. maybe you can play with removing parts of canvg until it doesn't break? i just moved my family cross country so i don't have too much time to look into this at the moment but i'll reopen.

**Comment by dangreen** [comment]
@mdnaserhassan 
For now, where are no docs, but you can test new version here: https://www.npmjs.com/package/@flexis/canvg

Example: https://github.com/TrigenSoftware/flexis-canvg/blob/15b99d738fe113ab32b5b04ce22bb5c08a88c3bd/test/browser/index.js#L119-L135

😉

**Comment by dangreen** [comment]
@mdnaserhassan 

https://www.npmjs.com/package/canvg/v/3.0.0-beta.0
https://github.com/canvg/canvg#example

**Comment by dangreen** [comment]
@mdnaserhassan @gabelerner Can we close this issue?

**Comment by gabelerner** [comment]
I think so thanks to your work on 3.0. Please reopen with breaking examples if something doesn't work.
