### ISSUE TITLE
SAP UI5, canvg.js and bar chart (vizFrame charts in UI5)

### ISSUE THREAD

**Issue by falcon-code** [canvg/canvg#724]
I use software combination -  SAP UI5 1.52 (vizFrame charts in UI5), canvg.js and jsPDF.js. 

The reported error refers to an incorrect drawing of a bar chart with negative values.

The problem is described to in the following link (jsPDF issue #2494)
[https://github.com/MrRio/jsPDF/issues/2494](url)

My **SVG** document:
ziped SVG [SVG4.zip](https://github.com/canvg/canvg/files/3348542/SVG4.zip)
![image](https://user-images.githubusercontent.com/52439845/60488120-69310a00-9ca1-11e9-853d-78a27c6a0fdd.png)

After conversion to PNG:
![image](https://user-images.githubusercontent.com/52439845/60488136-764df900-9ca1-11e9-830b-4f437d8ef18e.png)

My controller:
`		onSavePDF: function() {
		
			var w = 2000, // or whatever your svg width is
				h = 700;
			var sSVG2 = document.getElementById("svg-01");
			var oCanvasHTML = document.createElement("canvas");

			var sSVG = sSVG2.outerHTML;

			oCanvasHTML.width = w;
			oCanvasHTML.height = h;

			var ctx = oCanvasHTML.getContext('2d');
			ctx.font = undefined;
			ctx.ignoreClearRect = true;
			ctx.fillStyle = '#ffffff';
			ctx.fillRect(0, 0, 2000, 600);

			canvg(oCanvasHTML, sSVG, {
				log: true,
				ignoreMouse: true,
				ignoreAnimation: true,
				ignoreDimensions: true,
				ignoreClear: true
			}); // add SVG content to Canvas

			var sImageData = oCanvasHTML.toDataURL("image/png");

			var oPDF = new jsPDF('l', 'pt', 'a2');

			oPDF.addImage(sImageData, "PNG", 15, 40, 1520, 540);
			oPDF.save("test.pdf");
		},`
If I run SVG converversions outside of SAP UI5 the result is correct.

I'm asking you to check the problem.

If you have any questions, please do not hesitate to contact me.

**Comment by dangreen** [comment]
@gabelerner 

<img width="1058" alt="Снимок экрана 2020-10-17 в 13 40 16" src="https://user-images.githubusercontent.com/986756/96330284-4d13d080-107e-11eb-9374-47e7f0ed0c31.png">

**Comment by gabelerner** [comment]
looks like it's been fixed
