### ISSUE TITLE
Add ability to turn off update interval from drawSvg

### ISSUE THREAD

**Issue by almercier** [canvg/canvg#726]
We are calling `drawSvg` but do not want or need the update interval. It makes detecting continuous loops/intervals bugs in our code by pausing the debugger much more difficult, and we really don't need the interval regardless as we are not using animations.

What I would like to request is either a new option that turns off the animation interval entirely that supersedes the `!nodeEnv || opts['enableRedraw']` condition, OR just return the svgRender from the call to canvg in `drawSvg` so we can call `stop()` on it.

We are currently doing the latter in a fork, but it would be nice to see something in the main repo to be able to do this. I could put up a PR for either, but I wasn't sure which solution would be preferred.

**Comment by dangreen** [comment]
@almercier Hi!

Is it still relevant problem for canvg v3?

**Comment by dangreen** [comment]
>  but none of my svgs are loading

Can you give an example of these svgs?

**Comment by almercier** [comment]
@dangreen Finally got around to an example. I think what's happening is that for some reason the svg is getting rendered way outside of the clipping bounds I'm drawing the svg in, so it ends up not getting shown....

Here's an example of an svg using Canvg.fromString in 3.0.9
https://jsfiddle.net/Mercieral/fhnwedpv/7/
![image](https://user-images.githubusercontent.com/30079507/149240140-eff220bc-2ac3-44e0-9a1f-ff577a04ca52.png)
```javascript
Canvg.fromString(context, arrowSVG, {
    offsetX: 0,
    offsetY: 0,
    scaleWidth: 50,
    scaleHeight: 100,
    ignoreMouse: true,
    ignoreAnimation: true,
    ignoreDimensions: true,
    ignoreClear: true,
});
```

and Here's an example of an svg using drawSvg in 2.0.0
http://jsfiddle.net/Mercieral/g0eraLy2/24/
![image](https://user-images.githubusercontent.com/30079507/149240115-e455eb4d-9a92-436f-8297-fec2d7e4f3f7.png)
```javascript
context.drawSvg(arrowSVG, 0, 0, 50, 100, {
    ignoreMouse: true,
    ignoreAnimation: true,
    ignoreDimensions: true,
    ignoreClear: true,
});
```

**Comment by almercier** [comment]
Moved this to its own item as it seems to be separate.
https://github.com/canvg/canvg/issues/1577

**Comment by almercier** [comment]
using `drawSvg` in 2.0.0 and `v.render` in v3 seems to prevent the update interval. So this ticket can be closed
