### ISSUE TITLE
How to retrieve javascript instructions instead of drawing?

### ISSUE THREAD

**Issue by meglio** [canvg/canvg#730]
I found one online tool doing that, but it uses an outdated version of `canvg`:

http://www.professorcloud.com/svg-to-canvas/

Is there an API to get JavaScript commands as an array of strings out without drawing on a canva?

If not, may you please help create such a jsfiddle?

**Comment by gabelerner** [comment]
there is no such api for this, you can go into the code and put print statements everywhere i call `ctx.` and collect the commands that way if that's your goal but it is something the library will not support
