### ISSUE TITLE
Add peerDependenciesMeta package property

### ISSUE THREAD

**Issue by dasa** [canvg/canvg#734]
Can the `peerDependencies` be marked as optional using the `peerDependenciesMeta` package property? This is available in Yarn and NPM 6.11: https://github.com/npm/cli/releases/tag/v6.11.0

**Comment by gabelerner** [comment]
They're needed in a node env but not in a browser env so not much I can do there. We can maybe at some point have a @canvg/browser and a @canvg/node package and I welcome PRs in that direction.

**Comment by dasa** [comment]
OK, I was hoping to avoid the peer dependency warnings that are shown.
