### ISSUE TITLE
While converting markers from SVG to canvas markers get disappeared

### ISSUE THREAD

**Issue by Bharat0103** [canvg/canvg#735]
when i want to convert svg to canvg markers get disappeared. 
also i have attached the screen shot and code for more clarification.
[sample.txt](https://github.com/canvg/canvg/files/3569197/sample.txt)

Please help me to solved the problem

thanks.
![Untitled](https://user-images.githubusercontent.com/54844605/64168961-51752e00-ce6a-11e9-8741-b07f66567761.png)

**Comment by dangreen** [comment]
@gabelerner I think need to publish next beta release with this fix.

**Comment by gabelerner-kernel** [comment]
https://www.npmjs.com/package/canvg/v/3.0.0-beta.3

**Comment by Bharat0103** [comment]
New Build is not working for me. see the attached screen shot
![Untitled](https://user-images.githubusercontent.com/54844605/68658250-1d4d7600-055b-11ea-869c-e5d463bd7d6f.png)

**Comment by dangreen** [comment]
@Bharat0103 Demo is not updated yet.

@gabelerner Can you please rebuild docs dir with new demo?

**Comment by Bharat0103** [comment]
how can i build docs dir?

**Comment by Bharat0103** [comment]
can you please do the build operation so that i can test it.

**Comment by gabelerner** [comment]
try now

**Comment by dangreen** [comment]
@Bharat0103 ?

**Comment by dangreen** [comment]
@Bharat0103 @gabelerner can we close this issue?
