### ISSUE TITLE
rendering multiple svgs

### ISSUE THREAD

**Issue by varunrayen** [canvg/canvg#738]
I am trying to render multiple svg's on a canvas. 
**For eg**: I have 3 svg elements, when I loop through the elements. 
when the second svg is render, it removes the first svg, 
when the third one renders, it removes the previous two svgs. 

Even though I have the `ignoreClear: true` option added

**Comment by gabelerner** [comment]
https://jsfiddle.net/cxs75t2k/1/ proves the option is working. please follow that.

**Comment by gabelerner** [comment]
if you remove width/height it works. i'll reopen for now if somebody wants to dig in.

**Comment by gonzofish** [comment]
I removed the height & width from the `svg2` in https://jsfiddle.net/varunrayen/6sjLxgzb/2/ and it rendered, but when I hovered over the compiled canvas the second shape disappears.

Seemed to happen if I removed height & width from the `svg1` too. Also if you swap their `canvg` calls, the square disappears on hover.

**Comment by gonzofish** [comment]
Passing `ignoreDimensions: true` seemed to fix it?

**Comment by Swordword** [comment]
I am trying to render multiple svg's by  document.createElement('canvas') , and it doesn't work

**Comment by Swordword** [comment]
[link](https://jsfiddle.net/zhangjianyu/breLqnta/6/)

**Comment by gabelerner** [comment]
```
svg1 = '<svg><text x="50" y="50">Hello</text></svg>';
svg2 = '<svg><text x="50" y="100">World</text></svg>';

var opts = {
  ignoreClear: true,
  ignoreDimensions: true,
  ignoreMouse: true,
}
let list = [svg1, svg2]
let container = document.getElementById('container')
const canvas = document.createElement('canvas')
canvas.width = 400;
canvas.height = 400;
const ctx = canvas.getContext('2d');
container.appendChild(canvas)
list.forEach(function(svg) {
  canvg(canvas, svg, opts);
})
```
works just fine from your example to render multiple svgs. if you have a problem w/ a specific SVG, please open another issue.
