### ISSUE TITLE
TypeScript error: type 'Canvas' not assignable to 'string | HTMLCanvasElement'

### ISSUE THREAD

**Issue by bewildergeist** [canvg/canvg#741]
Running `canvas@2.6.0, canvg@2.0.0, jsdom@15.1.1, xmldom@0.1.27` on `node@12.10.0`.

Not using `.ts` files (yet), but have TypeScript set up to compile JS files and report errors. 

Running basically this in `node`:

```
import canvg from 'canvg'
import { createCanvas } from 'canvas'

const canvas = createCanvas(200, 200)
canvg(canvas, /* SVG string */)
```

...reports this error:

```
error TS2345: Argument of type 'Canvas' is not assignable to parameter of type 'string | HTMLCanvasElement'.
  Type 'Canvas' is missing the following properties from type 'HTMLCanvasElement': toBlob, transferControlToOffscreen, addEventListener, removeEventListener, and 239 more.
```

Because the [`Canvas` class exported by `canvas`](https://github.com/Automattic/node-canvas/blob/master/types/index.d.ts#L56) does not conform to the `HTMLCanvasElement` interface, which is what [the `canvg` typings declare the `target` argument to be](https://github.com/canvg/canvg/blob/2996728168c94bbb56e3fb259d13857e427fad42/dist/node/canvg.d.ts#L21) (that, or a string):

```
declare function canvg(target?: string | HTMLCanvasElement, s?: string | Document, opts?: canvg.Options): void;
```

Is there a way (and is that the right solution?) to declare that the `target` argument can also be of type `Canvas`, by importing/referencing that type definition from `canvas`?

**Comment by gabelerner** [comment]
yea i guess i would have to generate different typings for browser vs. node ... right now you can just cast it to an HtmlCanvasElement before passing it in. these are all type checks that do nothing at runtime, or just tsignore/tslint ignore. if you want to open a PR that does the split of browser vs server typings, i'll review

**Comment by dangreen** [comment]
@gabelerner Due to v3 I think we can close it?

**Comment by gabelerner** [comment]
Yes! Should be fixed
