### ISSUE TITLE
Subscript/superscript

### ISSUE THREAD

**Issue by m55c55** [canvg/canvg#748]
First of all, thanks a lot for this great library! It works perfectly fine in general but I found an edge case that isn't handled properly.

`canvg` renders relative font-sizes and dy values differently compared to the SVG renderer of the browsers I tested. I created a small test example:

![grafik](https://user-images.githubusercontent.com/3725906/67081829-3a7b6880-f198-11e9-9620-6a00791f3aa3.png)

Any idea how we can fix this?

---

This is the the problematic SVG

```
<svg id="test" width="600px" height="100px" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
  <g xmlns="http://www.w3.org/2000/svg">
    <rect fill="#67b7dc" width="600" height="100" />
    <text fill="#fff" transform="translate(20,20)" font-size="25" dy="20">
        Text and <tspan style="font-size:70%" dy="0.3em">subscript</tspan> and <tspan style="font-size:70%" dy="-0.7em">superscript</tspan>
    </text>
  </g>
</svg>
```

**Comment by gabelerner** [comment]
the problem is that `if (s.match(/%$/)) return this.numValue() * svg.ViewPort.ComputeSize(viewPort);` does %'s from the `viewPort` (in this case the height of the svg/parent element) whereas we should be doing font sizes off the last defined font-size (25px). hopefully this helps somebody open a PR against this problem.

**Comment by m55c55** [comment]
@gabelerner thanks for the hint, I'll give it a try

**Comment by m55c55** [comment]
After my changes, there still seems to be a slight difference in the calculation of the dy offsets, but at least to font-size calculation seems to be appropriate now.

![grafik](https://user-images.githubusercontent.com/3725906/67157393-a3471a00-f32b-11e9-90bf-d3e2e41a4523.png)
