### ISSUE TITLE
Vertical alignment issue after applying dy in tspan

### ISSUE THREAD

**Issue by m55c55** [canvg/canvg#750]
Hi, 

I have one more weird SVG that is not properly rendered (also after applying the fix from https://github.com/canvg/canvg/issues/748). 

See the alignment of the `O` in H2O.

![grafik](https://user-images.githubusercontent.com/3725906/67282271-ab40be80-f4d1-11e9-9e93-889d794d54b1.png)

This is the SVG's source code: 

```
<svg id="test" width="600px" height="500px" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
  <g xmlns="http://www.w3.org/2000/svg">
    <rect fill="#67b7dc" width="600" height="500" />
    <text class="annotation-text" style="font-family: sans-serif; font-size: 40px; fill: rgb(68, 68, 68); fill-opacity: 1; white-space: pre;" x="20" y="40">H​<tspan style="font-size:70%" dy="0.3em">2</tspan><tspan dy="-0.21em">​</tspan>O​</text>
  </g>
</svg>
```

Any idea where I can look for the root cause of this issue?

**Comment by gabelerner** [comment]
seems related ... if on `master` you change the `font-size:70%` to `font-size:20px`, everything lines up:

![image](https://user-images.githubusercontent.com/241819/67362898-08b02c00-f521-11e9-9ea2-ba2dc92334f3.png)

it's definitely the way that we're doing font sizes and percents. another thing that i never got around to implementing is that `svg.emSize` is just a number but should be more of a "stack" in the sense that every time it changes you push and then when you're done rendering you pop and the current emSize is what is at the top of the stack. this is similar to what we do with the canvas context and i think needs to be extended here for this to properly work.

**Comment by m55c55** [comment]
Hi @gabelerner , the last weeks I played around some time with this issue. And I got some progress locally, but I did not get to a satisfying solution yet. Sadly, I won't be able to continue working on this for the next weeks.

**Comment by gabelerner** [comment]
Hey @m55c55 we got the big typescript refactor into master on version 3.0 (and included your prior PR). this allows us to have more confidence in future fixes and I think I can get to this issue fairly soon on that codebase. please set your projects up off the new 3.0 API and provide any feedback to us there and this should get in fairly soon.

**Comment by m55c55** [comment]
Hi @gabelerner , happy to hear that the transition to TypeScript happened. It will make the future development much more robust and less trial-and-errorish. We will move to canvg 3.0 as soon as it was released and provide feedback as soon as anything comes up.
