### ISSUE TITLE
Data Attribute with Markup in It

### ISSUE THREAD

**Issue by gonzofish** [canvg/canvg#755]
Here's a jsfiddle: https://jsfiddle.net/gonzofish/e3ytvp1g/56/

Notice that only the black rectangle (`svg2`) is rendered. This is because in the markup for `svg1` there is a dataset attribute (`data-unformatted`) with an angle bracket in it (`<`):

```html
data-unformatted="Dyson (US) < Consideration [Positive]"
```

Removing this bracket or replacing it with `>` renders `svg1` with no problem.

**Comment by gabelerner** [comment]
this is just an invalid svg which no library can handle - chrome gives a similar error
![image](https://user-images.githubusercontent.com/241819/68080504-0cae3a80-fdba-11e9-8daf-50a712130e5a.png)
