### ISSUE TITLE
Potential updates to make for 3.0.0

### ISSUE THREAD

**Issue by gabelerner-kernel** [canvg/canvg#756]
1) Can we eject `.eslintrc` so we can edit it here for our future needs?
2) Can we eject `.browserlistrc` so we can edit it here for our future needs? 
3) Issue 104 is broken (in both v2/v3, need to move it to broken, this is my mistake from earlier - i went through all the generated images and v3 matches or beats v2 on all of them!) <== never mind it's already listed in `broken`
4) Should we add back jsfiddle/codepen link for people to replace/submit issues?
5) Do we want to support the existing browser use cases:
5a) Explain to people how to use it w/o `yarn` using cdns including the dependencies?
5b) `canvg()` without parameters replacing everything?
5c) `.drawSvg(...)` support (may be useful on node also)?
6) ` image.crossOrigin = 'Anonymous'` needed?

@dangreen thoughts?

**Comment by dangreen** [comment]
@gabelerner 
1) Yes, but there is also tslint config. Soon I want to move from tslint to typescript-eslint in all my projects. So, for now, I suggest to leave `.eslintrc` as is . 
2) yes
5a) umd bundle with all dependencies inside: https://unpkg.com/@flexis/canvg@3.1.1-beta/lib/umd.js
5b) `canvg()` is like fallback for old browsers, without svg support. Currently all modern browsers support it. I think people, who still need fallback like this, can just use canvg@2.
5c) I don't think what this still need.

**Comment by gabelerner** [comment]
some fixes in https://github.com/canvg/canvg/pull/762

**Comment by dangreen** [comment]
@gabelerner Can you please connect dependabot and coveralls to the repo?

**Comment by gabelerner** [comment]
@dangreen done on those 2!

**Comment by dangreen** [comment]
@gabelerner 

> what do you think about releasing 3.0 officially? Is there anything else you'd want to get in?

I want to finish this fix https://github.com/canvg/canvg/pull/787, then we can publish v3.

**Comment by kallelat** [comment]
Any estimates for the release of v3? Just spend a few hours just to notice npmjs has v2 but all the docs (here) are for v3 😅

**Comment by gabelerner** [comment]
The v2 docs are in the main page of npm. That is where people should be looking for how to use it. GitHub just hosts the latest code so it will be out of sync until we release. I think we're a PR away from releasing but beta is pretty stable if you want to install that from npm and start using. The API is not expected to change.

**Comment by dangreen** [comment]
@kallelat https://www.npmjs.com/package/canvg/v/3.0.0-beta.3

**Comment by kallelat** [comment]
thanks @dangreen and @gabelerner - I guess anyone can learn new things even at this age, didn't even consider possibility that npmjs could have "newer" versions than the latest/stable 😅 

the api might have not changed, but with v2 my ts configuration didn't like it and complained a lot - not sure when this project had ts introduced, but with v3 it seems work out of the box...

**Comment by gabelerner** [comment]
V3 was built on TS and is far easier to manage. The API won't change between 3-beta and actual 3 but did change between 2 and 3.

**Comment by dangreen** [comment]
@gabelerner 
Please check https://github.com/canvg/canvg/pull/787 and https://github.com/canvg/canvg/pull/813
If it's ok I think we are ready to publish stable v3 release 🚀

**Comment by gabelerner** [comment]
i pushed out https://www.npmjs.com/package/canvg/v/3.0.0-beta.4 so we can close out the issues behind the PR. i opened up https://github.com/canvg/canvg/pull/815 so we can update the changelog/etc there

**Comment by gabelerner** [comment]
🎉

**Comment by dangreen** [comment]
🚀

**Comment by gabelerner** [comment]
https://news.ycombinator.com/item?id=21704633 made a post there, might hit up `/r/programming` too to get some more interest

**Comment by dangreen** [comment]
@gabelerner My small contribution: https://twitter.com/dangreen58/status/1202600061680734208 😃
