### ISSUE TITLE
test page doesn't resize source svg

### ISSUE THREAD

**Issue by gabelerner** [canvg/canvg#770]
@dangreen i undid this from the other PR, maybe you can provide a good solution!

in test/browser, rendering the default hello world:
![image](https://user-images.githubusercontent.com/241819/68267980-3f01a700-0009-11ea-8a6c-1f79cb45d361.png)

whereas just rendering the svg on it's own should show the 50px/50px offset:
https://jsfiddle.net/gju38pok/

the expectation is that the right side also shows the 50px/50px offset

**Comment by dangreen** [comment]
#786
