### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by mitesh-shah** [canvg/canvg#812]
Can this library be used in Angular 7 with Ionic 4?

**Comment by dangreen** [comment]
@mitesh-shah yes

**Comment by mitesh-shah** [comment]
@dangreen Could you please help me with some sample example?

**Comment by dangreen** [comment]
@mitesh-shah Please use [stackoverflow.com](https://stackoverflow.com/) for questions like this

**Comment by mitesh-shah** [comment]
Understood. 👍 
But, couldn't find any example on it? So asked here.

**Comment by dangreen** [comment]
@mitesh-shah There are 5 usage example in readme 

https://github.com/canvg/canvg#usage

**Comment by mitesh-shah** [comment]
@dangreen None of them seems to be in Angular 2+ (Typescript)

**Comment by dangreen** [comment]
@mitesh-shah Almost all examples are also valid TypeScript code

**Comment by mitesh-shah** [comment]
@dangreen Ok, If you say so. :)
But, all of them are in Javascript.

**Comment by gabelerner** [comment]
Typescript is a superset of JavaScript. All JavaScript is valid Typescript but not the other way around. Also, Angular is just a framework - canvg supports all JavaScript frameworks you just call the functions in the right place. If you need more help understanding where to do that in Angular you can use stackoverflow.
