### ISSUE TITLE
canvas.toDataURL('image/jpeg', 1) failed

### ISSUE THREAD

**Issue by Undo101** [canvg/canvg#878]
I got the canvas after v.render({...}), and then I use the canvas to carry out "canvas.toDataURL('image/jpeg', 1)", it was failed,  hint me:
 "DOMException: Failed to execute 'toDataURL' on 'HTMLCanvasElement': Tainted canvases may not be exported."
I can't find out what was tainted, can you help me?

**Comment by dangreen** [comment]
https://www.unblu.com/en/docs/latest/knowledge-base/html-tainted-canvas-limitation.html


пн, 6 янв. 2020 г. в 18:18, Undo101 <notifications@github.com>:

**Comment by Undo101** [comment]
Thank you for your reply!
I'm sure the server of img has set the header: Access-Control-Allow-Origin: *;
Also I write the attribute in my js code: img.setAttribute('crossorigin', 'anonymous');
even l even went into the source code of canvg and added this attribute to createImage；
but to no avail
![image](https://user-images.githubusercontent.com/26062774/71815723-5e758880-30bb-11ea-9ef2-3289eb204f12.png)

**Comment by Undo101** [comment]
Thank you for your reply!
I'm sure the server of img has set the header: Access-Control-Allow-Origin: *;
Also I write the attribute in my js code: img.setAttribute('crossorigin', 'anonymous');
l even went into the source code of canvg and added this attribute to createImage；
but to no avail
image

**Comment by Undo101** [comment]
Thank you for your reply!
I'm sure the server of img has set the header: Access-Control-Allow-Origin: *;
Also I write the attribute in my js code: img.setAttribute('crossorigin', 'anonymous');
l even went into the source code of canvg and added this attribute to createImage；
but to no avail
![image](https://user-images.githubusercontent.com/26062774/71815818-a72d4180-30bb-11ea-8c78-1eed8efceec9.png)

**Comment by dangreen** [comment]
@Undo101 

https://stackoverflow.com/a/20562223

> Seader set Access-Control-Allow-Origin "*"
> Header set Access-Control-Allow-Headers "referer, range, accept-encoding, x-requested-with"

**Comment by Undo101** [comment]
I found the reson, not only config the response header allow-origin, but also set the crossOrigin  for the image in the canvg;
![image](https://user-images.githubusercontent.com/26062774/71824162-d485e980-30d3-11ea-8556-0cc9856133c5.png)
Actually,I have been guessing that it is caused by crossOrigin, because I used "canvas.toDataURL" directly before without problems, but I have made a mistake in debugging, which has caused me to fail to verify;
Can you urgently fix this problem so that my code can be submitted for testing tomorrow, otherwise I need to fork and introduce my own fixed code;

**Comment by Undo101** [comment]
I see that you have set it in the createImage function, but it is commented out. I want to know Why?

**Comment by dangreen** [comment]
@Undo101 It should be under the option, as it was in v2. I will done it soon.

**Comment by Undo101** [comment]
Thank you so much, your reply is so fast.
Can i use it tomorrow？or I need to modify it myself in my program.

**Comment by Undo101** [comment]
Hello, dangreen, Could you update the package in NPM.

**Comment by dangreen** [comment]
@gabelerner ?

**Comment by gabelerner** [comment]
sorry on pacific time and work 9-5, it's done now

**Comment by Undo101** [comment]
Hey, guys, I found that only the readme file is updated in npm, there is no option for anonymousCrossOrigin in index.es.js.
![image](https://user-images.githubusercontent.com/26062774/71872675-1c4e5480-3158-11ea-8dbb-9e636ef615ac.png)
![image](https://user-images.githubusercontent.com/26062774/71872763-57508800-3158-11ea-98b8-2565bbd35c8d.png)
@gabelerner @dangreen

**Comment by dangreen** [comment]
Package is not published yet.

вт, 7 янв. 2020 г. в 13:17, Undo101 <notifications@github.com>:

**Comment by dangreen** [comment]
@gabelerner can you publish v3.0.3 soon?

**Comment by gabelerner** [comment]
hmm i used `cleanPublish` but must have done it wrong. i published/unpublished so now republishing.

**Comment by gabelerner** [comment]
ok try 3.0.4 ...

**Comment by Undo101** [comment]
3.0.4 is ok!  This fix really helped me a lot, thank you very much, love you ❤️

**Comment by dangreen** [comment]
https://github.com/canvg/canvg/pull/880
