### ISSUE TITLE
feColorMatrix not working

### ISSUE THREAD

**Issue by Rydori** [canvg/canvg#897]
I wanted to use a ColorMatrix, but rendering it just ignored the filter
The following is the interesting part out of the svg
```
<defs>
	<filter id="aquamarin">
		<feColorMatrix in="SourceGraphic" type="matrix" values="0.0941176470588235 0 0 0 0, 0 0.7686274509803922 0 0 0, 0 0 0.8784313725490196 0 0, 0 0 0 1 0"></feColorMatrix>
	</filter>
</defs>

<image style="overflow:visible;" width="100" height="100" xlink:href="image.png"  transform="matrix(1 0 0 1 355 0)" filter="url(#aquamarin)">
</image>
```

**Comment by Rydori** [comment]
it seems to be a problem with the evaluation of the filter and transform, the following works in my svg (also here only the problematic code)
```
<defs>
	<filter id="aquamarin">
		<feColorMatrix in="SourceGraphic" type="matrix" values="0.0941176470588235 0 0 0 0, 0 0.7686274509803922 0 0 0, 0 0 0.8784313725490196 0 0, 0 0 0 1 0"></feColorMatrix>
	</filter>
</defs>
<g transform="matrix(1 0 0 1 355 0)">
<image style="overflow:visible;" width="100" height="100" xlink:href="image.png"  filter="url(#aquamarin)">
</image>
</g>
```

**Comment by gabelerner** [comment]
can you send your whole svg w/ any images?

using your filter on a rect works for me:
```
<svg>
  <defs>
         <filter id="aquamarin">
		<feColorMatrix in="SourceGraphic" type="matrix" values="0.0941176470588235 0 0 0 0, 0 0.7686274509803922 0 0 0, 0 0 0.8784313725490196 0 0, 0 0 0 1 0" />
	</filter>
  </defs>
  <rect fill="gray" x="1" y="1" width="100" height="100" filter="url(#aquamarin)" />	
</svg>
```

![image](https://user-images.githubusercontent.com/241819/73153940-7f157a80-408a-11ea-95f9-498c9a4d748b.png)

**Comment by Rydori** [comment]
the problem is only present when you apply the filter on an rect or image or whatever when the element with the filter-attribute has also a transform attribute that for example translates it

**Comment by Rydori** [comment]
This works:
`<svg>
  <defs>
         <filter id="aquamarin">
		<feColorMatrix in="SourceGraphic" type="matrix" values="0.0941176470588235 0 0 0 0, 0 0.7686274509803922 0 0 0, 0 0 0.8784313725490196 0 0, 0 0 0 1 0" />
	</filter>
  </defs>
<g transform="matrix(1 0 0 1 355 0)">
  <rect fill="gray" x="1" y="1" width="100" height="100" filter="url(#aquamarin)" />	
</g>
</svg>
`

and this not:
`<svg>
  <defs>
         <filter id="aquamarin">
		<feColorMatrix in="SourceGraphic" type="matrix" values="0.0941176470588235 0 0 0 0, 0 0.7686274509803922 0 0 0, 0 0 0.8784313725490196 0 0, 0 0 0 1 0" />
	</filter>
  </defs>
  <rect fill="gray" transform="matrix(1 0 0 1 355 0)" x="1" y="1" width="100" height="100" filter="url(#aquamarin)" />	
</svg>
`
(tested on https://canvg.github.io/canvg/demo/index.html today)

**Comment by dangreen** [comment]
@Rydori Thanks for an issue.

@Rydori @gabelerner I can take it soon

**Comment by dangreen** [comment]
@Rydori  Hi! Before release you can test fix on demo page: https://canvg.github.io/canvg/demo/index.html?url=../svgs/issue897a.svg

**Comment by dangreen** [comment]
@Rydori  canvg@3.0.6 was released
