### ISSUE TITLE
Option to supress warnings - Feature Request

### ISSUE THREAD

**Issue by Belisarith** [canvg/canvg#944]
When importing an svg there might be a lot of console warnings, which might be helpful for debugging purposes, but not later on. However, I would like to suppress the console warnings of canvg. Warnings like the following are not really helpful, if you cannot change the svg source: 
![image](https://user-images.githubusercontent.com/8216815/74552196-f8e7a800-4f54-11ea-9ff8-ee5432fba93a.png)

**Comment by gabelerner** [comment]
is it getting in the way of debugging other things?

**Comment by dangreen** [comment]
@Belisarith  canvg@3.0.6 was released
