### ISSUE TITLE
Project management

### ISSUE THREAD

**Issue by dangreen** [canvg/canvg#985]
@gabelerner How about to try github's project management?

https://github.com/features/project-management/

Can you create "Development" project with template "Automated kanban with reviews"?

**Comment by gabelerner** [comment]
@dangreen done and invited you to org. hopefully that works

**Comment by dangreen** [comment]
@gabelerner better to create project on repo, not on organisation

**Comment by gabelerner** [comment]
yea you're right, i just didn't see where to do it at first. now it should be there @dangreen
